### ISSUE TITLE
Functional route composition

### ISSUE THREAD

**Issue by mjackson** [reactjs/react-router#1877]
I've been doing a lot of thinking about the way we currently compose route config. I think the high-level API is actually quite good, but the internals could be made a lot simpler and more flexible.

There's [a Medium article](https://medium.com/@vslinko/isomorphic-router-in-functional-paradigm-92959effc29c) by @vslinko where he describes a system of composing routes together to ultimately create a new function that can be used to compute a "screen". His routing function returns a `Promise`, which I'd like to avoid since it means we can no longer do fully synchronous transitions. But it's an interesting read, and I'd like to explore doing something similar here, at least internally. Not sure if we should expose something like this as public API yet.

**Comment by vslinko** [comment]
When I wrote this article I forgot that return type could be combined. 

Now I think transition function could be like that:

```
type Transition = (url: Url) => ?(Promise<Screen> | Screen)
```

**Comment by gaearon** [comment]
Don't forget about Observables :-). You don't have to use Rx or something else to fulfill Observable contract: it's just `{ subscribe({ next, return, throw }) => { dispose() } }`.

The nice thing about observables is that they can be synchronous. The router, perhaps, can be described as `Observable<Location> => Observable<Location>` where the input observable is *desired* locations and the output observable is *actual* locations. How it fits with screens, I haven't thought, but again, `Observable<Location> => Observable<Screen>` can be obtained from `Observable<Location> => Observable<Location>`.

**Comment by mjackson** [comment]
> Don't forget about Observables :-). You don't have to use Rx or something else to fulfill Observable contract

Absolutely. Our history objects are obvservables.

Here, I'm thinking more about a method for composing a route config programmatically instead of using our current `createRoutes` function.

Now that the 1.0 dust has settled, would you like to take a stab at a PR for this @vslinko ?

**Comment by vslinko** [comment]
@mjackson I can do that but after one or two weeks.

**Comment by mjackson** [comment]
Awesome, thank you @vslinko :) Looking forward to seeing what you come up with.

**Comment by knowbody** [comment]
@vslinko any luck on this? let us know if you need any help.

**Comment by vslinko** [comment]
Sorry, but I have no time for OSS for several months, because I have 3 huge deadlines. :fire:

**Comment by knowbody** [comment]
@vslinko do you mind giving some guidance on that so maybe I can implement it?

**Comment by taion** [comment]
What are our current thoughts here?

I think we've ended up moving in a different direction for things like async data fetching with tools like async-props and react-router-relay.

Is this kind of composition still relevant?

**Comment by vslinko** [comment]
I don't know how this is actual today because I didn't follow `react-router` progress last months.
And I have no power to dig it out again and refactor core functionality of the `react-router`.

**Comment by taion** [comment]
I'm going to close this out for now – I think in context, this is an implementation detail from our perspective.

In practice I also think that https://github.com/reactjs/react-router/issues/2922 is a larger concern for debug-ability, and we'd need to be careful not to compromise on that.

Thanks!
