### ISSUE TITLE
Absolute paths for dynamically loaded route config

### ISSUE THREAD

**Issue by johanneslumpe** [reactjs/react-router#2244]
Currently we do not support absolute paths for components which are dynamically loaded. A very manual but working solution for this could be to hand a map of `absolute path -> relative path` to the router, in which the router can lookup the specified route and determine whether it should use the actual absolute route or one which would be gradually matched. Example: 
``` javascript
const map = {
  '/someAbsolutePath': '/this/will/get/matched'
};
```
The url would show `/someAbsolutePath` but internally the router would match against `/this/will/get/matched`.

I just did a tiny test and this seems to work just fine but I am sure there are issues in terms of determining whether a route is active or not since the absolute path isn't registered on the component which is being displayed, but is just an alias for another route.

If this were to be supported first-class by the router (maybe using an alias prop on the route), then the active link checking could still work. Have you already thought about something like this?

Not having the ability to use absolute paths with dynamically loaded routes is a bitter pill to swallow. I'm aware that it is like this because we cannot scan the routes for absolute paths, as they haven't been loaded yet. That is why I think supplying a manually created alias map would at least in some way ease the pain. Sure it's not as comfortable, but it would definitely be better than losing the ability for absolute paths within nested UIs, right?

@mjackson @ryanflorence would love to hear your thoughts on this.

**Comment by taion** [comment]
cc @adamziel

https://github.com/rackt/react-router/issues/2177#issuecomment-154418408 is essentially stealing this top-level route mapping idea in the context of allowing userspace assignment of names to routes.

**Comment by taion** [comment]
Ref https://github.com/reactjs/react-router/issues/3172 – I am thinking that we'd be better off dropping this feature entirely.

**Comment by taion** [comment]
Closing in favor of new patterns from #3172. Will re-open if we decide not to go forward with #3172.
