### ISSUE TITLE
Sites Using React Router

### ISSUE THREAD

**Issue by knowbody** [reactjs/react-router#2412]
I'll be interested to see the sites which are using React Router. We could include that on our upcoming website.

To keep this thread clean please include just a link and maybe a short description of the site, something like:

* [My site](http://linktomysite.com) - short description...

THANK YOU!

**Comment by gaearon** [comment]
[Stampsy](http://stampsy.com/) — A single place to share, curate and discover visual content that tells a story.

**Comment by mattapperson** [comment]
houstonapp.io -- Deploy your react native app updates without going through the app store!

**Comment by bripkens** [comment]
[Instana](https://demo.instana.io) — Keep your systems healthy by applying expert knowledge and visualizing system landscapes in 3D.

**Comment by AnSavvides** [comment]
[gofurther](http://gofurtherapp.com/) — Finding the hidden secrets that only the locals know (not launched yet, out soon)

**Comment by jblock** [comment]
[Trunk Club](http://www.trunkclub.com/) — We pair you with a personal stylist (an actual person) that helps you look great without you having to do any work

**Comment by gusaiani** [comment]
[www.comidadagente.com.br](comida da gente) — peer-to-peer organic groceries (soon)

**Comment by raulmatei** [comment]
[PropertyBook](https://propertybook.ro) - real-estate properties aggregator - React Router v0.13.x - moving to version 1 but we're waiting for the stable release.

**Comment by ayrton** [comment]
[Product Hunt](https://producthunt.com) - Product Hunt is a curation of the best new products, every day. Discover the latest mobile apps, websites, and technology products that everyone's talking about.

**Comment by terinjokes** [comment]
[CloudFlare](https://www.cloudflare.com) - A bunch of internal projects, and (hopefully) soon a new external project.

**Comment by morinted** [comment]
[Stenodict](http://tedmor.in/stenodict)—*in [development](https://GitHub.com/morinted/stenodict)*—a website for stenographers to publish their free dictionaries, as part of the Open Steno Project.

**Comment by danieljuhl** [comment]
[AkutBolig.dk](http://www.akutbolig.dk) - Portal for rental homes

[Boligbesked.dk](http://www.boligbesked.dk) - Instant notification service for tenants seeking a rental home

**Comment by jamischarles** [comment]
PayPal. You know what we do :).

**Comment by furqanZafar** [comment]
http://reactiflux.pipend.com - hackable analytics for the reactiflux community on discord

**Comment by Nick011** [comment]
[Hivelocity](https://hivelocity.net) - Dedicated servers and hosting. Used in MyVelocity control panel.

**Comment by giogonzo** [comment]
[oxway](http://app.oxway.co) - consulting through collective knowledge

[lexdo.it](https://www.lexdo.it/) - personalized legal documents in minutes

[hailadoc](https://www.hailadoc.com/login) - online medical consultations

**Comment by JustinCarmony** [comment]
[Deseret News HS Sports](http://www.deseretnews.com/sports/high-school/) - High School sports coverage & stats for the state of Utah. Soon the rest of Deseret News, as well at the National Edition, will be using React Router. :) We also have several internal projects using it.

**Comment by burtyish** [comment]
[Yeloha](https://app.yeloha.com/get_panels/select) - The solar sharing network: Enable _anyone_ to switch to solar power, regardless of where they live and their economic status.

**Comment by adamrneary** [comment]
[WI](wi.co) - collaborative tools for the industrial enterprise.

**Comment by evanc** [comment]
[https://app.liveplan.com/](LivePlan) - The world’s leading business plan software

**Comment by rickharrison** [comment]
[Meadow](https://getmeadow.com) - On-demand medical cannabis.

**Comment by finalfreq** [comment]
<a href="http://www.cloudability.com/">Cloudability</a> - Data-driven Cloud Cost Management

**Comment by dimaip** [comment]
[Izm.io](http://izm.io) - Worldview survey website + [source code](https://github.com/dimaip/encultN)

**Comment by iyoukeyyewei** [comment]
51visa.com - Online visa service website

**Comment by okcoker** [comment]
[vimeo.com](https://vimeo.com) - Upcoming stats platform and user settings pages. More on the way I'm sure.

**Comment by nettofarah** [comment]
ifttt.com - If This Then That (new website still in dev)

**Comment by mull** [comment]
[qlearning.io](https://qlearning.io) - We simplify studying

**Comment by hsinha** [comment]
[commonfloor.com](https://www.commonfloor.com/) - Online Real-estate Listing site in India (Used in the Mobile Version)

**Comment by winkler1** [comment]
[React.rocks](http://react.rocks) - Pinterest-style directory of React examples, with code.

**Comment by jokka** [comment]
[konceptapp.com](https://konceptapp.com) — Usability testing in a prototyping phase

**Comment by StevenFrostwick** [comment]
[Time Out Love London Awards](http://timeout.com/london/lovelondonawards)

**Comment by aweiksnar** [comment]
[Zooniverse](https://www.zooniverse.org/) - Crowdsourcing platform for scientific research

**Comment by mgreer** [comment]
[Alive! with Joan] (https://alivewithjoan.com) - A video community for women with breast cancer and their friends and families.

**Comment by tedpennings** [comment]
[New Relic](http://newrelic.com). We're using it for a handful of new projects and features, some of which ship in two weeks at our annual conference.

**Comment by KyleAMathews** [comment]
[RelateRocket](https://relaterocket.co) — Startup building social proof tools for sales & marketing.

**Comment by Radivarig** [comment]
[radivarig.github.io](http://radivarig.github.io) - a website with my opensource projects and demos

**Comment by Kilte** [comment]
[My Own Last.FM](http://scrobbler.leichnam.com)

**Comment by LestaD** [comment]
@nettofarah, no, ifttt.com on Angular.js!

**Comment by nettofarah** [comment]
@LestaD I'm a web engineer at IFTTT. I can assure you we don't have anything in Angular.

**Comment by LestaD** [comment]
@nettofarah

![image](https://cloud.githubusercontent.com/assets/5620073/10924276/a6cf96c0-8296-11e5-89f0-6923baf51fce.png)
But i don't see React.

Angular it's my mistake.

![image](https://cloud.githubusercontent.com/assets/5620073/10924297/d0abdbac-8296-11e5-890b-059451d20fa7.png)

**Comment by LestaD** [comment]
![image](https://cloud.githubusercontent.com/assets/5620073/10924324/09045768-8297-11e5-97b4-8968bb3b61fa.png)

**Comment by spikebrehm** [comment]
[Airbnb](https://www.airbnb.com)

**Comment by alexmcpherson** [comment]
[Kapost](http://kapost.com/) - Leading enterprise content marketing platform

**Comment by tommyjp** [comment]
<a href="http://www.jemoticons.com/">Jemoticons</a> - Japanese Emoticons

**Comment by tomatau** [comment]
[junior search engine](http://yoursearchengine.wizenoze.com/) - a search engine for children of different reading levels

**Comment by Simonify** [comment]
[Minbox](http://minbox.com) - Cloud file sharing for your company.

**Comment by Webkadabra** [comment]
http://brainfock.org/ - Brainfock, project management, CRM, CMS. I plan to Opensource it ASAP

**Comment by robyoder** [comment]
[1Password for Teams](https://start.1password.com/signin) – team password management – [main site](https://1password.com)

**Comment by marcelpanse** [comment]
https://teletext.io - Javascript based content management as a service. you can manage your content with an inline wysiwyg editor directly in your custom made (react) website.

**Comment by rossthedevigner** [comment]
[DiscoveryVR](DiscoveryVR) - A new way to see your world. Get a first glimpse at our experiments in virtual reality.

**Comment by kellyrmilligan** [comment]
[Tastemade](https://www.tastemade.com) - Food and Travel content for the experience generation

**Comment by kmoe** [comment]
[Kahoot!](http://getkahoot.com) - a game-based learning platform

**Comment by fson** [comment]
[Reindex](https://www.reindex.io) - GraphQL backend as a service

**Comment by lencioni** [comment]
[Brigade](https://www.brigade.com) — platform that lets you express your opinions on news and politics, see how you compare with friends on current issues and events, and ultimately build movements for democratic change.

**Comment by hejld** [comment]
[ProductBoard](www.productboard.com) - Beautiful product management for those who strive to discover and make products people really want.

**Comment by TheSisb** [comment]
[Discord](https://discordapp.com) - Free voice and text chat for gamers.

**Comment by svk31** [comment]
[OpenLedger](https://bitshares.openledger.info) - Hosted wallet for the cryptocurrency Bitshares.

**Comment by unodgs** [comment]
[Jaworzyna](http://jaworzyna.com.pl) - summer and winter camps for kids

**Comment by rovolution** [comment]
[Social Tables](https://www.socialtables.com/) - The #1 software for planners and properties to work together online

**Comment by ghempton** [comment]
[Outreach](https://outreach.io) - We make entire sales organizations more effective

**Comment by majjoha** [comment]
[Zendesk](https://www.zendesk.com/) - Cloud-based customer service software solution.

**Comment by SohKai** [comment]
[ascribe](https://www.ascribe.io/) - Digital attribution on the Internet backed by blockchain technologies

**Comment by agirton** [comment]
[Twitter Flight School](https://twitterflightschool.com) a learning program that helps advertisers integrate Twitter into their work.

**Comment by zebapy** [comment]
[Fateseal](http://fateseal.com) - a Magic: The Gathering deck building website and community

**Comment by andresgarza** [comment]
[Schoolhub](https://www.schoolhub.com) - The easiest and simplest way for teachers and students to manage their courses, assignments, exams, and more

[Schoolhub Students](https://students.schoolhub.com) - Schoolhub's students portal/app

[Schoolhub Teachers](https://teachers.schoolhub.com) - Schoolhub's teachers portal/app

**Comment by sstefoss** [comment]
[geekbot.io] (https://geekbot.io) - Asynchronous stand-up meetings in Slack

**Comment by tommyjp** [comment]
[LennyFaces.net](http://www.lennyfaces.net/) - Cheatsheets for various lenny faces (⌐▀͡ ̯ʖ▀)

**Comment by wedranb** [comment]
[Uber](https://www.uber.com/) - Uber is the smartest way to get around.

**Comment by mwilliams-change** [comment]
[Change Politics](https://www.changepolitics.org) - Elections by the people. Ask questions to candidates and view endorsements from the people you trust.

**Comment by dklewis** [comment]
[HotPads](https://hotpads.com) - Apartment and home rental search engine

**Comment by ncuillery** [comment]
[6play](http://www.6play.fr) - Catchup TV of the french TV channels M6, W9 and 6ter

**Comment by hegdeashwin** [comment]
[Elastic Hub](https://github.com/hegdeashwin/elastic-hub) An Elasticsearch plugin which can be deployed on own server to monitor and manage Elasticsearch instances, clusters, nodes, indices etc with Web Application.

**Comment by mjackson** [comment]
Wow, this is quite a list :) Thank you, everyone, for chiming in.

@knowbody You ok if we close this for now, just to keep the issue tracker tidy? Maybe we could move the list to a wiki or something?

**Comment by knowbody** [comment]
yup, I'll move this to the new docs

**Comment by orouz** [comment]
is there an updated list somewhere?

**Comment by mjackson** [comment]
Good question, @orouz. We should start a doc in the repo somewhere.
