### ISSUE TITLE
Empty path in route with optional param (possible bug?)

### ISSUE THREAD

**Issue by nickdima** [reactjs/react-router#3074]
I have this routes:

```js
<Route name="artist" path="/artist/:artistVanityId" component={h('artist')}>
  <Route name="artist-albums" path="albums(/:page)" component={h('artist/albums')} />
  <Route name="artist-community" path="feed(/:page)" component={h('artist/feed')} />
  <Route name="artist-overview" path="(:page)" component={h('artist/overview')} />
</Route>
```

The last children route matches `/artist/Foo/10` just fine but not also `/artist/Foo` which gets matched by the parent route instead.
Could this behaviour be a bug or is it expected to be like this?

**Comment by timdorr** [comment]
You need an `IndexRoute`. The search pattern is looking for the final trailing slash in the URL, which isn't there in your example. So, it's not proceeding to the nested routes.

**Comment by taion** [comment]
Right – by design, matching terminates as soon as you hit an exact match for the path. At that point, you need index routes.

**Comment by nickdima** [comment]
Yeah, ideally the `IndexRoute` would match also the optional `:page` part but it's not possible.
Are you saying I should have one `IndexRoute` and another route for `:page` pointing to the same component?

**Comment by taion** [comment]
Correct – otherwise in matching, even after making an exact match, we'd still have to iterate through all child components to see if any of them have an optional match to the empty string. That doesn't sound like the right thing to do.

**Comment by moonsift** [comment]
Note from v4 IndexRoute has been replaced with exact property:
` <Route exact ...>`
Much better!
