### ISSUE TITLE
Navigating Outside Of Components not so simple

### ISSUE THREAD

**Issue by damienleroux** [reactjs/react-router#3079]
Hi all,

I read : https://github.com/reactjs/react-router/blob/fe9358adc864c556afff6fd472476ab84ce2d7d9/docs/advanced/NavigatingOutsideOfComponents.md

I was interested in calling History without having to pass it to component props. I tries it and I note that the wrapped History provided by React-router cannot be used this way.

React-Router adds functions (isActive for example) to History when passing History to Router component. Using History from History.js as module doesn't provide the History from react-router.

Is there any way to make the History wrapped object from react-router a module?

Thank you

**Comment by timdorr** [comment]
This is provided in 2.0: https://github.com/reactjs/react-router/blob/master/docs/guides/NavigatingOutsideOfComponents.md

**Comment by damienleroux** [comment]
Actually is doesn't give the same history.

When importing the history I obtain those functions:
![image](https://cloud.githubusercontent.com/assets/12717418/13052338/a6c7fb68-d3fe-11e5-86d1-06011e19eb4c.png)

When using the one given by react-router through the context, I obtain those:
![image](https://cloud.githubusercontent.com/assets/12717418/13052369/cb8ec42c-d3fe-11e5-8337-1a9023056ba7.png)

As you can see, some functions where added. My question was how can I make the modifed History a module?

I need to use isActive() but cannot find it on the imported history.
