### ISSUE TITLE
Encoded characters "%25" and "%5E" got decoded in params

### ISSUE THREAD

**Issue by yangshiliang** [reactjs/react-router#3081]
Hi! First of all, thanks for the great library!

Recently when I am using react-router 0.13.3, I met an encoding/decoding issue which I don't understand.

code pen: http://codepen.io/yangshiliang/pen/zrbZKa

I passed the encoded string to the Link as params.

Orignal string:
as*()@#$&%^

Encoded string:
as*()%40%23%24%26%25%5E

String from router:
as*()%40%23%24%26%^

It seems that in params %25 and %5E are decoded into % and ^ correspondingly，while other encoded characters are not.

Why does react router has a behaviour like this? Anyone can explain?

Many thanks!

**Comment by taion** [comment]
0.13.x is no longer supported.

**Comment by yangshiliang** [comment]
I have tried react-router 2.0.0. All the encoded characters are decoded, which means I can simply remove my own decodeURIComponent and everything is fine. 

But before I can switch to the latest react-router, I am afraid I have to use some workarounds.  Thanks again.

FYI,
code pen: http://codepen.io/yangshiliang/pen/Goeagj

Results:
Orignal string:
as*()@#$&%^

Encoded string:
as*()%40%23%24%26%25%5E

String from router:
as*()@#$&%^
