### ISSUE TITLE
onUpdate-like callback for Route components

### ISSUE THREAD

**Issue by kadmil** [reactjs/react-router#3082]
Hello, guys! Thank you for your awesome work!

I'm a bit puzzled with such issue. In an app I have news feed, and want to fire request to fetch data every time route with feed is visited. This can be achived with `onEnter` hook and works just perfect. Then I want to add pagination and fetch new chunk on route update, I have two options: switch to firing from inside the components or use `onUpdate` callback handler on Router itself. If I don't want to fire any updates from components, I should re-implement route matching in order to use `history` and decide which app route was re-visited on update.

I've seen issues about re-firing `onEnter` on query params change (like in my pagination case, where each page is encoded with `?offset=10` query param). Is there a API design reason for not adding a hook like `onUpdate` to `Route`?

**Comment by taion** [comment]
Dupe https://github.com/reactjs/react-router/issues/2547
