### ISSUE TITLE
<Link to> with relative link broken?

### ISSUE THREAD

**Issue by Pomax** [reactjs/react-router#3085]
I have a router set up as 
```
<Router>
    <Route path='/' component={Root}>
...
      <Route path='section1' component={require('../pages/section1.jsx')}>
        <Route path='details' component={require('../pages/section-details.jsx')} />
      </Route>
...
    </Route>
</Router>
```
and in the `section1.jsx` have a `<Link to='./details/'>details</Link>`, but this doesn't resolve correctly at all. The browser shows a link that "should" go to `.../section/details` according to the browser status bar, but clicking it results in a react-router error instead:

```
Warning: [react-router] Location "./details/" did not match any routes
```
If I turn this `<Link>` into an `<a>` things work find but of course then I lose all the benefits of navigation inspection etc.

https://github.com/reactjs/react-router/blob/latest/docs/API.md#link does not say anything about relative links being broken, so: is this a bug, or is this intended? And if intended, what's the proper way to get a `<Link>` going to a relative path?

**Comment by timdorr** [comment]
Relative `<Link>`s aren't supported yet. Watch #2172.

**Comment by Pomax** [comment]
Now watching (but it does look like that issue died about a month ago rather than being on track).

Can we at least reopen this issue and make its closing contingent on the docs being appended with a note that `<Link>` cannot currently do relative links itself, with some code that shows how someone can build the absolute path using whatever contexts are available in a component in the mean time?

Given that URLs are the backbone of the web, it's pretty important to note that `<Link>` does not currently work as new users will expect it to.

**Comment by timdorr** [comment]
It's not dead. We were waiting on some API changes with 2.0 so that we can work on it.

**Comment by timdorr** [comment]
Check #2933 if you have some documentation improvements. PRs are the best way to get it solved! :smile:

**Comment by Pomax** [comment]
They most certainly are - but I clearly don't know as much about `<Link>` as people active on this project, so the best people to write that doc improvement is in this case not-me =) I don't even know what code to write to get an current absolute path so I can even work around this issue. Is there some documentation or an issue that already explains that?
