### ISSUE TITLE
[API Proposal] Passing down properties to route components

### ISSUE THREAD

**Issue by perrin4869** [reactjs/react-router#3090]
I want to propose a new API to achieve the above. First, let's review the two solutions that I can come up with available right now:

* Higher order components

Basically, here you bind some properties to the route component with a higher order component, and pass that new component to the route component:

```javascript
const bind = (Component, boundProps) => (
  ((props) => <Component {...props} {...boundProps} />)
)

const boundIndex = bind(Index, indexProps);
const boundFoo = bind(Foo, fooProps);
const boundBar = bind(Bar, barProps);

<Route path="/" component={App}>
    <IndexRoute component={boundIndex} />
    <Route path="foo" component={boundFoo} />
    <Route path="bar" component={boundBar} />
</Route>
```

This is, incidentally, the approach I'm following right now. The downside of this approach is the need of an additional wrapping component which can be omitted with the APIs that I want to propose, and the extra `bind` function, plus boilerplate code.

* Switch statement and context handling

This one has much more boiler plate and I haven't tested it, but it should work.

```javascript
const App = ({ location, children }, { indexProps, fooProps, barProps }) => {
    switch(location.pathname) {
        case '/': return React.cloneElement(children, indexProps);
        case '/foo': return React.cloneElement(children, fooProps);
        case '/bar': return React.cloneElement(children, barProps);
        default: return children;
    }
} 

<ContextProvider>
<Route path="/" component={App}>
    <IndexRoute component={Index} />
    <Route path="foo" component={Foo} />
    <Route path="bar" component={Bar} />
</Route>
</ContextProvider>
```

The downsides to this approach are the boilerplate code, where you have a verbose switch statement, the expensive `React.cloneElement` call and the `ContextProvider` element which relies on the unstable `context` API.

The API that I want to propose would look like this:

```javascript
<Route path="/" component={App}>
    <IndexRoute component={Index} componentDependencies={indexProps} />
    <Route path="foo" component={Foo} componentDependencies={fooProps} />
    <Route path="bar" component={Bar} componentDependencies={barProps} />
</Route>
```

There is no boilerplate code, it's expressive and there are no extra components or elements required to make it happen, at least as far as I can see. Now I spent around 20 minutes writing down my detailed arguments I would definitely appreciate it that, even if you reject my arguments, at least you do me the courtesy of engaging them and not dismiss them outright as I've seen you do in the past.

**Comment by taion** [comment]
Your premise is mistaken because you're running in dev mode: https://github.com/facebook/react/blob/v0.14.7/src/isomorphic/ReactIsomorphic.js#L33

**Comment by perrin4869** [comment]
Thanks for the response.
OK, I'm guessing that by premise you mean that `React.cloneElement` is an expensive function. Fair enough, but even if I give you that there is still the extra switch statement, context provider and unstable context API. I mean, is my proposed API hard to implement? Does it have downsides I didn't think about?   If so, which of my 2 original solutions would be the better one?

One more thing is, this issue keeps coming up all the time, yet there are no examples in this repo tackling the issue. If you want I can add them and send via a pull request. Just tell me which of the two methods above to use.

**Comment by taion** [comment]
We always appreciate documentation contributions.

The correct pattern for doing what you're trying to do is to use `this.props.route` and to read the values from the route object (e.g. any props on the JSX route) via that approach.

**Comment by perrin4869** [comment]
I see! Thanks, I will submit an example using this approach then, since this has to be documented.

Still, there is a downside to this approach, and it is that it changes the way components expect their attributes to be passed. Therefore, it limits their reusability. If you want to use the same component in a non-react-router setting, you need to collect the parameters in a different manner. Although it could be easily accomplished by:

```javascript
const Component = (props) => {
    if(props.route) props = { ...props, ...props.route.dependencies }
}
<Route component={Component} dependencies={{ foo: "bar" }} />
```

Is there a reason why the above can't be the default behavior?

**Comment by perrin4869** [comment]
The thing is, I had a component before I started using React Router in my current project, and this approach makes me modify the component which worked very well, and raises complexities of its own. I still think that a way to inject dependencies directly into a component should be provided, although I can be persuaded otherwise.

**Comment by timdorr** [comment]
You can also use the `createElement` prop on `<Router>` to do this. It receives the `route` prop, which you can spread into individual props or whatever you want.

**Comment by perrin4869** [comment]
@timdorr cool! Still, this wouldn't work in an isomorphic environment where `<Router>` is not used and only `<RouterContext>` is

**Comment by timdorr** [comment]
[It's passed into `<RouterContext>`](https://github.com/reactjs/react-router/blob/master/modules/RouterContext.js#L24), so you can use it on the server too.

**Comment by perrin4869** [comment]
That's awesome! I just tested it, love the unopinionated solution :)
I'll make an example using this approach and submit it via a pull request then

**Comment by jarsbe** [comment]
Just for anyone arriving here looking for how to pass props into a Routers Route components.

```
class App extends Component {

  render() {
    return (
      <Router history={browserHistory} createElement={createElement(this.props)}>
        <Route path="/" component={MyComponent} />
      </Router>
    )
  }
}

function createElement(originalProps) {
  return function (Component, props) {
    return <Component {...props} {...originalProps} />
  }
}
```

**Comment by oelmekki** [comment]
is there a reason this isn't the default? Loosing ability to pass 
properties to components is quite a problem.

Anyway, thanks for workaround!
