### ISSUE TITLE
Routes matching issue

### ISSUE THREAD

**Issue by iamgutz** [reactjs/react-router#3092]
I'm having issues matching the routes, I'm using "react-router": "^2.0.0-rc5" and also tried with "react-router": "^2.0.0"
I have the following router:
`<Router>`
   `<Route component={SimplePage} path='page/simple-page' />`
   `<Route component={SearchPage} path='page/search/?q=:query' />`
   `<Route component={OtherPage} path='page/:pagename' />`
`<Router>`

When going directly to http://localhost/page/simple-page the component SimplePage is shown, that's correct
When going directly to http://localhost/page/some-page-name the route OtherPage is shown, that's correct
When going directly to http://localhost/page/search/?q=something the route OtherPage is shown, this is incorrect I need the SearchPage component to be shown

The interesting part is that it works fine when navigating to the page with the <Link> Component, but when navigating directly to the URL through the browser it doesn't work.

Can you help?

**Comment by timdorr** [comment]
Don't add the query variable to your path. That will come via the route component's props.

**Comment by mxstbr** [comment]
To elaborate on what Tim said, change the search route to `<Route component={SearchPage} path='page/search' />`, and then in your `SearchPage` component you have access to `this.props.location.query` which will include the query string. (See [here](https://github.com/reactjs/history/blob/master/docs/Glossary.md#location) for more information)

**Comment by iamgutz** [comment]
Thanks guys!
