### ISSUE TITLE
Animation broken with Router 0.13 and React 0.14

### ISSUE THREAD

**Issue by ncuillery** [reactjs/react-router#3094]
## Version
0.13.5

## Test Case
Few updates on the animation example on branch `0.13.x`:
https://github.com/ncuillery/react-router/commit/944df1dbcaf9ac0481b4340330b5b7860a31a121
I use React 0.14 as we are supposed to do (no warning) and I increased the animation duration up to 10s

## Steps to reproduce
- Clone my fork
- Run `npm i`
- Run `npm run examples`
- Go to http://localhost:8080/animations/#/page1
- Click on link "Page 2"

## Expected Behavior
**Smooth animation from Page 1 to Page 2**

## Actual Behavior
**No animation, Page 2 shows up immediately**

It seems that the `CSSTransitionGroup` still does his job but the "leaving" component (a `RouteHandler`) is transitioning to the new route without animation while the "entering" component shows up:
![capture du 2016-02-18 10 00 59](https://cloud.githubusercontent.com/assets/4425455/13139578/87a838e8-d62d-11e5-9757-b9462c989b7c.png)

Have you a fix in mind ?

**Comment by taion** [comment]
0.13.x is no longer supported.

**Comment by ryanflorence** [comment]
Animation issues like this was a major motivation for the 1.0 API, so yes, the fix in mind is 1.0 :) There are upgrading guides that should help you make the transition in the repo.

**Comment by ncuillery** [comment]
I would like to bump React from 0.13 to 14 on a huge project. You guys have made efforts to keep the 0.13.x branch compatible with React 0.14 (#2262), I was hoping I wouldn't have to bump react-router too.

It seems I'll have to :unamused: 

Thanks for your answer anyway.

**Comment by gaearon** [comment]
There are some issues that are solveable without rewriting everything. (Such as supporting a newer version of React.)

There are some other issues that require you to rethink the approach and solve the problem differently. The animation problem falls into the second bucket. The whole approach in RR 0.13.x was problematic, which is one of the reasons 1.0+ exists. We don’t want to deliberately make things harder for you, but unfortunately in this case the only fix is to upgrade to the new API which solves your problems.
