### ISSUE TITLE
Can I write pre-fetch code in onEnter.

### ISSUE THREAD

**Issue by zenato** [reactjs/react-router#3096]
Hello, 

I need pre-fetched data before open page. (similar `resolve` of `anuglar-ui-router`)
Can I write pre-fetch(using ajax and etc..) code in `onEnter`?

**Comment by timdorr** [comment]
No, because that will not fire when navigating between the same nodes of the route tree. Use React lifecycle methods to achieve this.

**Comment by ryanflorence** [comment]
Check out my experimental project ryanflorence/async-props for some ideas.
