### ISSUE TITLE
No this.context.router exists

### ISSUE THREAD

**Issue by holymonson** [reactjs/react-router#3100]
## Version
2.0.0

## Steps to reproduce
After upgrade to 2.0, we followed the warning
```text
Warning: [react-router] `props.history` and `context.history` are deprecated. Please use `context.router`. http://tiny.cc/router-contextchanges
```
and found in the doc
> Only an object named router is added to context. Accessing this.context.history, this.context.location, and this.context.route are all deprecated. This new object contains the methods available from history (such as push, replace) along with setRouteLeaveHook.

However, no `this.context.router` exists, so we have no choice but using deprecated `this.props.history`. 
Could you please provide more detail in docs on how to move to 2.0?

Addtional Info: we are using ES6 class to create `React.Component`.

<img width="750" alt="2016-02-19 18 35 17" src="https://cloud.githubusercontent.com/assets/902012/13173429/5c280ade-d738-11e5-8538-e05af5b1b5fa.png">

## Expected Behavior
 `this.context.router` exists

## Actual Behavior
no `this.context.router` exists

**Comment by holymonson** [comment]
Sorry, https://facebook.github.io/react/docs/context.html fix our issues, perhaps refer the context usage on docs could help others. Thanks.

**Comment by neezer** [comment]
For anyone arriving at this issue running into the same problem and are looking for a quicker solution than reading [the aforementioned react doc](https://facebook.github.io/react/docs/context.html), the trick is this:

> If `contextTypes` is not defined, then `this.context` will be an empty object.

**Comment by yinzSE** [comment]
`this.context.router` is a tortured little fairy.

**OBJECT** not **FUNCTION**

Homepage.contextTypes = {
  router: React.PropTypes.object.isRequired
}
