### ISSUE TITLE
createMemoryHistory not using location path

### ISSUE THREAD

**Issue by jarsbe** [reactjs/react-router#3101]
I'm trying to get server side rendering working with the new router/history api changes. The trouble is with the history object. 

I've read the server side docs etc but I am not trying to render EVERYTHING with react. Just a small "app" which uses react router.

I would set up a js lint but it's an express problem... 

## Steps to reproduce

This runs on the client fine with browserHistory passed in. 
``` 
function TabsRouter(history) {

  class TabsRouterClass extends Component {
    render() {
      return (
        <Router history={history}>
          <Route path='/owner/repo' component={Tabs}>
            <IndexRoute component={Code} />
            <Route path="issues" component={Issues} />
            <Route path="pulls" component={Pulls} />
          </Route>
        </Router>
      )
    }
  }

  return TabsRouterClass
}
```

On the server

```
...
import { createMemoryHistory } from 'react-router'
import { createLocation } from 'history'

router.get('/owner/repo', (req, res, next) => {
  const location = createLocation(req.url)
  const history = createMemoryHistory(location)
  const Tabs = TabsRouter(history)
  const tabsApp = renderToString(<Tabs />)

  console.log(tabsApp)
  ...
})
```
## Expected Behavior

The string should render the Code component (from TabsRouterClass) as the req.url is `/owner/repo` but ...

## Actual Behavior

I get `Warning: [react-router] Location "/" did not match any routes` and only a noscript rendered string.

The location object looks correct:

```
{ pathname: '/owner/repo',
  search: '',
  hash: '',
  state: null,
  action: 'POP',
  key: null }
```

Versions:

```
"history": "^2.0.0",
"react": "^0.14.7",
"react-dom": "^0.14.7",
"react-router": "^2.0.0",
```

If there's anything I can do to make resolving this easier let me know. Could be history related but figured the projects are tightly coupled.

**Comment by taion** [comment]
Follow the server rendering guide. This is a usage error.

**Comment by jarsbe** [comment]
@taion Ah thank you. After splitting the `Router` away from the child `Route`s and using `match` everything works correctly. 

Make sure you pass the routes to `match` correctly:

`match({ routes, location: req.url }, ...` is the equivalent of:

`match({ routes: routes, location: req.url }, ...`
