### ISSUE TITLE
Multiple onEnter/onLeave Hooks on <Route>

### ISSUE THREAD

**Issue by bjlewis88** [reactjs/react-router#3103]
## Summary
I think it might be very helpful to allow users to pass either a single function (as they currently can) or an array of functions (proposed new feature) to the onEnter and onLeave props of Route components. I think this could allow developers to create much more powerful and flexible actions on route transitions.

## Example Use Case
This is something that has come up in the app I'm working on now. As the router is currently configured, every leaf route has a single onEnter hook that dispatches actions to fetch all data dependencies from the server and then records page views for Google Analytics. This works pretty well right now because every leaf route does both of those things, so we only need one hook. However, we're starting to run into cases where some routes have more highly customized needs, particularly with analytics.

I'll explain one such case in more detail. Certain routes may have referrer tokens in the query string that we would like to capture and send to Google Analytics. Unfortunately, we can't just rely on the normal referral URL that GA automatically sends on initialization, since these referral links could be placed on arbitrary domains. For those routes (and only those routes), I would like to send an event to Google Analytics that contains the referral token. Unfortunately, adding this new onEnter functionality to some routes and not others requires that we write a new hook for those particular routes. I don't see that as a scalable solution. Plus, providing a good name for that function is a nightmare - which to me is a major code smell.

Our workaround right now is to put the custom, route-specific actions in the lifecycle hooks of the route handler components themselves. It's functional, and it doesn't strike me as hack-y. But it's not the ideal solution to my mind. I think enabling multiple onEnter hooks would provide a simpler, more expressive, and declarative way for us to create these more flexible transition actions.

## Code Sample
    /* Suggested API for passing multiple onEnter hooks */

    <Router history={History}>
      <Route path="/" component={App}>
        <Route path="recommendations" component={Recommendations} onEnter={ [fetchDataForComponents, recordPageView, recordReferralToken] } />
        <Route path="profile" component={Profile}>
          <IndexRoute component={requireAuth(ProfileMain)} onEnter={ [fetchDataForComponents, recordPageView] } />
          <Route path="edit" component={requireAuth(ProfileEdit)} onEnter={ [fetchDataForComponents, recordPageView] } />
        </Route>
      </Route>
    </Router>

## In Closing
It's possible that I'm missing something that makes this feature either unnecessary or very difficult to implement with the current API. Perhaps there's a cleaner solution to the problem I described above. If that's the case, we can close this issue. Otherwise, I'd be happy to take a run at writing the necessary code.

**Comment by taion** [comment]
It seems like this could be handled adequately via an HoF in user-space:

```js
<Route onEnter={chain(hook1, hook2)} />
```

I don't see the benefit of bringing this into React Router explicitly.

**Comment by bjlewis88** [comment]
@taion You may be right. I had been considering something similar to what you describe here, and on second thought, it probably would work for my use case. A more complicated case would involve multiple async functions where you only want to execute the transition once all hooks that were provided a callback have invoked that callback. I was thinking that such behavior would require a more explicit binding with React Router. But I might be off base there.

**Comment by taion** [comment]
You get to declare the semantics?

Your `chain` function could only invoke latter elements in the chain when callbacks fire. But then if you have multiple async `onEnter` hooks, there arise questions of whether to run them in parallel or in series, or what to do if e.g. more than one of them tries to redirect.

The subtleties especially in the async case mean that I don't see a sufficiently reasonable one-size-fits-all default, so I don't really want to impose something at this level.

**Comment by timdorr** [comment]
I don't think this is a good idea. This suffers from all the subtle problems of `Promise.all`. 

Just use a `compose` implementation. This is solvable with standard FP.

**Comment by bjlewis88** [comment]
Having given it more thought, I think you guys are right that there really isn't a sensible default way to handle the execution sequence, and I have a better idea now of how I could compose these functions in a way that would work well with the existing API for async transitions. Handling the composition outside of React Router offers more flexibility. Thanks for the quick responses.

**Comment by chazsolo** [comment]
@bjlewis88 I've found myself in a similar situation and was wondering if you have any advice for how to compose your hooks and where, outside of the Router, you considered placing them?

**Comment by bjlewis88** [comment]
@chazsolo I wrote a couple of utility functions that you might find useful for composing your hooks. I just put them up on GH [here](https://github.com/bjlewis88/react-router-compose-hooks/blob/master/index.js).

**Comment by chazsolo** [comment]
@bjlewis88 This is very useful - thank you!
