### ISSUE TITLE
Feature Request: Namespace injected props

### ISSUE THREAD

**Issue by glortho** [reactjs/react-router#3104]
The injected props named `location`, `params`, and `routes` that get passed into route components are somewhat generic and disaggregated methinks! This makes for more complexity and less maintainability in cases where you may be passing along a number of other props to child routes,* and/or when you want to collectively store/track/assert something about all props relevant to routing.

For example, when I create my fictitious gps navigation app, having to avoid using `location` and `routes` props, much less the very generic `params` prop, because a 3rd party lib has claimed them will be off-putting indeed!

I assume you have considered this. Why not collect all under `this.props.router` or something like that?

*Though it is clear that [some consider passing props across route boundaries undesirable](https://github.com/reactjs/react-router/issues/2618#issuecomment-160822989), I would argue that there are lots of apps out there (ours included) that reasonably pass props down through nested routes so as to not implement redundant getters for every generation.

**Comment by taion** [comment]
You're not bound to those prop names anywhere other than your top-level components. You can easily rename the props with a shim component, or destructure out just the pieces that you need.
