### ISSUE TITLE
Unexpected behaviour of setRouteLeaveHook

### ISSUE THREAD

**Issue by emmenko** [reactjs/react-router#3106]
Hey guys, 
I'm trying out the new version and noticed a weird behaviour using `setRouteLeaveHook` (which replaces `Lifecycle` mixin). I'm not sure if this is expected behaviour or a bug though.

I've created a simple JSBin example. Basically if a component has for example tabs (`/account(/:tab)`), and you switch between them, you are "navigating" to another route, which in this case happens to be the same route component. 
If I define `setRouteLeaveHook` in `componentWillMount` / `componentDidMount`, the hook gets called only one time because I'm still within the same route component. 
Apparently it appears that after a transition, the listener gets removed. Is that correct? Should I be using `componentWillReceiveProps` / `componentDidUpdate` instead? Or this is actually not the correct behaviour?

Many thanks!

## Version
2.0.0

## Test Case
http://jsbin.com/nutivi/edit?html,js,console,output

## Steps to reproduce
> Make sure to "re-run" the code before each case.

- case 1 (works)
  - click "account"
  - click "dashboard" (see console.log)

- case 2 (works)
  - click "account"
  - click "profile" tab (see console.log)

- case 3 (doesn't works)
  - click "account"
  - click "profile" tab (see console.log)
  - click another tab (e.g. "billing") (no console.log anymore)

- case 3 (doesn't works)
  - click "account"
  - click "profile" tab (see console.log)
  - click "dashboard" (no console.log anymore)

## Expected Behavior
I would expect that whenever I navigate to another route (even if it's mapped to the same component), the hook gets called.

## Actual Behavior
See initial description.

**Comment by taion** [comment]
Need to not call https://github.com/reactjs/react-router/blob/v2.0.0/modules/createTransitionManager.js#L74-L75 on the intersection of `leaveRoutes` and `enterRoutes`.
