### ISSUE TITLE
Feature: useBeforeUnload by default for browser history

### ISSUE THREAD

**Issue by jamiehodge** [reactjs/react-router#3110]
In order to enable useBeforeUnload, one currently needs to import createHistory and useBeforeUnload from history. If I'm not mistaken, listening for unload events would be a sane default for browser history, so why not change the browserHistory export to some variation of `useBeforeUnload(createHistory)()`?

**Comment by taion** [comment]
Is there any cost to attaching a no-op unload listener that we don't use?

This would be a breaking change, anyway.

**Comment by timdorr** [comment]
[It doesn't attach the listener until the first `listenBeforeUnload` hook is added.](https://github.com/reactjs/history/blob/master/modules/useBeforeUnload.js#L47)

**Comment by timdorr** [comment]
Also, is it a breaking change? It only adds an extra API and doesn't change the original history behavior. In fact, it really looks usable without history at all. `useBeforeUnload(() => ({}))()` should work just fine.

**Comment by taion** [comment]
The change is that leave hooks will now always trigger on hard-leaving the page, which is not the current behavior.

**Comment by timdorr** [comment]
Oh, I didn't even know [we handled that](https://github.com/reactjs/react-router/blob/39b36f2af313ce4cd986da4f03d404dc6c5449e6/modules/createTransitionManager.js#L216-L217).

I don't think it's a huge change. What are most people using `onLeave` for? I don't use it myself.

**Comment by taion** [comment]
Route leave hooks, not `onLeave`.

**Comment by timdorr** [comment]
Well, it looks like [our example](https://github.com/reactjs/react-router/blob/master/examples/confirming-navigation/app.js) and [this doc](https://github.com/reactjs/react-router/blob/master/docs/guides/ConfirmingNavigation.md) are wrong/incomplete without this being added. 

I can't think of a reason not to add it by default.

**Comment by taion** [comment]
Well, the example _works_. It just only works when staying within the router, and not for e.g. hard leaving the page or closing the tab.

**Comment by taurose** [comment]
`beforeunload` isn't totally free of side effects. It disables BFCache ([Firefox](https://developer.mozilla.org/en-US/Firefox/Releases/1.5/Using_Firefox_1.5_caching), [IE](https://msdn.microsoft.com/en-us/library/dn265017(v=vs.85).aspx)). This could actually be a good thing though, since [BFCache can break the router](https://github.com/reactjs/react-router/issues/837) and it seems like [we can't support BFCache](https://github.com/reactjs/history/issues/34#issuecomment-148532202) in a clean way using pageshow.

**Comment by taion** [comment]
I'd be fine either way, but I'm not convinced we can make this change without a major version bump.

**Comment by timdorr** [comment]
@taurose Thanks for that insight. Yeah, this sounding more like a straight up improvement. 

@taion At worst, it's a minor bump. We're simply improving an API to cover more cases of "leaving" a route. There is no backwards incompatible change. Existing leave hooks will continue to fire on the same events as always.

**Comment by taion** [comment]
I'm not totally convinced, but I don't care enough either way.

**Comment by timdorr** [comment]
Closing as per #3118
