### ISSUE TITLE
nextState in API docs

### ISSUE THREAD

**Issue by jcalfee** [reactjs/react-router#3111]
Do you have documentation for parameters like `nextState`?  This appears to be only API page but it has only references to `nextState` but I really have no idea how to use it.  Anything will do, even a link into the code.  It is an onEnter callback.

https://github.com/reactjs/react-router/blob/master/docs/API.md#onenternextstate-replace-callback

**Comment by taion** [comment]
Please consolidate on https://github.com/reactjs/react-router/issues/2933.

**Comment by jcalfee** [comment]
Who are you talking too?  I'll just leave it to you, I think you have it covered.

**Comment by jcalfee** [comment]
Guess I'm not getting any help in this ticket.  So in looking in the cod on line 2785 you have `if (route.onEnter) hooks.push(createEnterHook(route.onEnter, route));` .. Guess I will not be getting this to work tonight.

**Comment by taion** [comment]
Per the issue template, usage questions will not be addressed on the issue tracker.

**Comment by gaearon** [comment]
While the docs need improvement you can start by doing `console.log(nextState)`. This should give you some idea of what’s in there, and if some of it looks useful to you, feel free to use it!

**Comment by jcalfee** [comment]
Awesome .. Thank you
