### ISSUE TITLE
unclear animation example

### ISSUE THREAD

**Issue by mgenev** [reactjs/react-router#3117]
No offense, but the animation for example is not that clear. There is no explanation at all, and in particular, what is this and why is it used? I suspect that this is how the pages which are routed to get rendered, but I have no idea really. I'm cloning the children + a key property??

``` 
          {React.cloneElement(this.props.children, {
            key: this.props.location.pathname
          })}
```

**Comment by ryanflorence** [comment]
https://facebook.github.io/react/docs/animation.html

**Comment by hew** [comment]
@mgenev 

The basic idea is that the router is displaying the children of the component, which would be your routes. The ``key`` is an important concept in React animation. It is what allows React to remember which child is which, and animate them accordingly. 

If you try to animate the state of a collection of elements (say, a list) without a key, it will re-render the entire list, as opposed to just the element that was changed. This is the basis for pretty much every list re-ordering library in React.

React Router works in a similar way, where the ``key`` is required to keep track of the router's children. Without the key, the animations do not work. 

It's a little hard to grok, but actually I find React Router's use of children to be right in line with the Reacat philosophy.
