### ISSUE TITLE
Uncaught TypeError: Cannot read property '_currentElement' of null. 

### ISSUE THREAD

**Issue by MilanRgm** [reactjs/react-router#3119]
Can you please see my code on here http://stackoverflow.com/questions/35602862/error-while-using-react-router-in-multi-step-registration-form ? Why is this displaying such error?

Thanks

**Comment by MilanRgm** [comment]
Its been 2 days i haven't got reply . I hope of positive response from here. Is there an compatibility issue ? 
"react": "^0.14.7" and "react-router": "^2.0.0"

**Comment by gaearon** [comment]
I left an [answer](http://stackoverflow.com/a/35776386/458193) on your StackOverflow question. There is no compatibility issue. The components are relying on props that aren’t being passed to them, and are crashing as a result.
