### ISSUE TITLE
Router is undefined with react-router v2.0.0 upon import

### ISSUE THREAD

**Issue by freyconner24** [reactjs/react-router#3122]
when I `import { Router, Route, browserHistory } from 'react-router'`, then `console.log(Router);` I get that Router is undefined.

This is my code:

`"use strict";

import React from 'react'
import { Router, Route, browserHistory } from 'react-router'
import createBrowserHistory from 'history/lib/createBrowserHistory'
import Home from './pages/home.js'
import Entrance from './pages/Entrance.js'
import Courses from './pages/Courses.js'
import Quizzes from './pages/Quizzes.js'
// var Router = require('react-router');
console.log("conner", Router);
console.log("conner", Route);

module.exports = (
  <Router history={browserHistory}>
    <Route path="/" component={Home}>
      <Route path="entrance" component={Entrance} />
      <Route path="courses" component={Courses} />
      <Route path="quizzes" component={Quizzes} />
    </Route>
  </Router>
);`

**Comment by freyconner24** [comment]
May I ask why you closed this issue?

**Comment by ryanflorence** [comment]
it's a question about your broken app, there's no way our exports are wrong w/o being flooded with issues like this. The issue template already explained that we don't do questions in the issue tracker.

**Comment by freyconner24** [comment]
I'm sorry, where should I post my question?

**Comment by ryanflorence** [comment]
When you open an issue it has a template in there with all the links, did
you delete it without reading or did it not show up?
