### ISSUE TITLE
How to passing parent route component's props to child route component

### ISSUE THREAD

**Issue by yinxin630** [reactjs/react-router#3125]
I'm sorry I opened a new issues. I read a lot of issue but did not solve my problem. 
I use `"react-router": "^2.0.0"` and `"redux": "^3.3.1"` in my reactjs app. The problem is that i want get parent route component props and passing to child route component.
such as:
```
<Provider store={ Store }>
    <Router>
        <Route path="/" component={ ConnectedApp }>
            <IndexRoute page="Main" component={ Main }/>
            <Route path="register" component={ Register }/>
            <Route path="login" component={ Login }/>
        </Route>
    </Router>
</Provider>, 
```
The ConnectedApp have redux main store. I define some actions in the ConnectedApp to change store. And I want passing these actions to child component.
How can I do this?

**Comment by yinxin630** [comment]
ok, I came up with a solution self but it looks strange.
```
render() {
    console.log(this.props);
    
    const { user, linkmans, linkmanFocus } = this.props.reducer;
    
    const Child = this.props.children.type;
    const props = {
        Main: {
            user: user,
            linkmans: linkmans,
            linkmanFocus, linkmanFocus,
        },
        Register: {
            
        },
        Login: {
            
        }
    }
    
    return (
        <div style={{
            height: window.innerHeight,
            display: 'flex',
            flexDirection: 'column',
        }}>
            <Header/>
            { React.createElement(Child, props[Child.name]) }
        </div>
    );
}
```
I judge the child component's type and structure props what it needs. Then I manually create child component and passing props to it. Yes, this way can solve my question. But is there any other way can do this also?

**Comment by ryanflorence** [comment]
The issue template you deleted said to look at the examples before posting a question, here is the example with an identical name to your issue here:

https://github.com/reactjs/react-router/tree/master/examples/passing-props-to-children
