### ISSUE TITLE
Relative URLs / basename

### ISSUE THREAD

**Issue by joneslloyd** [reactjs/react-router#3129]
## Version
2.0.0

## Test Case
Hi there,

I'm not sure if my issue is relevant. Please let me know if that's the case.

I have a React 'app' existing on a page which itself is already a querystring (WordPress back-end admin page, as it happens).

My code containing my Router is as follows:

```
import React from 'react';
import ReactDOM from 'react-dom';
import { Router, Route, useRouterHistory } from 'react-router';
import { createHashHistory, useBasename } from 'history';

const appHistory = useRouterHistory( createHashHistory )({
	queryKey: false
});

import NotFound from './components/NotFound';
import InstancePicker from './components/InstancePicker';
import App from './components/App';

/*
	Routes
*/
var routes = (
	<Router history={appHistory}>
		<Route path="/" component={InstancePicker} />
		<Route path="/instance/:instanceId" component={App} />
		<Route path="*" component={NotFound} />
	</Router>
)

ReactDOM.render( routes, document.querySelector( '#fuelled-lunch-menu' ) );
```

The app's starting url is `http://example.com/wp-admin/admin.php?page=my-app` but when I navigate to a another Route (`browserHistory.push( '/instance/' + instanceId );`) the URL changes to `http://example.com/instance/343`

I've tried using a baseurl but that doesn't seem to be working.

I'm unsure whether this is an issue with my code or the router

## Steps to reproduce
browserHistory.push( '/any-route/' + an_int_variable_containing_the_id );

## Expected Behavior
Relative URL change

## Actual Behavior
Entire URL updates, losing the current page I'm on

**Comment by mxstbr** [comment]
The forward slash (`/`) in the route is a reset and makes it absolute. Changing the route without the leading slash should fix the issue: `browserHistory.push( 'instance/' + instanceId );`

> Note: Thanks for the detailed bug report, appreciate it!

**Comment by joneslloyd** [comment]
Thanks for the quick response!

Doing as you've said results in `http://example.com/wp-admin/instance/290` (rather than `http://example.com/instance/290`) but the desired behaviour is `http://example.com/wp-admin/admin.php?page=my-app/instance/290` (or anything that preserves that querystring/page)

**Comment by mxstbr** [comment]
I have no experience with that, but using `hashHistory` might work:

```JS
hashHistory.push( 'instance/' + instanceId );
```

**Comment by joneslloyd** [comment]
That actually solved it perfectly. Thanks a lot :) Much appreciated.

**Comment by mxstbr** [comment]
No worries, could you close this issue if that's everything you need? Thanks!

**Comment by joneslloyd** [comment]
Okay! Thanks again
