### ISSUE TITLE
Using onLeave hook and confirming navigation simultaneously?

### ISSUE THREAD

**Issue by echenley** [reactjs/react-router#3132]
I need to fire an action `onLeave`, but only after the user confirms navigation. The current API doesn't seem to allow for both without the following workaround.

I could use `componentWillUnmount`, but I have route transition that prevents the component from being unmounted immediately. My current workaround is something to the effect of:

```js
// routes.js

<Route
  path="/:id"
  onEnter={ fetchData }
  onLeave={ clearData }
  component={ DataWrapper }
>
// other routes...
```

```js
// DataWrapper.js

let hookAdded = false;

class DataWrapper extends Component {
  static contextTypes = {
    router: React.PropTypes.object
  };

  componentDidMount() {
    const { router } = this.context;
    const { route } = this.props;

    // don't keep adding onLeave hooks
    if (!hookAdded) {
      hookAdded = true;
      router.setRouteLeaveHook(route, this.routerWillLeave.bind(this));
    }
  }

  routerWillLeave() {
    if (/* stuff */) {
      // no callback for when confirmed or not?
      return 'Your have unsaved changes! Are you sure you want to leave?';
    }
  }

  render() {
    return <div { ...this.props }/>;
  }
}
```

While it works, it isn't particularly elegant. Is there a better way of doing this?

**Comment by echenley** [comment]
Wow, really? If you had read this before closing you'd realize this is an API issue.

**Comment by echenley** [comment]
For anyone who is looking to a solution to this problem, this is what I ended up doing.

```js
let removeHook = null;

class DataWrapper extends Component {
  static contextTypes = {
    router: React.PropTypes.object
  };

  componentDidMount() {
    const { router } = this.context;
    const { route } = this.props;

    // this check is necessary to avoid setting multiple of
    // the same route hook when navigating to child routes
    if (!removeHook) {
      removeHook = router.setRouteLeaveHook(route, this.routerWillLeave.bind(this));      
    }
  }

  props: Props;

  routerWillLeave() {
    const { actions, undoable, redoable } = this.props;

    removeHook();
    removeHook = null;

    // returning string opens prompt to confirm navigation
    if (/* stuff */) {
      const confirmed = window.confirm(
        'Your have unsaved changes! Are you sure you want to leave?'
      );
      
      if (confirmed) {
        actions.clearData();
      }

      return confirmed;
    }
  }

  render() {
    return <div { ...this.props } />;
  }
}
```

**Comment by echenley** [comment]
For those that may have the same issue:

I had a route transition happening on a parent component. This was causing multiple DataWrappers to be mounted at the same time, which was wreaking havoc on this logic. I moved the route transition to DataWrapper and the problem went away.

**Comment by mahavrilla** [comment]
I'm doing something very similar, my route, is calling my DataWrapper, however I keep getting the following `Uncaught TypeError: Cannot read property 'setRouteLeaveHook' of undefined` has anyone see the same issue using React-Router, and ES6.
