### ISSUE TITLE
isActive not matching routes with route params properly

### ISSUE THREAD

**Issue by tjgupta** [reactjs/react-router#3136]
## Version
2.0.0

## Test Case
https://github.com/reactjs/react-router/pull/3134/files#diff-ac4398acd480b9df6457b7676c9b5cb4R84

## Steps to reproduce
Use isActive() on a route that uses route params, something like /items/:itemId

## Expected Behavior
isActive('/items/:itemId') should return true if the current route is '/items/1'

## Actual Behavior
isActive('items/:itemId') does not return true at the route '/items/1'

**Comment by taion** [comment]
This is entirely an error on your part. Look at the passing tests in https://github.com/reactjs/react-router/pull/3135 and the test coverage for `<Link>`.
