### ISSUE TITLE
Docs about this.props.location.state.nextpathname in v2

### ISSUE THREAD

**Issue by littlee** [reactjs/react-router#3138]
Can you guys provide some docs about `this.props.location.state.nextpathname` in v2?

I am trying to upgradge from v1 to v2

in v1, I can access `this.props.location.state.nextpathname`
but in v2 `this.props.location.state` is always `null`

**Comment by timdorr** [comment]
#2933

**Comment by jonboylailam** [comment]
@littlee I think this is what you are looking for... https://github.com/reactjs/react-router/blob/master/examples/auth-flow/app.js

function requireAuth(nextState, replace) {
  if (!auth.loggedIn()) {
    replace({
      pathname: '/login',
      state: { nextPathname: nextState.location.pathname }
    })
  }
}

**Comment by bhishp** [comment]
It doesn't look like this works in v3? How would one do the equivalent of the above in v3? Thanks
