### ISSUE TITLE
useBasename doc missing

### ISSUE THREAD

**Issue by degr** [reactjs/react-router#3140]
In previous version (1.0.3) version of router, I use this code sample to do useBasename,

```
import { createHistory, useBasename } from 'history';
var history = useBasename(createHistory)({
    basename: '/project/preffix/'
});
```
(https://github.com/reactjs/history/issues/61)

 and all my routes start's from '/project/preffix/'. Now, as I can see, you include history inside of 'react-router' library. Should I work with my old code, or I need to do something with react-router lib history implementation?

**Comment by degr** [comment]
Link?

**Comment by degr** [comment]
I found, sorry
https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md#custom-query-string-parsing

**Comment by wchest** [comment]
For anyone looking for a solution for this issue, it is in the react-router documentation, but in a different spot: https://github.com/reactjs/react-router/blob/master/docs/guides/Histories.md#customize-your-history-further

Note: You must use a preceeding  `/` for the `basename` to work correctly. So from the example above, it would need to be `basename: '/base-path'` for the basename to work correctly.

**Comment by pkosenko** [comment]
With react-router@2.6.1 I get the error "TypeError: _history.useBasename is not a function" generated by my bundle.js
