### ISSUE TITLE
About "huge-apps" example

### ISSUE THREAD

**Issue by vieks** [reactjs/react-router#3141]
Not really related to react nor react-router, but what the purpose of:
`<!doctype html public "embarassment">`
in this file:
https://github.com/reactjs/react-router/blob/master/examples/huge-apps/index.html 

Assigning a FPI to an html5 doctype is not valid right ?

**Comment by timdorr** [comment]
@ryanflorence Any idea why that's there? You added it :P

**Comment by mxstbr** [comment]
LOL

**Comment by ryanflorence** [comment]
My code is embarassing, and lots of it is public.

[There](https://github.com/reactjs/react-router/blob/master/examples/active-links/index.html#L1) [are](https://github.com/reactjs/react-router/blob/master/examples/auth-flow/index.html#L1) [others](https://github.com/reactjs/react-router/blob/master/examples/confirming-navigation/index.html#L1).

**Comment by vieks** [comment]
Trololol

**Comment by Munter** [comment]
I haven't tested this, but I'd like to know which browsers get thrown into quirksmode by the invalid DTD, making this sort of a self fulfilling prophecy

**Comment by ryanflorence** [comment]
It's harmless.

**Comment by rossipedia** [comment]
> My code is embarassing

I'd really like to see code that _isn't_ embarrassing, then :)
