### ISSUE TITLE
Router 2.0 get next path for refreshing properly

### ISSUE THREAD

**Issue by AlexNexcom** [reactjs/react-router#3143]
Hi there! 

I have an React/Flux App that uses Authentication. I use an Auth service, whick makes a call to the API and then triggers an Action that dispatches the action to the AuthStore (where i save the username, role, etc..) and saves the user props in localStorage. Then, this action must redirect to '/home' or to the route that i was trying to go. At the beggining of the app, i check if username is set in localStorage to call the login action again.

Some code...

```javascript
//app.jsx
let username = localStorage.getItem('username');
let role = localStorage.getItem('role');
if (username && role){
    AuthActions.login(username, role);
}
```

```javascript
//app.jsx
login: (username, role) => {
        var savedUserName = localStorage.getItem('username');
        var savedRole = localStorage.getItem('role');
        AppDispatcher.dispatch({
            actionType: AUTH_LOGIN,
            username: username,
            role: role
        });
        if (savedUserName !== username) {
            hashHistory.push('/home');
            localStorage.setItem('username', username);
            localStorage.setItem('role', role);
        }
        else {
            //GO TO CURRENT ROUTE || HOME
            //hashHistory.push('/home');
        }
    },
```
And the router...
```javascript
var router = (
    <Router history={hashHistory}>
        <Route path="/" component={App}>
          <Route path="login" component={Login} />
          <Route path="logout" component={Logout} />
          <Route path="home" component={Home} >
             <Route path="home/users" component={Users}>
             </Route>
           </Route>
        </Route>
    </Router>
```
I see in other versions that u can save the RouterComponent and then do:
```javascript
   var nextPath = RouterComponent.getCurrentQuery().nextPath || '/';
   RouterComponent.transitionTo(nextPath);
```
So how i can translate this into 2.0 version? Im using a hashed history.

The problem is when i'm in /home/users and i refresh the page, it always return me to /home cause i have defined  this behaivour in the action. How can i get the path where i'm refreshing to for redirect to it instead of always redirecting to /home?
 
Thanks all for your support! 

(Sorry about my poor English :P)

**Comment by stupidisum** [comment]
Why is this closed? without any comment or references or solutions?
