### ISSUE TITLE
React-router no longer triggers componentWillReceiveProps

### ISSUE THREAD

**Issue by kayakyakr** [reactjs/react-router#3146]
## Version
2.0.0
React 15.0.alpha1

## Issue
With React 15, the componentWillReceiveProps has been changed to be more discerning when it does fire. React-router's route changes are apparently not enough to trigger the receive props method on children, so on an initial load it works fine, but any navigation after breaks. I'm not sure what side needs the fix, if it's even fixable or force-able from react-router. 

New to using React, so leave it to the new guy to break stuff.

**Comment by kayakyakr** [comment]
This PR caused the change: https://github.com/facebook/react/pull/5787

**Comment by timdorr** [comment]
While this is against a pre-release version of React, it's good for us to stay ahead of the curve on this stuff. Do you have a test case handy?

**Comment by kayakyakr** [comment]
I'm sorry, I don't. And I think my implementation might be moving away from even allowing route transitions at least for the time being, so I'll be moving toward other things.

**Comment by taurose** [comment]
Are you sure about this issue? I couldn't reproduce it with rc1 and one of the examples. Also, the PR reads like `willReceiveProps` fires more often, not less. And I don't think we're doing anything too out of the ordinary when rendering route components.

**Comment by kayakyakr** [comment]
I'll see if I can put together a moment to try to recreate it with a test case or an example.
