### ISSUE TITLE
Custom notification dialogue/modal for setRouteLeaveHook?

### ISSUE THREAD

**Issue by deep-c** [reactjs/react-router#3147]
Hi,

I couldnt find any information online regarding this and the docs only show mention of window.confirm. Is it possible to set a custom notification for routeLeaveHook instead of using `window.confirm`. I created a stackoverflow question regarding this and my particular use case for it in more detail and would like to know if this is currently possible or whether there is a specific reason why we cannot do this and whether this could be something implemented. I have a code example of how I would like to use it inside the question.

Im using react-router 2.0

http://stackoverflow.com/questions/35770438/show-custom-dialog-setrouteleavehook-or-history-listenbefore-react-router-redux

**Comment by DanielSWolf** [comment]
@taion I also think that allowing custom dialogs on route leave would be a useful feature. I don't quite understand why you closed this issue.

**Comment by deep-c** [comment]
@DanielSWolf and @taion  I agree, this seems like something that will become a fairly common requirement. I read the posting guidelines but as far as i am aware react-router does not support this. Can someone at least give me a reason if it can be done or cant be done (and why it wont be implemented if thats the case).

**Comment by DanielSWolf** [comment]
I had the same problem. What it boils down to is that `setRouteLeaveHook` expects the hook to return its result synchronously. This doesn't give you time to display a modal dialog and wait for the user to make a decision. What we need is an *asynchronous* version of `setRouteLeaveHook` that accepts a promise.

I just wrote such a function in [my answer to a similar StackOverflow question](http://stackoverflow.com/a/35793421/52041). It would be great if react-router offered this functionality natively.

**Comment by knowbody** [comment]
Please follow the issue template, @taion closed the issue as it didn't follow the template.

**Comment by screendriver** [comment]
+1

**Comment by DanielSWolf** [comment]
@knowbody I don't follow. The issue template explicitly says

> Have a feature request?
> =======================
> Remove the template from below and provide thoughtful commentary *and code samples* on what this feature means for your product.

To me, this issue clearly is a feature request (allow custom dialogs). So I can't see why @deep-c should have used the template.

**Comment by knowbody** [comment]
@DanielSWolf what feature? we provide the API for Confirming Navigation, that's all you need, the rest it's totally up to you. 

@deep-c is asking on how to do it or what's the best way of doing it, and the issue template advises to ask questions like that on SO or discord where we can help you.

**Comment by deep-c** [comment]
@knowbody would my updated issue qualify as an accepted feature request?

**Comment by timdorr** [comment]
The current behavior is built for an `onbeforeunload`-style listener. The is the standard the web has agreed to, so we're just following it.

But what you're asking for is already possible with `setRouterLeaveHook`. Just throw up your dialog then instead of trying to change a web standard :smile:

**Comment by chauthai** [comment]
:+1:

**Comment by oztune** [comment]
@timdorr if it's modeled with the limitations of `onbeforeunload`, why doesn't it also do the job of `window.onbeforeunload`? As it stands, I need to hack together support for that _and_ implement `setRouterLeaveHook` would be great to have all that taken care of in one place.

I also have a question: if I want to do what you suggest:
> But what you're asking for is already possible with setRouterLeaveHook. Just throw up your dialog then instead of trying to change a web standard :smile:

What is the recommended way to actually perform the navigation once my custom prompt is accepted?

**Comment by timdorr** [comment]
No hacking needed. Just add `useBeforeUnload` to your history instance.

**Comment by tnrich** [comment]
Hey @timdorr and @oztune ,

I'm trying to follow along with your conversation, but don't think I fully understand @timdorr's instructions. 

I too would like to throw up a custom dialog (only some of the time) when a user tries to navigate to an invalid page. The other part of the time, I would like to not even give them the option to move, and instead give a little notification that they can't leave the page until they update their form correctly. Is it possible to do that and if so, could you provide a code example of how to do it? 

Thanks very much!

**Comment by oztune** [comment]
@tnrich As long as the user is navigating within your app via the html 5 history capabilities, you are free to show custom dialogs or even block a transition completely. When the user chooses to leave your domain or do page refresh though, your only option is to use the native dialog box (by returning a string). So, to avoid having two different code paths for your dialogs it may be preferable to always use the string version.

If you want to block a transition within your application you can do something like this:
```
class Comp ... {
	static contextTypes = {
		router: React.PropTypes.object
	}
	
	componentDidMount () {
		this.context.router.setRouteLeaveHook(this.props.route, () => {
			if (userShouldntLeaveYet) {
				return false
			}
		})
	}
}
```

**Comment by oztune** [comment]
@timdorr Thanks for the tip! I'm assuming you're referring to something like https://github.com/reactjs/react-router/issues/3110

Right now I'm using `browserHistory`. Is it possible to add `useBeforeUnload` without creating my own?

**Comment by taion** [comment]
@oztune 

No, sorry. At this point we'd generally recommend creating your own history singletons inside your project, customized per your requirements.

**Comment by oztune** [comment]
@taion Thanks for clarifying. For anyone trying to do this but getting lost in the labyrinth of documentation, here's how I did it:

```
// make sure to npm install history
import { createHistory, useBeforeUnload } from 'history'
import { Router, useRouterHistory } from 'react-router'

const myBrowserHistory = useBeforeUnload(useRouterHistory(createHistory))()

<Router history={ myBrowserHistory } routes={ routes } />
```

Now if you return a string from your `setRouteLeaveHook` callback, it will be used for both soft transitions (those using the HTML5 API) and hard transitions (navigating to a different domain or refreshing the page).

Overall I really like the API, but it would be awesome if this explanation was in https://github.com/reactjs/react-router/blob/master/docs/guides/ConfirmingNavigation.md

**Comment by taion** [comment]
Could you PR an update? I think updating that guide got lost in the shuffle.

**Comment by oztune** [comment]
@taion I'd be happy to do it when I get a free moment

**Comment by git-blame** [comment]
@oztune I tested both newer Firefox and Chrome. With `useBeforeUnload` you do get a prompt with hard transitions. But it will not display your string from `setRouteLeaveHook` but a generic message. This seems to be a security issue: https://bugzilla.mozilla.org/show_bug.cgi?id=588292

**Comment by aislanmaia** [comment]
With History 4.x seems that useBeforeUnload is not used anymore.
