### ISSUE TITLE
<Redirect> doesn't trigger onEnter

### ISSUE THREAD

**Issue by pseidemann** [reactjs/react-router#3148]
hi,
I created some test case:

```jsx
import React from 'react';
import {render} from 'react-dom';
import {Router, Route, Redirect, browserHistory, Link} from 'react-router';

const onEnter = () => {
    console.log('hello from onEnter!');
};

const Test = () => {
    return (
        <div>
            <Link to="/">go to /</Link><br />
            <Link to="/foo">go to foo</Link><br />
            <Link to="/bar">go to bar</Link><br />
            <Link to="/beer">go to beer</Link>
        </div>
    );
};

render((
    <Router history={browserHistory}>
        <Redirect from="/" to="foo" />
        <Route>
            <Route onEnter={onEnter}>
                <Route path="foo" component={Test} />
                <Route path="bar" component={Test} />
            </Route>
            <Route onEnter={onEnter}>
                <Route path="beer" component={Test} />
            </Route>
        </Route>
    </Router>
), document.getElementById('chief-node'));
```

if I'm on `/bar` and I click "go to foo", onEnter isn't trigger, which is expected because I'm navigating in the same "namespace".
**but** if I'm on `/bar` and click "go to /" (which redirects to `/foo`), I would expect that onEnter is called but **it's not**. my guess is that `<Redirect>` isn't really a redirect but more of an rewrite of the target `<Route>`.

however, navigating between `/beer` and `/foo`+`/bar` does trigger onEnter.

not sure if it's a bug.

how can I achieve that a `<Redirect>` triggers the hooks of the route it points to? I would need this for my logout and home url logic.

thanks in advance!

**Comment by knowbody** [comment]
this is not a bug, please post it on SO or discord, someone will be able to help you there.

**Comment by pseidemann** [comment]
stackoverflow question to this in case anyone else is interested: http://stackoverflow.com/q/35796474/616310

**Comment by pseidemann** [comment]
I see that it's not a bug and I think it's good that it behaves like that. 
my use case was that the user got logged out and then a redirect to / should bring him to the login page instead of the redirect target.
I solved this now via doing the logout in a route instead, which can then be safely navigated away to / then, because the logout route doesn't have the onEnter which should be then triggered when entering the redirect target of /.
