### ISSUE TITLE
[Feature Request] Use indexRedirect in route's configuration object

### ISSUE THREAD

**Issue by jgoux** [reactjs/react-router#3150]
Hello,

I tried to use `indexRedirect` in a route configuration object, but it seems that it's ignored.

Would it be possible to add it with a syntax like : 
```js
indexRedirect: { to: "path" },
```

Thanks to all the contributors for this awesome library.

**Comment by mrtnbroder** [comment]
Why was this closed? It's a legitimate feature request @taion.

**Comment by timdorr** [comment]
Does this not work? https://github.com/reactjs/react-router/issues/2256#issuecomment-148249068 (I don't have a test case in front of me, so it's a legitimate question)

**Comment by jgoux** [comment]
I'm sorry,

it seems that my issue is a duplicate of https://github.com/reactjs/react-router/issues/2559

I assumed there were a feature parity between JSX / plain object notation, but apparently I was wrong.

**Comment by taion** [comment]
It works just fine; that's just not the syntax.

**Comment by jgoux** [comment]
@taion Could you point me to the doc showing the right syntax please ?

**Comment by taion** [comment]
No – the issue tracker is not the place for support questions.

**Comment by timdorr** [comment]
@jgoux Click the link in my comment right above yours...

**Comment by jgoux** [comment]
@timdorr This doesn't work for me, I also have an infinite redirect loop, like the last comment on the issue : https://github.com/reactjs/react-router/issues/2256#issuecomment-151993906

The route in question : 
```js
import { view } from "./view"
import { update } from "./update"
import { route as rechercheRoute } from "./components/Recherche"
import { route as saisieRoute } from "./components/Saisie"

export const route = {
  component: view,
  reducer: update,
  onEnter: (_, replaceState) => { replaceState(null, saisieRoute.path) },
  childRoutes: [
    rechercheRoute,
    saisieRoute
  ]
}
```

I assume I have to find the way to redirect only when no child is matched (this is what IndexRoute does).

Sorry to bother you all, I'll continue on stackoverflow/discordapp instead,

have a nice day ! :+1:
