### ISSUE TITLE
BUG: Unexpected behaviour for Active IndexLink with query param

### ISSUE THREAD

**Issue by tdurand** [reactjs/react-router#3151]
## Version
2.0.0

## Test Case
![vkbewonchm](https://cloud.githubusercontent.com/assets/533590/13540978/96bef7c6-e227-11e5-826d-b0cb992b5f12.gif)

here is a gist of the code: https://gist.github.com/tdurand/fafa4020aede5ca6fd53  (based on the active link example) 

## Steps to reproduce

Just click on the second link

## Expected Behavior

`/users IndexLink` link shouldn't be active when `/users&type=test Link` is selected , as it doesn't match the route exactly

## Actual Behavior

`/users IndexLink` is active when `/users&type=test Link` is selected

**Comment by taion** [comment]
https://github.com/reactjs/react-router/pull/2386

**Comment by tdurand** [comment]
Ok thanks, for anyone looking into this, the solution is to explicitly specify undefined for the users type query params on the indexlink route like this:

`<IndexLink to={{ pathname: '/users', query: { type: undefined } }} activeStyle={ACTIVE}>/users IndexLink</IndexLink>`
