### ISSUE TITLE
Strange behavior of IndexRoute

### ISSUE THREAD

**Issue by chrisdziewa** [reactjs/react-router#3159]
I am having an issue where if I click to go to my `/` route, and then click another navbar link, the active class stays on the main page route and isn't removed unless I click two other links. I am using IndexRoute on my link but the child routes don't get set to active right away.

Adding an IndexRoute underneath users worked for logged in routes, but it doesn't work correctly for `/login` or `/signup`. I even tried nesting login and signup under users to no avail.
These are my routes:

```
<Route path="/" component={App} onEnter={currentUserCheck}>
    <IndexRoute component={HomePage} />
    <Route path="/polls" component={PollsPage}>
       <Route path="create-poll" component={CreatePollForm} onEnter={checkAuth} />
    </Route>
    <Route path ="/users">
        <IndexRoute component={UsersPage} />
        <Route path="signup" component={SignupForm} />
        <Route path="login" component={LoginForm} />
        <Route path="edit-user" component={EditProfile} onEnter={checkAuth}/>
        <Route path=":username/:question" component={SinglePollPage} />
        <Route path=":username" component={ProfilePage} />
     </Route>
     <Route path="*" component={NoMatch}/>
</Route>
```

**Comment by chrisdziewa** [comment]
@taion I simply reached out because I am wondering if this is a potential problem that others may also be experiencing. I would at least appreciate a reason for having my issue closed without the courtesy of a reply.

**Comment by skylinezum** [comment]
@chrisdziewa 
I think you need to use an IndexLink

https://github.com/reactjs/react-router/blob/master/docs/guides/IndexRoutes.md

**Comment by chrisdziewa** [comment]
Thanks for the response. I actually did use IndexLink but even though
according to the docs it should've worked how I had it, it was having
unexpected behavior. I ended up just removing active links from my project.

**Comment by ryanflorence** [comment]
https://github.com/reactjs/react-router/blob/master/examples/active-links/app.js

**Comment by chrisdziewa** [comment]
@ryanflorence yeah I had a similar implementation but used activeClassName. It had problems when clicking on a link that was nested or when the route was at the first level of the path. I'm moving on to another project as active links aren't crucial for this project but I will try to get it working in a future project. Thanks for reaching out!

**Comment by ryanflorence** [comment]
Like the issue template says, if you think there's a bug, please make a jsbin showing it, the active link code is pretty battle-tested at this point.
