### ISSUE TITLE
hashHistory does not support push. It only supports pushState

### ISSUE THREAD

**Issue by potsypantsy** [reactjs/react-router#3160]
This is an issue because other parts of the code assume push to be available. https://github.com/reactjs/react-router/blob/master/modules/Link.js#L100

## Version
2.0.0

## Steps to reproduce
import { hashHistory } from 'react-router';
console.log(hashHistory.push) # undefined

I would love to make a pr, but I am not sure what the right fix should be. Currently I added the push function myself before passing the hashHistory into the Router.
```
hashHistory.push = (param) => {
  if (_.isString(param)) {
    hashHistory.pushState(null, param, null);
  } else {
    hashHistory.pushState(param.state, param.pathname, param.query);
  }
};
```

**Comment by taion** [comment]
Your install is messed up.

**Comment by potsypantsy** [comment]
it works with history@2.0.0 but history@2.0.1 broke it.
