### ISSUE TITLE
Can't redirect to external URLs on `onEnter` hooks

### ISSUE THREAD

**Issue by goldensunliu** [reactjs/react-router#3161]
right now the `onEnter` hook only exposes the `replace` function or internal redirects.:
 https://github.com/reactjs/react-router/blob/1fb4f7abb9a7f32a82fb3bc15ace7012fead7885/modules/TransitionUtils.js#L44 

here is the react-router example https://github.com/reactjs/react-router/blob/master/examples/auth-flow/app.js#L122

What about use cases when I would like to redirect an user away from the domain based on auth requirement or feature gating?

**Comment by goldensunliu** [comment]
related discussions:
https://github.com/reactjs/react-router/issues/1434

**Comment by timdorr** [comment]
`window.location = url`

**Comment by goldensunliu** [comment]
@timdorr could you shine some light on how you would do this on the server side?

particularly in the example https://github.com/reactjs/react-router/blob/master/docs/guides/ServerRendering.md
we do 
```
match({ routes, location: req.url }, (error, redirectLocation, renderProps) => {
    if (error) {
      res.status(500).send(error.message)
    } else if (redirectLocation) {
      res.redirect(302, redirectLocation.pathname + redirectLocation.search)
    } else if (renderProps) {
      // You can also check renderProps.components or renderProps.routes for
      // your "not found" component or route respectively, and send a 404 as
      // below, if you're using a catch-all route.
      res.status(200).send(renderToString(<RouterContext {...renderProps} />))
    } else {
      res.status(404).send('Not found')
    }
  })
```
where does your `window.location = url` solution fit in?

**Comment by mmahalwy** [comment]
@timdorr I cannot test `window.location` by stubbing it out, etc.

**Comment by taion** [comment]
Please don't cross-post onto multiple issues.

**Comment by PixnBits** [comment]
Had a [conversation](https://twitter.com/pixnbits/status/753309766059819008) with @timdorr 

> I would just add a static prop on your route components and look for that server side. Not really a good way to do that generally.

So I'm _guessing_ use something like `renderProps.host`?

```
res.redirect(302, renderProps.protocol + renderPros.host + redirectLocation.pathname + redirectLocation.search)
```

@timdorr could we re-open this issue until there's a better way to do this? (Maybe `<ExternalRedirect />`, IDK)
