### ISSUE TITLE
Can't redirect to external URLs on `onEnter` hooks on server side

### ISSUE THREAD

**Issue by goldensunliu** [reactjs/react-router#3162]
right now the `onEnter` hook only exposes the `replace` function or internal redirects.:
 https://github.com/reactjs/react-router/blob/1fb4f7abb9a7f32a82fb3bc15ace7012fead7885/modules/TransitionUtils.js#L44 

here is the react-router example https://github.com/reactjs/react-router/blob/master/examples/auth-flow/app.js#L122

What about use cases when I would like to redirect an user away from the domain based on auth requirement or feature gating?

particularly how you would do this on the server side?

in the `react-router` example https://github.com/reactjs/react-router/blob/master/docs/guides/ServerRendering.md
we do 
```javascript
match({ routes, location: req.url }, (error, redirectLocation, renderProps) => {
    if (error) {
      res.status(500).send(error.message)
    } else if (redirectLocation) {
      /*** This ain't gonna work for external urls. ***/
      res.redirect(302, redirectLocation.pathname + redirectLocation.search)
    } else if (renderProps) {
      res.status(200).send(renderToString(<RouterContext {...renderProps} />))
    } else {
      res.status(404).send('Not found')
    }
  })
```

**Comment by goldensunliu** [comment]
reopening https://github.com/reactjs/react-router/issues/3161

**Comment by timdorr** [comment]
You could put a sentinel value in the `redirectLocation` via state.

**Comment by taion** [comment]
This is not a router-level concern – if you need support for managing locations outside of the SPA, such support belongs in history. Additionally, this is a semantic concern of your application in particular, so I wouldn't expect this to be something supported at the library level.

**Comment by ryanflorence** [comment]
```
match(..., (err, redirectInfo, props) {
  if (redirectInfo) {
    if (redirectInfo.state.external) {
      req.redirect(redirectInfo.state.external)
    }
  }
}

//

const onEnter = (loc, replace) => {
  replace({ state: { external: 'http://example.com' } })
}
```

Might work? Let me know.
