### ISSUE TITLE
Postinstall script is not picking up the correct .babelrc

### ISSUE THREAD

**Issue by GreenGremlin** [reactjs/react-router#3163]
## Version
2.0.0

## Steps to reproduce
1. Create a project with a .babelrc file, without "loose" build enabled
2. Add react-router to project package.json as a github url
```
"react-router": "github:reactjs/react-router#master"
```
3. From project root `npm install react-router`

## Expected Behavior
Should build react-router using `./node_modules/react-router/.babelrc` with babel loose build enabled.

## Actual Behavior
Builds react-router using `./.babelrc` with "loose" build disabled, and thus react-router is not functional.

**Comment by taion** [comment]
This actually can't work beyond a basic best-efforts thing. Given Babel 6, even that isn't really going to be an option. It's not worth our time to deal with this sort of issue, so I'm just going to drop GitHub install support entirely.
