### ISSUE TITLE
Huge bundle size when using react-router

### ISSUE THREAD

**Issue by Mercality** [reactjs/react-router#3167]
If this is a problem with browserify and not react-router please let me know before closing this question, i have been wondering for days why my bundle sizes go up 1.5mb when using react-router

This is my Routes.jsx file

```
var React = require('react');
var Router = require('react-router/lib/router')
var useRouterHistory = require('react-router/lib/useRouterHistory');
var hashHistory = require('history/lib/createHashHistory');
var IndexRoute = require('react-router/lib/IndexRoute');

var Route = require('react-router/lib/Route');

var History = useRouterHistory(hashHistory)({
    queryKey: false
});

var Base = require('./components/Pages/Base.jsx');
var HomePage = require('./components/Pages/HomePage.jsx');
var Historial = require('./components/Pages/Historial.jsx');
var NuevoPedido = require('./components/Pages/NuevoPedido.jsx');

var Routes  = (
    <Router history={History}>
        <Route path="/" component={Base}>
            <IndexRoute component={HomePage} />
            <Route path="/historial" component={Historial} />
            <Route path="/pedido/nuevo" component={NuevoPedido} />
        </Route>
    </Router>
);

module.exports = Routes;
```

My bundle script is something like this

`watchify src/main.jsx -v -t [ babelify --presets [ react es2015 ] ]  -o public/js/main.js`

This outputs a 1.5mb file which is huge for the little code i have written.

I noticed that EG i remove a component and it's route

```
var NuevoPedido = require('./components/Pages/NuevoPedido.jsx');
<Route path="/pedido/nuevo" component={NuevoPedido} />
```

It cuts down like 500 kb from the 1.5mb file but that component is not 400kb in size...

Dist setting brings it to 700kb which is still huge

`SET NODE_ENV=production & browserify src/main.jsx -v -t [ babelify --presets [ react es2015 ] ] -g [uglifyify] -o public/js/bundle.js`

**Comment by ryanflorence** [comment]
our UMD build is ~12kb minified + gzipped, any browserify usage should be smaller (don't need to bundle all deps) Something is wrong in your app.

**Comment by juliorodriguez48** [comment]
I Just have the same problem. I only have this imports : 
`import {
    Router,
    Route,
    Link,
    DefaultRout,
    IndexRout,
    browserHistory
} from 'react-router';`

And my bundle app has a 1.5mb of size. Too big.  I had change browserify for webpack and the same problem. What can I do ?
