### ISSUE TITLE
Navigating to http://localhost// causes a security exception

### ISSUE THREAD

**Issue by f0rk** [reactjs/react-router#3168]
When react router attempts to load a route beginning with two slashes, you will receive a security exception similar to the following:

Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'http:' cannot be created in a document with origin 'http://localhost'.

This is because react router attempts to push // onto the history, which is interpreted as a scheme-relative URL.

I was expecting a 404 and the corresponding not found route to load.

**Comment by taion** [comment]
Can you file this against mjackson/history? It's not an RR bug per se.

**Comment by f0rk** [comment]
Sure
