### ISSUE TITLE
Aliases names for paths

### ISSUE THREAD

**Issue by DmitryAuine** [reactjs/react-router#3174]
For example i have:
`<Route path="/repos/:userName/:repoName" component={Repo}/>`
and about 100 Links in the app:
`<Link to="/repos/rackt/react-router">React Router</Link></li>`
What i need todo, to change  /repos/ to /repo/?
Yes, i need to change:
`<Route path="/repos/:userName/:repoName" component={Repo}/>`
to:
`<Route path="/repo/:userName/:repoName" component={Repo}/>`
and all 100 Links in the app to:
`<Link to="/repo/rackt/react-router">React Router</Link></li>`

It's realy strange that i don't have ability to change it in one place.
For example it will be cool to use something like:
`<Route path="/$repo/:userName/:repoName" component={Repo}/>`
`<Link to="/$repo/rackt/react-router">React Router</Link></li>`
aliases: {repo: 'repos'}
or
getRoute('alias', {userName: 'user1, repoName: 'repo1' })

**Comment by mxstbr** [comment]
You can have nested routes, which would mean you only have to change the routes in one place:

```HTML
<Route path="/repo">
  <Route path=":userName>
    <Route path=":repoName"></Route>
  </Route>
</Route>
```

**Comment by DmitryAuine** [comment]
Thx

**Comment by DmitryAuine** [comment]
@mxstbr  But what about 100 links? With /repos/:userName/:repoName

**Comment by mxstbr** [comment]
See my above comment

> As far as the links go, every editor I know of has a search and replace function – search for <Link to="repos and replace it with <Link to="repo.

**Comment by DmitryAuine** [comment]
@mxstbr  And you too, it's not a good idea, it's like hardcode :)

**Comment by mxstbr** [comment]
Normally you'd have relative links anyway, so on a page that is `/repos` you'd have a `<Link to="someUser/someRepo">` Why would you hardcode 100s of links to a specific location?

**Comment by DmitryAuine** [comment]
> Normally you'd have relative links anyway, so on a page that is /repos you'd have a <Link to="someUser/someRepo"> Why would you hardcode 100s of links to a specific location?

Normally i can have links anyway and they may be not relative to parent path. You can find aliases everywhere in PHP frameworks, ruby, java, JS client, server side frameworks. It's really good stuff, to implement. It gives greater routing flexibility

**Comment by DmitryAuine** [comment]
@mxstbr 
Ok i found this :)
```
import {getUrlByRouteName} from './path/to/URLUtils';
<Link to={getUrlByRouteName(this.context.router.routes, routeName, routeParams)} />
```
