### ISSUE TITLE
Link is not rerendered when location changes, causing active state to go out of sync.

### ISSUE THREAD

**Issue by romeovs** [reactjs/react-router#3177]
## Version
2.0.0

## Expected Behaviour
`Link` `render()` is called when the location changes.

## Actual Behavior
`Link` `render()` is *not* called when the location changes.

**Comment by romeovs** [comment]
I'm sorry the issue request is so vague. I'm setting up an example as we speak!

**Comment by romeovs** [comment]
Okay,
sorry for the preemptive issue. I figured it out. Apparently, when there's a component anywhere in the tree above the `Link` that has the `PureRenderMixin`, it doesn't re-render.

In hindsight, this is pretty obvious but it took me a while to figure out. Have some semantics considering `context` changed? I guess so because before, I never had this problem. 

I'm using [`pure-render-decorator`](https://github.com/felixgirault/pure-render-decorator) to decorate my classes, I'm guessing they should add a test for `context` as well.

**Comment by taion** [comment]
See https://github.com/reactjs/react-router/issues/470. It's tricky.
