### ISSUE TITLE
API feature: dynamically-built list of links

### ISSUE THREAD

**Issue by debugwand** [reactjs/react-router#3179]
Currently, to build a list of links dynamically based on what is specified in the routes requires something like this:
https://gist.github.com/debugwand/d13ded09fabb2ef2ff4d

This relies on examining `this.props.routes[0].childRoutes`, assuming your routes are nested correctly, which looks like something not supposed to be interrogated.

An API method such as getNestedRoutes()or getRoutes() that returns an array of Router objects would be useful if this part of the object is not supposed to be looked at.  Alternatively a component that produces a collection of links could be useful.

The use-case for me is creating a style-guide that consists of many pages, this could also be useful for the huge app example.

**Comment by taion** [comment]
This doesn't belong in core. Among other things, the semantics aren't clear in the case of async routes anyway. You have to do this yourself; if you find a common use-case, make an addon library.
