### ISSUE TITLE
redirecting to NotFound when a <Route> matches, but there there is no actual content

### ISSUE THREAD

**Issue by Pomax** [reactjs/react-router#3181]
Say I have a component that fetches content from out-of-app, for instance from the wordpress API. I use a routing structure like:
```
<Router>
  <Route path="..." component=... />
  <Route path="..." component=... />
...
  <Route path="..." component=... />
  <Route path=":wpslug" component={require('wp-content-page')/>
<Router>
```
The WP content is completely unknown, so there are no static routes that can be bound. Instead the component does this:
```
  render: function() {
    wpAPI.fetchForID(this.props.params.wpslug)
    .then(function(data) {
      if (data.status === 404) {
        // This should terminate rendering of this component and instead switch to a NotFound instead!
      }
    })
    .error(function() {
      // might be a 404, might not be, let's pretend it can be either.
    });
  }
```
How do I abort the component render attempt and tell react-router to instead reexamine its routes starting after the route that triggered, so that potential NotFound or other catch-all routes can kick in?

**Comment by taion** [comment]
https://github.com/reactjs/react-router/pull/3098
