### ISSUE TITLE
Is it possible to pass props into RouterContext?

### ISSUE THREAD

**Issue by voronianski** [reactjs/react-router#3183]
I'm using this guide - https://github.com/reactjs/react-router/blob/master/docs/guides/ServerRendering.md for upgrade my universal app from v0.13 to v2. However I cannot pass additional props to `RouterContext` component..

```js
// ...
(req, res, next) => {
        title = req.title || title;

        const flux = req.flux;

        ReactRouterMatch({ routes, location: req.url }, renderBaseHTML);
        async function renderBaseHTML (err, redirectLocation, renderProps) {
            if (err) {
                return next(err);
            }
            if (redirectLocation) {
                return res.redirect(302, `${redirectLocation.pathname}${redirectLocation.search}`);
            }

            try {
                await flux.getActions('remoteConfig').requestPropertyFiltersConfig();
                await performRouteHandlerStaticMethod(routes, 'routerWillRun', { flux });

                const element = React.createElement(RouterContext, { flux, ...renderProps });
                const appString = ReactDOMServer.renderToString(element);
                const snapshot = new Buffer(flux.serialize(), 'utf-8').toString('base64');

                res.render('base', { ... });
             // ...
```

**Comment by keyursuchdeo** [comment]
I am facing similar issue. RouterContext is ignoring every prop other than history, location, routes, params, components. Moreover, it seems to overwrite these with their values on client side. What is the right way to pass additional props when using server side rendering?

**Comment by keyursuchdeo** [comment]
Never mind. Found solution at https://github.com/reactjs/react-router/issues/3090

**Comment by koolaidfinesse** [comment]
@voronianski I noticed that the issue is closed but did you figure out how to do it? – there are quite a few ways to do it and it depends on the flux implementation you are using e.g. in Redux you can use the Provider component.

**Comment by voronianski** [comment]
@koolaidfinesse I solved the problem that way - https://github.com/voronianski/universal-react-router-flux-2016/blob/master/src/server/middleware/renderHTML.js#L17

**Comment by koolaidfinesse** [comment]
@voronianski That's the method I used at first but I didn't feel comfortable [with] passing the props to ALL created components, with the `createElement` method it's passing the props not only to the route handling component but ALL the components in the component tree but I guess it doesn't really matter because you're just rendering HTML to a string and on the client you're hydrating the stores and passing the state to the right component anyways. Glad to see that you solved it so quickly it took me a while which is why I try to help anyone with the same issue because there is not a standard way (as yet).

**Comment by ryanflorence** [comment]
createElement is only used for route components

**Comment by koolaidfinesse** [comment]
@ryanflorence I meant that it wasn't only called on the route being handled but all the components in the routes hierarchy e.g. App > Friends: App would have props meant for Friends (not the components inside the route handling components). Not a real problem it's just in the back of my mind lol.

**Comment by sergeylukin** [comment]
So glad I found this. Used solution suggested by @voronianski to make [isomorphic-style-loader](https://github.com/kriasoft/isomorphic-style-loader) (which only has examples with [react-routing](https://www.npmjs.com/package/react-routing)) work with [react-router](https://github.com/reactjs/react-router)'s `<RouterContext />`.

**Comment by taion** [comment]
Added to the troubleshooting guide: https://github.com/reactjs/react-router/blob/master/docs/Troubleshooting.md#passing-additional-values-into-route-components.
