### ISSUE TITLE
Aliases names for paths (reopened?)

### ISSUE THREAD

**Issue by andreigabreanu** [reactjs/react-router#3186]
Related to @3174

There are more reasons why you would want named routes instead of path routes:

1) Easier to write code for : I can remember easier "base.users.edit" rather than "/users/edit/5"
2) Imagine you reference a route with params from a completely differnet location the app, like /some/deep/path wants to Link to /users/edit/5 . And imagine you have tons of these links in that component or you have a lot of components with the Link there. If you change the route path, you have to change everywhere.
3) Imagine you're doing an ACL route based system. You can't compare users/edit/5 with /users/edit/6 in order to tell if the user is allowed on users/edit (w/o parsing the path). You should be able to compare the route name and not route path

Side note: all major routing frameworks in common programming languages (PHP and JS from what I am aware) offer this feature. I don't know why it was dropped from (?) from React Router. And no, "just do a find and replace to to change the paths" is not an answer, *especially* when links are/can be relative. I'd rather have the framework do it and have tests for it than relying on the editor to do it and missing certain places where a part of the path was different.

What I propose is that :

1) Link should have a toName="route name" params{...} query="" props (this is what I've been doing for example so far by enhancing the Link object and it works well)

2) Route should allow the "name" prop and combine it via nesting with the "dot" - . - character. 
Route path="base" => Route path="users" => Route path="edit/:id" would become 
Route name"base" path="base" => Route name"users" path="users" => Route name="edit" path="edit/:id" . We could even autopopulate the name if no name is provided, with the path value and throw a warning if the name contains params (or if you provide name="edit/:param)

**Comment by taion** [comment]
We've discussed this issue at length many times. You're not accomplishing anything here beyond annoying me.

**Comment by andreigabreanu** [comment]
I am sorry if I annoyed you. That was not my intention. 

That being said, you do realize that this *is* a public library and the whole point of these discussions / issues is to propose/discuss about bugs or features of the library, right?. Of course you can just say "nope" and end it but  ... :) Anyway. Be happy!

**Comment by taion** [comment]
Apologies. Anyway, this has come up before, and we've discussed the issues exhaustively. We're not planning on supporting named routes in React Router core – this can be handled as an extension.

**Comment by andreigabreanu** [comment]
No worries :) . Understood, ok.

**Comment by ryanflorence** [comment]
> You're not accomplishing anything here beyond annoying me.

@taion  ... just ... 

https://zillowzollo.files.wordpress.com/2010/04/picard_facepalm.jpg

**Comment by ryanflorence** [comment]
> You're not accomplishing anything here beyond annoying me.

@taion ... I just ... uh ... 

![picard_facepalm](https://cloud.githubusercontent.com/assets/100200/13727038/bf723d16-e896-11e5-9a84-fda5ed8ac8ab.jpg)

**Comment by joshmanders** [comment]
@taion 
> We've discussed this issue at length many times. You're not accomplishing anything here beyond annoying me.

 Wow... I just... So far I've found two `React Community member`'s having this tone towards users asking simple questions... This isn't good.

**Comment by ryanflorence** [comment]
@joshmanders yeah, its completely unacceptable.

**Comment by joshmanders** [comment]
@ryanflorence I don't remember the exact issue, I've been pouring over open and closed issues in this repo for about an hour now trying to find out how I can accomplish named routes and it seems that the concensus from maintainers of this org is "too bad, we don't want it, get over it." which seems to be pretty discouraging considering the responses seem to come from people formulating well crafted concerns.
