### ISSUE TITLE
Snoop for NODE_ENV === 'test' in <Link>

### ISSUE THREAD

**Issue by taion** [reactjs/react-router#3188]
In `<Link>`, we currently support not providing a `router`, in which case we just don't generate an `href`.

This is in fact convenient for testing, but it also leads to potential errors like http://stackoverflow.com/questions/35959965/react-router-link-doesnt-render-href-attribute-with-server-side-rendering/35966923.

We could change `<Link>` to require a `router` unless `NODE_ENV === 'test'`. Thoughts?

**Comment by timdorr** [comment]
I'm usually pretty against test-specific hacks in code. We really should be testing against the expected behavior and avoiding doing things solely for our convenience. Is creating a dummy router with just a createHref on it that hard?

**Comment by taion** [comment]
If it weren't, then we'd be requiring `router` on `<Link>`. I think it's been enough of an issue that it's worth having this carve-out.

**Comment by ryanflorence** [comment]
I'm still pretty happy with how it works right now, that SO question doesn't convince me we've got a problem. There's no reason to use `Link` outside of a `Router`, the moment that app actually starts becoming something real the "problem" will go away.

Also, I've done some user-customizable theming where we display different screens in the app with the new colors live, it was nice ot just render the components w/o needing a bunch of fake routers all over the place (we had like, 9 screens up, all scaled down 25%)
