### ISSUE TITLE
History - Going back not rendering in previous scroll position

### ISSUE THREAD

**Issue by FunnyBoxification** [reactjs/react-router#3189]
Greetings. I'm using react-infinite to implement an infinite list of items. When you click on an item it sends you to another route where the item details are exposed. When going back with goBack via Desktop Chrome and Safari on iPod, it renders the list with the previous scrolling position. 
When trying to go back in an Android device using Chrome, it renders the list setting the scrolling position  to the start. 
Is this a bug?

**Comment by timdorr** [comment]
https://github.com/taion/scroll-behavior
