### ISSUE TITLE
Remove index routes as a separate concept

### ISSUE THREAD

**Issue by taion** [reactjs/react-router#3204]
We don't really need this any more. Given that we already support something like:

```js
<Route path="foo" component={A}>
  <Route component={B}>
    <Route component={C}>
      <IndexRoute component={D} />
    </Route>
  </Route>
</Route>
```

We may as well just get rid of index routes as a concept and just use pathless leaf routes, e.g.:

```js
<Route path="foo" component={A}>
  <Route component={B}>
    <Route component={C}>
      <Route component={D} />
    </Route>
  </Route>
</Route>
```

**Comment by ryanflorence** [comment]
```
<Route path="foo" component={A}>
  <Route component={B}/>
  <Route component={C}/>
</Route>
```

Who wins? You're going to say `B`.

```
<Route path="foo" component={A}>
  <Route component={B}/>
  <Route component={C}>
      <Route component={D}/>
  </Route>
</Route>
```

Who wins? Still `B`. But now our matching function has to traverse the entire route config until it realizes its done and never found a leave node, so it goes back and picks `B`.

It's also super unclear.

`IndexRoute` is a the hint to both the developer looking at your route config and the matching function to stop.

**Comment by taion** [comment]
I'd actually consider `B` the leaf node above there, and stop as soon as we get to `B`, but I agree that this is potentially less clear.

**Comment by ryanflorence** [comment]
```
<Route path="foo" component={A}>
  <Route component={B}/>
  <Route component={C}>
      <Route path="bar" component={D}/>
  </Route>
</Route>
```

How would you know to stop at `B` w/o traversing down to `D`?

**Comment by taion** [comment]
You'd stop at the first branch where no routes have paths, when you get to a route with no children. Once the matching get to `B`, it'd see that `B` satisfies the "path-less branch with no children" condition, and terminate the match there.

We have most of this logic already in https://github.com/reactjs/react-router/blob/master/modules/matchRoutes.js#L30-L57, to handle the case where the `<IndexRoute>` is nested under (potentially many) path-less `<Route>`s.

**Comment by ryanflorence** [comment]
ah gotcha, well, still seems harder to talk about than IndexRoute. IndexRoute is basically the name for this entire conversation.

**Comment by taion** [comment]
That snippet from `matchRoutes` is where this idea comes from, BTW.

Before we added the "index route under pathless route" feature, we could just terminate matching on an exact match, and go directly to the index route.

With the new logic, we might end up iterating through child routes regardless. In other words, we can essentially replace all instances of index routes with just pathless routes, and still have everything just work, without any real increase in code complexity.

So purely from an engineering perspective, the concept of explicit index routes doesn't get us anything, but I am now leaning toward thinking that it's clearer to see an `<IndexRoute>` configuration component or `indexRoute` key as appropriate.
