### ISSUE TITLE
Update exported PropTypes

### ISSUE THREAD

**Issue by taion** [reactjs/react-router#3205]
~~I'm not convinced that we get anything out of exporting `PropTypes`. They're at least documented now, thanks to @lPadier's https://github.com/reactjs/react-router/pull/3203, but I think we ought to consider dropping them.~~

~~With the possible exception of `location`, which is a matter of history rather than here anyway, they're not really applicable to users of this library, and things like `history` are even deprecated.~~

Analogous to how react-intl handles it, we should export `routerShape` as a top-level export. The other exports like `location`, to the extent they are required, should sit in `history`.

**Comment by taurose** [comment]
:+1: In my opinion, importing prop types from other modules seems counter-productive. If a component uses `location.pathname`, for example, the component should be explicit about it (location: shape with pathname: string). By keeping prop types local, the component is more resistant to outside changes, e.g. if the `location` shape changed, the validation would fail, which it wouldn't with imported prop types.

In cases where a component only passes things along to other components, it should be sufficient to define it as an object or "any".

I wonder how common this is among react libraries.

**Comment by taion** [comment]
I've never seen any other React libraries that export propTypes. I've never even heard of anybody using the exported propTypes here until https://github.com/reactjs/react-router/pull/3203.

**Comment by ryanflorence** [comment]
not sure how things made it into that list, but original intention was people to be able to add a `contextTypes: { router: routerPropType }` for their components that need the router.

**Comment by taion** [comment]
That would make sense, but we've already extensively documented `router: React.PropTypes.object`, and I feel like that's adequate; enough that we don't need exported prop types.

**Comment by taion** [comment]
@rickharrison Care to elaborate? :stuck_out_tongue:

**Comment by rickharrison** [comment]
I do use some of them personally. My thought was why take them out if they are already there considering it's so small. But, I guess if you don't want to maintain them I see why you would. I could also easily just include a similar file like that in my own project, but I'd have to duplicate it across our many react-router based apps.

**Comment by timdorr** [comment]
IMHO I think most people are better served by a real typing system, such as TypeScript or Flow. PropTypes' duck typing never seemed that helpful to me, personally.

[Looks like we need to update our PropTypes anyways.](https://github.com/reactjs/react-router/blob/master/modules/PropTypes.js#L12-L13) Given they're out of date, I would say we get rid of them.

**Comment by taion** [comment]
Right, IMO the main thing is that they've just gotten quite out-of-date.

Plus the types for things like locations are owned by history anyway.

**Comment by ryanflorence** [comment]
PropTypes are super valuable, but I'm not sure we need to export any of them except router

**Comment by taion** [comment]
We're not currently exporting a `router` prop type, though.

**Comment by taion** [comment]
I just found a counter-example. react-intl exports a shape. As I'm currently using react-intl, I am selfishly declaring for the sake of consistency that we should do the same in React Router.

I'm now in favor of continuing to export prop types, though perhaps with a slightly different API.

**Comment by taion** [comment]
Updated OP with my current thinking here.
