### ISSUE TITLE
eslint-config-reakt dependency no longer exists?

### ISSUE THREAD

**Issue by mikegreiling** [reactjs/react-router#3209]
## Version
2.0.1

## Issue Description
https://github.com/reactjs/react-router/blob/master/package.json#L51

This appears to point to the following repository which appears to no longer exist:
https://github.com/rackt/eslint-config-rackt

If this has been moved or renamed somewhere I have not been able to find it.

**Comment by mxstbr** [comment]
https://github.com/reactjs/redux/issues/1509#issuecomment-195090996
