### ISSUE TITLE
Upgrade to history v3

### ISSUE THREAD

**Issue by zdila** [reactjs/react-router#3211]
Please add support of history ver. 3.0.0+

**Comment by timdorr** [comment]
Version 3 hasn't even shipped yet.

**Comment by taion** [comment]
Probably not before 3.x here, BTW – there are a few semantic changes such that it'd be awkward to shim in compatibility for v3 histories, and we can't change the contract of the history objects that we re-export.

**Comment by vdh** [comment]
[history v3.0.0 is out now](https://github.com/mjackson/history/blob/master/CHANGES.md#v300). Should this issue be re-opened, or should a new issue or PR get made?

**Comment by timdorr** [comment]
If you (or anyone else) wants to submit a PR, that would be great. But keep in mind that we'll need deprecations for any API changes, which might be fairly extensive with code outside of this library's direct control.

**Comment by holms** [comment]
Well.. so how to use history 3.0 in the project? It says `You have provided a history object created with history v2.x or earlier. This version of React Router is only compatible with v3 history objects. Please upgrade to history v3.x.`
