### ISSUE TITLE
How to include in a requirejs based application.

### ISSUE THREAD

**Issue by Pfeifenjoy** [reactjs/react-router#3216]
I wonder which file I must include to run the react-router.
I have installed react-router via bower and are trying to require it in requirejs now.
Do you plan on building a compiled version of the react-router, because it is weired to compile the react-router myself?

Thanks,
Pfeifenjoy

**Comment by timdorr** [comment]
https://github.com/reactjs/react-router#installation

**Comment by Pfeifenjoy** [comment]
I still have the same problem. I could ether include react-router via npm, webpack or the cdn, but I cannot include it via bower and requirejs, because it is not compiled to es5.

**Comment by timdorr** [comment]
The UMD build is es5: https://npmcdn.com/react-router@2.0.1/umd/ReactRouter.js

**Comment by Pfeifenjoy** [comment]
I tried to include this module, but I always get an error:

TypeError: Cannot read property 'PropTypes' of undefined(…)

**Comment by Pfeifenjoy** [comment]
Also I cannot require Route:

import {Router, Route} from "react-router";

console.log(Router); //=>undefined

**Comment by taion** [comment]
Please use one of the suggested support forums if you need help. The issue tracker is not an appropriate forum for asking for help.
