### ISSUE TITLE
Documentation for "Confirming Navigation" is lacking

### ISSUE THREAD

**Issue by globexdesigns** [reactjs/react-router#3228]
I'm finding the documentation for "Confirmation Navigation" to be lacking. I'm migrating my code from 1.0 to 2.0 and having a lot of issues with this particular feature.

The page here: https://github.com/reactjs/react-router/blob/master/docs/guides/ConfirmingNavigation.md
mentions two things:

- `this.props.route`: What is this? Where do I get it? How do I pass it to my component?
- `this.context.router.setRouteLeaveHook`: What is this function? Why is it not in the API documentation or the Glossary documentation?

The error I'm running into it is `TypeError: Cannot read property '__id__' of undefined` which is caused by the fact that `this.props.route` is undefined. But I'm not sure what I'm supposed to be passing there to the `setRouteLeaveHook` function.

**Comment by taion** [comment]
Rolls up to https://github.com/reactjs/react-router/issues/2933, plus most of this is actually covered in the docs already.

**Comment by ddeath** [comment]
@EvNaverniouk Hi were you able to identify what went wrong? I do not see anything about it in docs

**Comment by EvNaverniouk** [comment]
@ddeath Yes. Here's how you get it to work. On any component that you want to prevent the unmounting of, add:

```
class YourComponent extends Component {
	// Ensure the 'router' context is specified on this component
	static contextTypes = {
		router: PropTypes.object.isRequired
	};

	componentDidMount () {
		// Add a new function to control the unmount blocking
		this._unblock = this.context.router.history.block(() => {
			return "You shall not leave";
		});
	}

	componentWillUnmount () {
		// When the component unmounts, call the function
		this._unblock();
	}
}
```
