### ISSUE TITLE
Simplify <Link> active semantics

### ISSUE THREAD

**Issue by taion** [reactjs/react-router#3231]
Prerequisites: https://github.com/reactjs/react-router/pull/3158, https://github.com/reactjs/react-router/issues/3172

Once we merge https://github.com/reactjs/react-router/pull/3158, we'll be able to dramatically simplify the active checking for index-only links – that check will just be a comparison of the link to the path name, with a special case for handling trailing slashes (as the pathname will be canonical outside of the trailing slash).

For consistency, we should consider also updating the semantics on non-index links to just do a prefix check, once we also resolve https://github.com/reactjs/react-router/issues/3172. Given issues like https://github.com/reactjs/react-router/issues/3230 (and many related ones), users seem to be confused with the current behavior of path active status calculation. Also, this will dramatically improve https://github.com/reactjs/react-router/issues/1873, as it will let us avoid running a full route match just to determine if a link path is active.

**Comment by taion** [comment]
(but contra what I said in https://github.com/reactjs/react-router/issues/1873#issuecomment-193444998, in the interest of not making breaking changes without extremely good cause, we should not make `onlyActiveOnIndex` be the default)

**Comment by timdorr** [comment]
@taion Did you want to tackle the #3158-related issue? I just merged that in.

**Comment by taion** [comment]
I want to hold off until we get a release cut. I really don't like having a huge stack of unreleased changes sitting on master.

**Comment by taion** [comment]
More people who are confused by the current behavior:
- https://github.com/reactjs/react-router/issues/3237

**Comment by taion** [comment]
I chatted with @ryanflorence on this. I'm convinced now that the current semantics for route active status are better, because they're more powerful than prefix checking. I'll re-open #3277 and separately just optimize index link handling for now.
