### ISSUE TITLE
Active Paths containing optional params don't activate related links

### ISSUE THREAD

**Issue by outdooricon** [reactjs/react-router#3233]
Given a route containing an optional piece (`path="/test(/:case)"`), when you are sitting on a route matching the optional part (url is `/test/case1`), then a Link for the required base url (`to="/test"`) doesn't receive it's activeClass. This is important for me since the `/test` Link is in navigation and my component for handling `/test` as well as any `/test/case` is the same. I need the `/test` Link to stay active when when viewing any of the cases, since that is the section you're viewing.

## Version
2.0.0

## Test Case
http://jsbin.com/canuruhavo/edit?html,css,js,output

## Steps to reproduce
- Click on "test link"

## Expected Behavior
- The link "this test link should be active" should have active class and be red.

## Actual Behavior
- The link "this test link should be active" doesn't receive the active class

**Comment by taion** [comment]
This is working as intended. All params, including optional ones, have to match. You'd have to actually set up a parent route for things to work as you describe.

We're considering changing this – see https://github.com/reactjs/react-router/issues/3231.

**Comment by outdooricon** [comment]
Ok thanks @taion! Thought I'd report it in case it was one of those missed edge cases. I'll just continue with my nested routes instead, as you suggested. :+1:
