### ISSUE TITLE
Confirming navigation async 

### ISSUE THREAD

**Issue by tnrich** [reactjs/react-router#3234]
Hey there,

It seems like the history module used by react-router allows for "async confirmation" via a callback function: https://github.com/mjackson/history/blob/master/docs/ConfirmingNavigation.md

As far as I can tell this same ability has not made it into react-router (https://github.com/reactjs/react-router/blob/e279507262a4337c0f3410f3a1a7f26852cfe430/docs/guides/ConfirmingNavigation.md): 

```
this.context.router.setRouteLeaveHook(this.props.route, 
      (nextLocation, callback) => {
        console.log(callback);
        //logs undefined
```

I'd like to request the ability to confirm/deny navigation changes asynchronously. 

I did find this hacky hack: http://stackoverflow.com/questions/35275344/how-to-use-a-custom-component-with-react-router-route-transitions/35793421#comment60252624_35793421

which is kind of nice, but unfortunately doesn't work in all cases (see the comment by @majorBummer (that's me!)) 

Is there any reason why we couldn't have the "standard" async confirmation callback with react router as well?

Thanks so much,
Thomas

**Comment by taion** [comment]
It's because the "before unload" support requires a synchronous hook.

**Comment by appsforartists** [comment]
Odd timing - I just came on here to ask the same thing.

**Comment by taion** [comment]
We're not planning on supporting this. The async support in `listenBefore` isn't intended for use in blocking users from leaving routes because of data on the route.

If you want fine-grained control on how users interact with link-like components, you should put that logic in those link-like components.

**Comment by appsforartists** [comment]
I was going to use it to wait for a transition, using ReactMotion.onRest to call the callback to let the route change continue.

**Comment by taion** [comment]
We have some examples for animations – the pattern there is generally better for this sort of thing.
