### ISSUE TITLE
Using Custom Histories - Typescript throws type error

### ISSUE THREAD

**Issue by GeekOnGadgets** [reactjs/react-router#3243]
## Version
2.0.0

**Problem**
Was using Custom Histories in order to make URL Pretty and typescript is throwing a type check error from the History module. 

const appHistory = useRouterHistory(createHashHistory)({ queryKey: false });
**Error** 
Argument of type '{ queryKey: boolean; }' is not assignable to parameter of type 'HistoryOptions'.
Object literal may only specify known properties, and 'queryKey' does not exist in type 'HistoryOptions'.

**Question**
After looking at the type file interface HistoryOptions is expecting a function - not sure why ?
`interface HistoryOptions {
	getUserConfirmation?(message: string, callback: (boolean) => void): void;
}`
is this type file wrong ?

**Solution**
Not sure this is the right way to address the problem, 
const appHistory = useRouterHistory(createHashHistory)(() => { return { queryKey: false } });

Thanks to @edwin-nz for helping with this problem.

Can someone else please put more light on this issue? 

Thanks

**Comment by taion** [comment]
We do not maintain the TypeScript definitions for React Router or for history.

**Comment by GeekOnGadgets** [comment]
sorry, created a issue for appropriate author. Hope this helps someone. 

Thanks

**Comment by glcheetham** [comment]
Can you post a link to the other issue here?
