### ISSUE TITLE
Testing guide is severely lacking

### ISSUE THREAD

**Issue by dadamssg** [reactjs/react-router#3249]
I'm new to react, react-router, etc and was trying to get a handle on how to test an app using react-router. The [testing guide](https://github.com/reactjs/react-router/blob/master/docs/guides/testing.md) has zero relevance to react-router. The code example only makes use of Links and the suite doesn't even test them. It does not show how to test navigating through an app at all.

Are there test utilities to determine the current route? What's the best way to test a route change? 

For someone looking to copy/paste an example in their app just to get it working to digest, I'd suggest removing `react-bootstrap` from the example. There's a bug in the example with the text of the button. The component has "Your account" while the test is testing for "Your Account". I would also mention in the guide that because of the static syntax the `babel-plugin-transform-class-properties` plugin is required and should be added to `.babelrc`. 

I wasted too much time trying to get the example working only to realize that it tests literally nothing related to `react-router`.

**Comment by timdorr** [comment]
See #2933.
