### ISSUE TITLE
Normal-sized app example

### ISSUE THREAD

**Issue by AndrewIngram** [reactjs/react-router#3259]
Based on #3232, it seems that the huge-apps example demonstrates a pattern that won't actually be needed by most apps, and actually has a negative performance impact if applied naively.

It seems to me that this example isn't helpful right now, because it demonstrates a pattern most users will never need and probably shouldn't use. Anecdotally, I was certainly under the impression that this was *the* way to do code-splitting, and would have implemented things in this suboptimal way if @taion hadn't pointed out the issue to me.

I think we need a normal/medium-sized app example that demonstrates the pattern of code-splitting suggested in #3232, and this should be promoted as the encouraged way to implemented code-splitting for most users.

**Comment by timdorr** [comment]
`huge-apps` does take things a bit to the extreme, but I don't think it's a bad example. You can take  pieces from it as it makes sense for your app. 

That being said, a more straightforward example would be a good addition. If you want to start a PR, we can work on building out something high quality for others to follow.

**Comment by taion** [comment]
It's not just "to an extreme" – it's actually incorrect. You almost certainly do not want to use both `getChildRoutes` and `getComponents` in the way that the example in question does – you end up with waterfalled round trips to the server for no good reason, compromising end-user experience.

That flaw in the huge-apps example was why I opened #3232 in the first place; that the API encourages users to do this and that we demonstrate it in an example is really bad.

**Comment by taion** [comment]
We don't actually have a meaningfully better pattern available other than the huge-apps one. Will need to resolve #3232 first.
