### ISSUE TITLE
Optional parameter for "populating" the link content

### ISSUE THREAD

**Issue by quasipedia** [reactjs/react-router#3260]
I'd like to propose an extension of the current `Link` API: a `content` optional parameter that would allow to inline the content of the rendered link.  For example:

```jsx
<Link to={this.props.homeUrl} content='Go to HomePage'>
```

should render to:

```html
<a href="/home">Go to HomePage</a>
```
The rationale is that having a text (or other stuff) for a link is the most common scenario, and this way one can avoid a level of complexity (and possibly one rendering cycle).

**Comment by timdorr** [comment]
This is the exact same thing as `props.children`. [We pass those to an `a` element](https://github.com/reactjs/react-router/blob/master/modules/Link.js#L130). You can do this today:
```js
<Link to={this.props.homeUrl} children='Go to HomePage'>
```

**Comment by quasipedia** [comment]
:+1:  Thank you.
