### ISSUE TITLE
React v15.0 no longer support React.__spread

### ISSUE THREAD

**Issue by carlsagan21** [reactjs/react-router#3263]
#happens 
index.js:83 Uncaught TypeError: React.__spread is not a function

I guess it's because of React version up.
There was a major version up to v15.0. plz check.
https://facebook.github.io/react/blog/

**Comment by ev1stensberg** [comment]
Could we get a snippet of your code through a gist or a github repo? Would be lot easier for us to figure it out if we got a complete understanding of what went wrong.

**Comment by ev1stensberg** [comment]
Also, if you need to use spread syntax now, while we check this out,  try invoking it through something like: ` React.createElement(RouteHandler, Object.assign({}, this.state)).`

**Comment by carlsagan21** [comment]
Oh... Sorry, but I think I found that it was my fault.
Sorry about this issue. Have a nice weekend.

**Comment by mikeemoo** [comment]
Hi guys,

The 'server rendering' example on your github wiki has this line:

res.status(200).send(renderToString(<RouterContext {...renderProps} />))

... which I believe is the problem
