### ISSUE TITLE
Support React v15.- react-router Link cause page reload

### ISSUE THREAD

**Issue by singggum3b** [reactjs/react-router#3264]
Generally it's a request to support React v 15.

When pre rendered on server, the Link element cause page refresh on click, while it's work normally when only rendered on client side

**Comment by singggum3b** [comment]
I just realized with v15 dom reconciliation all click event doesn't retain O0O. suppose to post this in react repository :|

**Comment by ev1stensberg** [comment]
Could you reference this by an example, or rephrase? In general, I can tell you that when you click a URI, the server needs to know about it and have something to fetch back. From what I can tell, you're referencing to browserHistory, which should have the same functionality in v15 as in previous versions of React.

Server side rendering takes care of each request it gets, and it doesn't pre-render anything before you tell it to. So if you click on a link, it will render the page when you click it, not when you load the initial page.

***
 Here's a nice read: [Redux Docs](http://redux.js.org/docs/recipes/ServerRendering.html)

If you could specify this question with a concrete example, that would be great :smile:

**Comment by singggum3b** [comment]
I've set up isomorphic rendering app , which work great with v0.14
[https://facebook.github.io/react/docs/top-level-api.html#reactdomserver](url)
But with react v0.15 its seem all event listener is missing after reconciliation on client side.

**Comment by singggum3b** [comment]
I'm suppose this doesn't caused by react-router, though you could check any way.

**Comment by singggum3b** [comment]
After further investigation , it's seem the [match] function doesn't excute on client side caused the issue

**Comment by singggum3b** [comment]
Ah , never mind this, just check out the cause because of async route doesn't resolve which cause match not finish, but even so , no message is thrown , so one has no way to know what went wrong.

**Comment by FuzzySockets** [comment]
I'm having this issue...

**Comment by ev1stensberg** [comment]
@FuzzySockets server side is async, which means if you call something sync it would't apply. What's the issue?

**Comment by FuzzySockets** [comment]
@ev1stensberg I'm a dummy. I hadn't imported Link for that component.  To my credit though, no errors were thrown during compilation or at runtime.

**Comment by ev1stensberg** [comment]
A link is only connected with Route through a transition manager I believe, that's why it doesn't warn you, you can chose not to use Link and make it custom through it's prop-types.

**Comment by dedxex** [comment]
I am also having this issue. 
the link is routing to correct URL but the page is reloading and then being routed, which is not expected behaviour
