### ISSUE TITLE
Props not Propagated

### ISSUE THREAD

**Issue by marr** [reactjs/react-router#3268]
Hi, 
I am trying to use a `name` property on my route, so I can dynamically assign an id in the wrapper component. Is this something that is supported? For example:

modifying some routes in the active-links example.. 
```
 render() {
    console.log(this.props.route.name)
    return (
...
<IndexRoute component={Index} name="home" />
<Route path="/about" component={About} name="about" />
...
```
I never see the name output in the console though, only `undefined`. 

I supposed this is unsupported and should be handled by using the output desired in each route's component but I thought i'd raise it here just in case it was expected to work..

Thanks,
Dave

**Comment by perrin4869** [comment]
See #3090 for a solution

**Comment by timdorr** [comment]
The Route React Element that is created doesn't have arbitrary object properties like that. The extra props are discarded when we create the element. You can override createElement if you really need them, but you will likely be better off creating dedicated route components that only deal with setting up things for that route and nothing else. If they need something external, you can pass it via context.
