### ISSUE TITLE
Routes with GET query string parameters

### ISSUE THREAD

**Issue by bmamouri** [reactjs/react-router#3271]
I would not ask this question here if I did not spend a few hours to find the answer.

I want to have a route with GET query string parameters but I cannot make it work. Is it even supported by `react-router`. This is the route that I want to have. The question mark is a special character in react-router, do I need to escape the question mark? How?

```
        <Route component={ResultsPage} path="/search?keyword:keyword&type:image" />
```

**Comment by mxstbr** [comment]
Instead of hard-coding them in your route (which afaik doesn't work), check `this.props.location.query` in your `/search` component and show the `ResultsPage` if a query exists!
