### ISSUE TITLE
app.get('*') with other get request

### ISSUE THREAD

**Issue by EasonWang01** [reactjs/react-router#3272]
hi,I’m new to this,

If I set below for broswerHistory,how can I set other app.get request?
```
app.get('*', function (req, res) {
    res.sendFile(path.resolve('client/index.html'));


});

app.get('/ajax', function (req, res) {
    console.log(req);//This will not work
    res.end();

});
```

thanks for reply

**Comment by mxstbr** [comment]
This has nothing to do with react-router, but with your node.js server framework of choice.

The issue is that you have to switch them around:

```
app.get('/ajax', function (req, res) { });
app.get('*', function (req, res) { });
```

Then it should work!

**Comment by EasonWang01** [comment]
thanks!
