### ISSUE TITLE
replace does not work work inside async function

### ISSUE THREAD

**Issue by littlee** [reactjs/react-router#3273]
I am following this example code to implement my own auth-flow
https://github.com/reactjs/react-router/blob/master/examples/auth-flow/app.js#L120-L127

because my authentication strategy is session based, so I make it async:
```
var request = require('superagent');
function requireAuth(nextState, replace) {
	request
		.get('/user/isUserLoggedIn')
		.end(function(err, res) {
			alert(res.body.loggedIn); // false
			if (!res.body.loggedIn) {
				replace({
					pathname: '/login',
					state: {
						nextPathname: nextState.location.pathname
					}
				})
			}
		})
}
```
it did alert, but it never redirect to `/login`, even if I make `/user/isLoggedIn` directly return 
```
{loggedIn: false}
```

**Comment by natelaws** [comment]
Add a 'callback' argument to requireAuth and call that function after your call replace.

See https://github.com/reactjs/react-router/blob/master/docs/API.md#onenternextstate-replace-callback

**Comment by timdorr** [comment]
@natelaws Thanks!

**Comment by kadikraman** [comment]
For anyone wandering here in the future: I had a similar problem - fixed it by using `browserHistory` from `react-router` instead

```js
import { browserHistory } from 'react-router';

const validateRole = role => async () => {
 // some async data fetching

  if (!<has role>) {
    browserHistory.push('/404');
  }
};
```
