### ISSUE TITLE
Preserve react-router scroll behaviour on a scrollable div

### ISSUE THREAD

**Issue by IljaDaderko** [reactjs/react-router#3275]
I am working on a project that has several pages where most content is located inside scrollable center div. I believe due to this I'm not noticing any sort of scroll state preservations, nor can I take advantage of options like [ignoreScrollBehavior](https://github.com/reactjs/react-router/pull/388#issue-45558217)

Hence I wanted to ask if there is some way to specify that div (for certain routes) as one that should be tracked for scroll?

**Comment by timdorr** [comment]
You can most likely adapt some of the techniques provided by [`scroll-behavior`](https://github.com/taion/scroll-behavior). Keep in mind @taion has said that library needs a bit of a rewrite, so the code might not have the best internals at the moment. But you can get some of the basic gist of it that way.
