### ISSUE TITLE
Documentation error about child lifecycle?

### ISSUE THREAD

**Issue by slestang** [reactjs/react-router#3276]
## Version
2.0.0

## Issue
The documentation page about [lifecycle](https://github.com/reactjs/react-router/blob/master/docs/guides/ComponentLifecycle.md) state that *componentDidMount* of children is called after the one from parent.
I observe the contrary in my app. To be sure I didn't do anything wrong/weird in my app, I modify an example of [react-router-tutorial](https://github.com/reactjs/react-router-tutorial/) to have a nested route and I observe the same behavior.

Those observations are coherent with [this page](https://facebook.github.io/react/docs/component-specs.html#mounting-componentdidmount) of the React documentation that state:
```
The componentDidMount() method of child components is invoked before that of parent components.
```
Should I make a PR to correct the documentation?

**Comment by timdorr** [comment]
I think you're inferring too much from the ordering of those tables. They're kept that way to make correlation with the routes above easier for the reader. It's not meant to imply execution order.

**Comment by taion** [comment]
We probably should add ordering hints to make it more clear. One sec.

**Comment by taion** [comment]
#3278

**Comment by slestang** [comment]
Than @taion for the clarification.
