### ISSUE TITLE
First server-side render can't find route '/'

### ISSUE THREAD

**Issue by FuzzySockets** [reactjs/react-router#3282]
When restarting my server and navigating to localhost/, the server returns:

browser.js:49Warning: [react-router] `Router` no longer defaults the history prop to hash history. Please use the `hashHistory` singleton instead. http://tiny.cc/router-defaulthistory

browser.js:49Warning: [react-router] Location "/" did not match any routes

It also adds a hash to the url: /#/?_k=jxm46d

Refreshing the page, or opening in a new tab works as expected the second time around.  I followed the docs related to using history with isomorphic rendering, but they were not very clear or complete.  I think the issue has something to do with how history is configured on the client side. Here's my client-side config, which I took from https://github.com/reactjs/react-router/blob/master/docs/guides/ServerRendering.md

`import {Router, match, browserHistory } from 'react-router';`
```
match({ history: browserHistory, routes }, (error, redirectLocation, renderProps) => {
  render((
    <Provider store={store}>
        <Router {...renderProps}/>
    </Provider> 
  ), document.getElementById('app'))
});
```

Here's my server configuration:

`import { RouterContext, createMemoryHistory, match } from 'react-router';`

then in my server route:

```
let location = request.getPath();
let history = createMemoryHistory(location);

match({ routes, location, history}, (err, redirect, renderProps) => {
  ...
});
```

**Comment by FuzzySockets** [comment]
Ok, I think I figured out this issue.  Changed back to providing browserHistory directly to the router without using match() on the client side.  Now I have some server/client syncing issues to take care of.  My only question now is what are the async routes they speak of in https://github.com/reactjs/react-router/blob/master/docs/guides/ServerRendering.md so I know what to look out for?

**Comment by timdorr** [comment]
Async routes are any route that is loaded asynchronously, of course!

But seriously, it's generally any route that uses `getComponent(s)` or `getChildRoutes`.
