### ISSUE TITLE
Undocumented or incorrect `setRouteLeaveHook` behavior

### ISSUE THREAD

**Issue by joevp** [reactjs/react-router#3287]
We should be able to confirm navigation when the tab is refreshed/closed or when the user navigates to a url outside the router (as detailed in @mjackson's [documentation on the beforeunload event](https://github.com/mjackson/history/blob/master/docs/ConfirmingNavigation.md)). Using the current `setRouteLeaveHook` setup described in react-router's docs I'm only able to add a confirmation message when the user navigates to a new route defined within the router. Am I missing a step here or is the functionality for page unload confirmation messages not included in react router? It seems like the default behavior should cover all of these cases, unless someone can think of an instance where that's not true?

**Comment by timdorr** [comment]
Check the end of that document you linked. You have to add the `useBeforeUnload` enhancer.

**Comment by joevp** [comment]
To me it feels weird having to redeclare history as a dependency for my own app just to get this working. Regardless, after I enhance `createHistory` with both `useBeforeUnload` and `useRouterHistory` the behavior still isn't as expected. You get a single confirmation for route changes within the router (expected) and two confirmations for page unloads (should only display one as described in docs I linked).

**Comment by Pines-Cheng** [comment]
Am I the only one think the document about the `setRouteLeaveHook` is too short?

**Comment by Pines-Cheng** [comment]
How to use `setRouteLeaveHook ` in ES6?
