### ISSUE TITLE
Unable to set basename when using UDM version of react-router.

### ISSUE THREAD

**Issue by Rio517** [reactjs/react-router#3292]
## Version
2.1.1

## Test Case
Source: https://github.com/Rio517/react-router-bug 
Live example: http://rio517.github.io/react-router-bug/  //nothing renders as JS error is thrown.

## Steps to reproduce
Attempt to use UDM version of `react-router` while attempting to use basename.  

Using: https://npmcdn.com/react-router/umd/ReactRouter.min.js

```js
const browserHistory = useRouterHistory(createHistory)({
  basename: '/react-router-bug/' 
});
```

## Expected Behavior
Expect routing to work 

## Actual Behavior
react-router throws this error:
`ReactRouter.min.js:1 Uncaught TypeError: e is not a function` - you can see it in console at the attached live example above.

Disclaimer: I'm a react newb.

**Comment by timdorr** [comment]
I'd use the non-minified versions during development so you can figure out what the error is: https://npmcdn.com/react-router@2.1.1/umd/ReactRouter.js

Offhand, I can't diagnose this because I have no idea what 'e' is.

**Comment by Rio517** [comment]
Oh neat. I didn't realize I could pull that from npmcdn so easily.  

I also didn't realize history was in a separate package.  I just needed to include the UDM version and was all set.  Thanks!
