### ISSUE TITLE
PR Merge Policy

### ISSUE THREAD

**Issue by ryanflorence** [reactjs/react-router#3294]
If you look at the git log, there isn't much community contribution to the actual code, docs and stuff, yeah, but not the code. I think it's because:

1. We don't have a clear roadmap (as discussed in #3289)
2. We don't have a PR merge policy.

Right now it's basically "everybody wait for @mjackson to be okay with this."  Except when I'm on a "we need to ship the next version now!" and just push straight to master.

I propose instead we just need two collaborators to +1 the change, if a collaborator is the one making the pull request, that counts as 1.

That also means any non-trivial change (API additions, changes, deprecations) needs to go through a PR.

**Comment by jquense** [comment]
:+1:  @mtscout6 set up a similar policy with react-bootstrap and its worked out great for us, its been a good combo of process to slow down potentially short sighted choices, while at the same time not too onerous that stuff stays stuck for a long time.

**Comment by mjackson** [comment]
I almost opened an issue like this yesterday. Sounds great. I'm +1

**Comment by mxstbr** [comment]
:+1: we've been using it over at https://github.com/postcss/postcss.org and it's been working very well for us. Definitely recommended.

**Comment by mtscout6** [comment]
You may find this useful: https://lgtm.co/

**Comment by ryanflorence** [comment]
I thought we already had this policy.

**Comment by taion** [comment]
Would somebody care to start by reviewing https://github.com/reactjs/react-router/pull/3295, https://github.com/reactjs/react-router/pull/3296, and https://github.com/reactjs/react-router/pull/3298? 😈
