### ISSUE TITLE
Switching path using `browserHistory` re-creates all the components (not just re-render)

### ISSUE THREAD

**Issue by firasdib** [reactjs/react-router#3297]
Hello,

I am using react-router version 2.0.1 and have a few routes setup, like this:

```js
    <Router history={history}>
      <Route component={App}>
        <Route path="/" component={Foo}>
          <Route path="bar/:id" component={Bar} />
        </Route>
     </Route>
    </Router>
```

So the idea is to render the `Bar` component whenever the user hits `/bar/1` for example. This works fine. However, at some point I need to contact my server to do some stuff and in return I get a new id, maybe 2. The users URL in the browser should then switch to `/bar/2` which I do using the following:

```js
import { browserHistory } from 'react-router';

browserHistory.push('/bar/' + newId);
```

Which also works, the URL changes and everything, but the components (`Foo` and `Bar`) both completely re-render from scratch - they are recreated and remounted! I checked this by doing a `console.log` in the `componentDidMount`. This feels weird, as I would at most expect the components to re-render and not be completely recreated.

Reading the docs regarding lifecycle (https://github.com/reactjs/react-router/blob/master/docs/guides/ComponentLifecycle.md) seem to imply that the component should just re-render.

Am I doing something wrong? Is there another way I should be going about this? Or is this a bug?

Thanks!

**Comment by taion** [comment]
That's not the expected behavior, and it's not what we see in the examples.

Do you have a repro case handy?

**Comment by firasdib** [comment]
@taion You're right, I believe this might be an issue with `react-router-redux` which is what I use to keep the state up 2 date with the router.

**Comment by firasdib** [comment]
For anyone finding this in the future: it was me being an idiot.

**Comment by chaintng** [comment]
@firasdib what do you mean ?
I also now experiencing this issue. The component did remount, instead of just rerender.

**Comment by waneka** [comment]
@firasdib @chaintng i am experiencing this now. can either of you shed some light on a possible cause?
