### ISSUE TITLE
Scrolling to the top of the same page when link is clicked when using a promise library

### ISSUE THREAD

**Issue by mmahalwy** [reactjs/react-router#3300]
From: https://github.com/erikras/react-redux-universal-hot-example/issues/1053

Using `redux-async-connect` which has become popular due to this boilerplate: https://github.com/erikras/react-redux-universal-hot-example. It's used to resolve all promises before route transition.

Seems like what is happening is when a user clicks on a link, the url is rewritten to the new link but @asyncConnect prevents rendering until all promises are resolved. Naturally, when you click on a new link the browser would scroll to the top (since using scroll-behavior), but it's really weird when it scrolls to the top, url rewritten but the rendering of the next page has not come in yet. This might be a problem with asyncConnect re: @sars but I believe it's a problem with react-router/scroll-behavior in not waiting for the component to render on the page before scrolling to the top.

Thoughts/

**Comment by taion** [comment]
This is the same problem that @AndrewIngram reported in https://github.com/taion/scroll-behavior/issues/21. I have an idea for how to address this, but haven't had time to explore the ramifications yet. Let's track this on this issue in scroll-behavior.

**Comment by mmahalwy** [comment]
awesome thanks @taion
