### ISSUE TITLE
Regression: 2.2.0 breaks for server side rendering with code working in 2.0.0 & 2.1.1

### ISSUE THREAD

**Issue by MoOx** [reactjs/react-router#3307]
It's sort of the same issue I mentioned in #3279 but with ReactRouter.match({ routes: routes, location: "/", basename: "/" }` that didn't work anymore (since 2.2.0, same with 2.2.1).

code with 2.0.0 (works with 2.1.1 too) http://jsbin.com/saziwop/edit?html,js,console
code with 2.2.0 http://jsbin.com/zivopi/edit?html,js,console

```js
const App = React.createClass({
  render() {
    return (
      <div />
    )
  }
})

var routes = (
  <ReactRouter.Router>
    <ReactRouter.Route path="*" component={App}/>
  </ReactRouter.Router>
)

ReactRouter.match({ routes: routes, location: "/", basename: "/" }, (error, redirectLocation, renderProps) => {
  if (renderProps) {
    console.log("ok")
  }
  else {
    console.log("NOK")
  }
})
```

Previously my issue wwas with "/test-url" but now same issue with "/" (and basename to "/")

**Comment by taion** [comment]
I'm taking a look. As a temporary workaround, can you remove the trailing slash from your basename?

**Comment by MoOx** [comment]
This code is shipped with [phenomic](http://phenomic.io/) so it's not an easy task atm :) As a workaround I told user to stick to 2.1.1 https://github.com/MoOx/phenomic/issues/393

**Comment by MoOx** [comment]
Maybe this commit introduced that regression https://github.com/reactjs/react-router/commit/ac0b76115c1cc011df34b52d03a9a27636106ca2

**Comment by taion** [comment]
I see – this is actually exposing a different issue than the original one. I coincidentally had a fix under https://github.com/reactjs/react-router/pull/3246, but I didn't cherry-pick it out.

**Comment by taion** [comment]
BTW, I'm not sure if there was some confusion, but you shouldn't be rooting your routes with a `<Router>`. In the case you have, the minimal config would just be e.g.

```js
<Route path="*">
```

which wouldn't trigger this regression.

**Comment by taion** [comment]
Is your actual route config:

```js
<Route>
  <Route path="*" />
</Route>
```

?

**Comment by MoOx** [comment]
Yeah. This

```
<Route component={ LayoutContainer }>
    <Route path="*" component={ PageContainer } />
</Route>
```

https://github.com/MoOx/phenomic/blob/0e67119ba0c86e195183d3877e60d5ae6ddc472a/boilerplate/web_modules/app/routes.js#L27-L31

**Comment by MoOx** [comment]
(In a very near futur, we are going to add more routes, but the first level is to have a common wrapper for all routes. Is there a better solution ?

**Comment by taion** [comment]
This will be fixed by #3308.

I believe this is an edge case triggered by the path being `/`, when using a route with `path="*"` nested under a pathless route.

We had a number of test cases for route matching in our test suite, but this specific case wasn't covered. I'm adding a regression test here with #3308 to keep this from happening again.

**Comment by taion** [comment]
Rather, this only happens when `/` gets matched by a `<Route path="*">`, nested under a pathless route. If you had some other route in front of the `<Route path="*">` that would match the `/`, then this also wouldn't happen.

**Comment by MoOx** [comment]
Ok good to hear. Thanks for your work.

**Comment by taion** [comment]
Sorry this is causing problems. We're tweaking the route matching to be stricter with slashes, to avoid a bug where a route like

```js
<Route path="foo">
  <Route path="bar" />
</Route>
```

would match a URL like `/foo/////////bar/////`. The intention of the fix is to make that path config only match `/foo/bar` and `/foo/bar/`, and nothing else.

Unfortunately, this requires us to be quite a lot stricter with slashes in paths, and this appears to be revealing a couple of odd edge cases.

**Comment by MoOx** [comment]
You are doing the right thing, no problem :)

**Comment by taion** [comment]
This is fixed on v2.2.2 now.

**Comment by MoOx** [comment]
Thanks for fixing this!

**Comment by taion** [comment]
Any more edge cases in our matching code you're hitting? 😛

**Comment by MoOx** [comment]
Haha, we'll see ^^
