### ISSUE TITLE
Provide unminified production UMD build

### ISSUE THREAD

**Issue by jochenberger** [reactjs/react-router#3309]
It would be nice if there was an unminified production build in the release distributions.
For example, I use React in a Java web application framework. Users of the framework can enable or disable minification and toggle between development and production mode. Those settings are orthogonal (though the default settings are dev=>no minification, prod=> minification)
If a user chooses to disable minification in production, I'd like to be able to serve an unminified production version.
See also https://github.com/facebook/react/issues/5242

**Comment by taion** [comment]
Thanks for your suggestion. We want to follow upstream packaging policies, and as React does not offer such a build, we feel that it'd be best if we were to not offer such a build as well, to avoid confusion or whatever.

Please follow up if your issue gets accepted upstream; we'd be happy to add this if the React team decide that it's a reasonable feature for React.
