### ISSUE TITLE
Wrong prop type in Confirming Navigation guide

### ISSUE THREAD

**Issue by xabikos** [reactjs/react-router#3310]
In [Confirming Navigation quide](https://github.com/reactjs/react-router/blob/master/docs/guides/ConfirmingNavigation.md#confirming-navigation) shows that we need to configure the context as 
```
contextTypes: {
  router: Router.PropTypes.router
},
```
This doesn't work and should replaced probably by 
```
contextTypes: {
  router: React.PropTypes.object.isRequired
},
```

**Comment by taion** [comment]
Why doesn't this work? We recently updated the prop type definitions in v2.2.x to include `Router.PropTypes.router`, as we had accidentally omitted it early.

**Comment by xabikos** [comment]
Ok I think I got it now. 

You first need to do 
```
import Router from 'react-router';
```

and then the PropTypes exist in the scode. Sorry my mistake.
