### ISSUE TITLE
API proposal: export matchRoutes

### ISSUE THREAD

**Issue by kirilknysh** [reactjs/react-router#3312]
Is it possible to have `matchRoutes` exported?
***
My use case is next: I'd like to prevent navigation from viewA to viewB. The best place for it, as far as I can see, is `history.listenBefore` as it's called before any changes in hash/history/router. But the problem is that inside `history.listenBefore` callback there's only `location` object not the actual Route object. And I'd like to store a navigation condition in routes to keep all routes related stuff in one place.
So my proposed implementation would look like (simplified version):

Routes:
```javascript
function getRoutes() {
    return (
        <Route path="/"  component={AppContainer}>
            <Route path="viewA" component={ViewA} canNavigate={false} />
            <Route path="viewA" component={ViewB} canNavigate={false} />
        </Route>
    );
}
```

App:
```javascript
import { matchRoutes, createRoutes } from 'react-router';

history.listenBefore((location, transitionCallback) => {
    matchRoutes(createRoutes(getRoutes()), location, (error, match) => {
        const targetRoute = _.last(match.routes);
        if (targetRoute.canNavigate) {
                transitionCallback();
        } else {
                transitionCallback(false);
        }
    });
});
```
***
I do know that similar behavior could be achieved by `onEnter` hook but the problem is that `onLeave` hook of the current view would be triggered before `onEnter` of target and it may invalidate the state of current view.

**Comment by timdorr** [comment]
Why is your `onLeave` invalidating any state at all? It seems error-prone to rely on a cleanup function to be run before you move to your next route. That route component should be able to instantiate itself without any external dependencies. It would make your components far more predictable and testable too.

**Comment by ryanflorence** [comment]
I think https://github.com/reactjs/react-router/blob/master/docs/guides/ConfirmingNavigation.md might solve your problem. It's the only way to prevent a transition from anywhere (back button, links, etc.)

If not, please describe the use-case in product terms (not "I want this code to do that" but "I don't want them to be able to go back to the first step of the checkout process") and we'll try to answer the question (even though I'm closing the issue)

**Comment by ryanflorence** [comment]
Sorry, the issue was closed because `matchRoutes` is internal and likely to change, so we won't be making it public, and it also seems like a bad idea to meet your use-case.

**Comment by taion** [comment]
Just to add on to this, it's also somewhat inadvisable to call `createRoutes(getRoutes())`, since that requires re-creating objects for your whole route config, twice.

**Comment by kirilknysh** [comment]
Thanks everyone for replies!
@ryanflorence my use case is next: I don't want to allow the user to leave the current view if the target view is not available (for both forward and back navigation). Ideally the decision should be made based on target Route configuration.

**Comment by draganSm** [comment]
I have to generate the context sensitive menu. The required logic is not simple in order to use declarative approach - the content of the menu comes from an API response. Basically, I need to have something like:

```
if (router.match_to_route('/user/:user')) {
   ... do something
}
else if (router.match_to_route('/car/:car/:year')) {
   ... do something
}
```
matchRoutes seems like something that would help me. I'm trying to not parse `location.pathname` manually. Submenu items should be shown only for the active menu.

The code used to render the menu

```
      <ul role="menu" className={styles.menu} aria-label="Side bar">
          {
            menuItems.map(item => (
              <li role="presentation" key={item.id}>
                <div>
                  <Link to={item.url} role="menuitem">
                    {item.label}</Link>
                </div>
                { item.subitems && (
                  <ul className={styles.submenu}>
                    {
                      item.subitems.map(subitem => (
                        <li
                          key={subitem.id}
                        >
                          <a href={subitem.url} role="menuitem">{subitem.label}</a>
                        </li>))
                    }
                  </ul>)}
              </li>))}
        </ul>
```
Is there anything similar to the `matchRoutes` method (r-r v3) that I can use?

**Comment by timdorr** [comment]
Yes, it's in react-router-config: https://github.com/ReactTraining/react-router/tree/master/packages/react-router-config

**Comment by draganSm** [comment]
@timdorr Unfortunately, `react-router-config` requires `react-router v4.0`. I've inherited the project based on `router` v3.0.

I would try with 

```
import matchRoutes from 'react-router/lib/matchRoutes'; // v3.0

const areRoutesHavePath = (routes, path) => routes.some(route => route.path === path);

const generateContent = (currentSection, router) => new Promise((resolve, reject) => {
  const routes = router.routes;
  matchRoutes(routes, location, (error, result) => {
    if (error) {
      console.error(`Can' generate the menu content for the given path ${location.pathname}`);
      return reject(error);
    }
    if (areRoutesHavePath(routes, 'bird/:angrySlug')) {
      ....
    }
    return resolve(result);
  });
});

export default generateContent;
```

**Comment by pshrmn** [comment]
@draganSm I'm pretty sure that the [`match`](https://github.com/ReactTraining/react-router/blob/v3/modules/match.js#L18) function is what you want. That calls `transitionManager.match`, which calls `matchRoutes`, so you should be getting the same result.

**Comment by draganSm** [comment]
@pshrmn - it works. Thank you. The updated code looks like:

```
import { match } from 'react-router';

const generateContent = (currentSection, router) => new Promise((resolve, reject) => {
  const routes = router.routes;
  match({ routes, location }, (error, redirectLocation, renderProps) => {
    if (error) {
      console.error(`Can' generate the menu content for the given path ${location.pathname}`);
      return reject(error);
    }
    const result = [];
    if (areRoutesHavePath(renderProps.routes, 'bird/:angrySlug')) {
      ...
    }
    console.log('result', result);
    return resolve(result);
  });
});

export default generateContent;
```
