### ISSUE TITLE
Support relative paths

### ISSUE THREAD

**Issue by ryanflorence** [reactjs/react-router#3314]
This is issue is just a placeholder so we can assign it to a milestone. I've been working on it over [here](https://github.com/ryanflorence/react-router-relative-links). I need to make a few changes and then I'll make a pull request to bring it into core and close this issue in lieu of the PR.

**Comment by timdorr** [comment]
\*cough\*#2172\*cough\*

**Comment by ryanflorence** [comment]
Yeah, I know, that one is huge now.

**Comment by ryanflorence** [comment]
eh, alright, I'll use that one

**Comment by timdorr** [comment]
![](https://cdn.meme.am/instances/400x/67066807.jpg)

**Comment by taion** [comment]
Err this is a bit late but I'm :+1: for retiring discussion issues and just having something saying "this is our plan", if we've reached a conclusion. Makes it easier to see what's going on.

**Comment by windsome** [comment]
does react-router support relative path in onEnter() ?
```
    indexRoute: {
        onEnter: function (nextState, replace) {
            replace('device/list')
        }   
    },  
```
