### ISSUE TITLE
Implement Cyrillic route paths

### ISSUE THREAD

**Issue by NSLS** [reactjs/react-router#3317]
Hello. I'm building an application using the latest react-router. We want to implement the route paths containing Cyrillic symbols in it, like
`<Route path="/пример" component={Example} />` 
However, this doesn't seem to be working by default, therefore I would like to ask, is it possible to create such routes or can the support of Cyrillic routes be included into the next release?

**Comment by taion** [comment]
We don't currently automatically encode URI segments in paths for pattern matching. There are some complexities in doing so. Take a look at e.g. https://github.com/pillarjs/path-to-regexp/issues/42 and https://github.com/pillarjs/router/pull/15 for the concerns from the Express team.

I don't think we can really handle this satisfactorily on our end right now. Can you just encode the relevant URI segments yourself?

**Comment by NSLS** [comment]
@taion Thanks a lot! 
For anyone who runs into the same issue, the solution is to simply encode your UTF-8 string before passing it into route.
In my case, an example for this would look like
`<Route path={encodeURIComponent('пример')} component={Example} />`
And with using route params you should write it like this
`<Route path={encodeURIComponent('пример') + '/:id'} component={Example} />`

The issue is solved.
