### ISSUE TITLE
undefined Link classNames after upgrading 2.0 -> 2.2

### ISSUE THREAD

**Issue by sprzybylski** [reactjs/react-router#3322]
My tests started to fail after upgrading to 2.2, what was unexpected bumping just minor version.
I was expecting every Link component to have className props.

Should we update upgrade guide for 2.2 or this should be considered a bug?

```javascript
const links = TestUtils.scryRenderedComponentsWithType(component, Link);
links.map((link) => link.props.className)
```
2.0.1 outputs:
[ '', 'a-class-name' ]
2.2.2 outputs:
[ undefined, 'a-class-name' ]

**Comment by ryanflorence** [comment]
Sorry it broke your tests. Rendering w/ empty classNames was a bug so we don't consider it a breaking change.

#3288

**Comment by sprzybylski** [comment]
Thanks!
Want me to make a PR with the note?
Below part of test case for my pagination component that failed after upgrading. 

```javascript
const links = TestUtils.scryRenderedComponentsWithType(component, Link);
const previous = links.find((link) => link.props.className.match('previous'));
previous.props.to.should.equal(correctPath);
```

**Comment by taion** [comment]
@sprzybylski That's a generally not-recommended pattern for testing classes. You should be asserting on the actual rendered classes, not `props.className`.
