### ISSUE TITLE
Object.assign is not a function

### ISSUE THREAD

**Issue by iotch** [reactjs/react-router#3329]
Hello.
Is seems like react-router requires an Object.assign polyfill, since react 15?
I'm getting `Uncaught TypeError: Object.assign is not a function` in some browsers. Looks like `getComponents()` is using it here: https://github.com/reactjs/react-router/blob/master/modules/getComponents.js#L33
Or I'm missing something? Thanks!

**Comment by taion** [comment]
Oops, my bad.

**Comment by taion** [comment]
Released as v2.2.3.
