### ISSUE TITLE
Problem with version 2.2.3 and npm

### ISSUE THREAD

**Issue by mntbkr** [reactjs/react-router#3332]
## Steps to reproduce
`npm install react-router --save`

## Expected Behavior
I expect react-router to be installed into my project

## Actual Behavior
`npm ERR! fetch failed https://registry.npmjs.org/react-router/-/react-router-2.2.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404`

If I navigate to https://registry.npmjs.org/react-router/-/react-router-2.2.3.tgz I get a 404, but change the URL to be for version 2.2.2 and it works.  My work around for now is to specify version 2.2.2 in package.json

I am unsure if this should be reported here or to NPM, but I figure you guys should be aware of this problem, even if there is nothing you can do about it.

**Comment by taion** [comment]
I just published v2.2.4 to work around this issue. Can you confirm if it works for you?

**Comment by mntbkr** [comment]
checking now

**Comment by mntbkr** [comment]
yes all is well again....2.2.4 is installed.  Thanks for your help

**Comment by taion** [comment]
Okay, closing this out, then. Sorry for the inconvenience (but I swear it wasn't my fault 😛).

**Comment by timdorr** [comment]
Bad timing: http://status.npmjs.org/incidents/7n06gj3f83tz

**Comment by mntbkr** [comment]
@timdorr thanks for posting that link...I was thrilled with the amazing response @taion and am glad to understand what happened.
