### ISSUE TITLE
Example of loading indicator/animation when changing async routes, please

### ISSUE THREAD

**Issue by iotch** [reactjs/react-router#3338]
Hello. Will be great to see an example of loading indicator/animation when changing routes, especially between routes that loaded async (for huge modules on slow connections there is a noticeable delay between pages re-render). Sorry for asking here, but Stackoverflow didn't helped.
Thanks!

**Comment by taion** [comment]
Unfortunately this isn't a good fit for our current example format – we'd need to e.g. introduce artificial latency to get the indicator to even display in a meaningful way, and it'd also be an advanced special case of something we already consider advanced usage. The basic approach right now is to do `history.listen` before setting up the router, then initiating a display of the loading indicator on a timeout (but clear it when the router transitions).

I'd suggest following #3232.

**Comment by iotch** [comment]
Couple more questions, if you don't mind.

1) Is this a valid approach to listen for URL change via `browserHistory.listen()` and treat it as "transition begin/busy state" and `Router.onUpdate()` as "transition end/ready state"?
Like:
````javascript
browserHistory.listen(function(location) {
   console.log('app is busy');
});

ReactDOM.render(
    <Router history={ browserHistory } children={ ... } onUpdate={ () => { console.log('app is ready') } } />, 
    document.getElementById('app')
)
````

2) Could you, please, advice why there is a gap in rendering (blank screen) between _"React is not loaded yet"_ and _"I'm a huge component"_ in the following example? I mean, why React renders a `<div id="app"><!-- react-empty: 1 --></div>` instead of waiting for a component and replacing the initial html only after that? And how to avoid that?

````html
<!-- index.html -->
...
<div id="app">React is not loaded yet</div>
...
````
````jsx
/* app.js */
const App = React.createClass({
    render: function() {
        return(<div>I'm a huge component</div>);
    }
});

var rootRoute = {
    path: '/',
    getComponent(location, callback) {
        // pretend we're fetching the component async
        setTimeout(function() {
            callback(null, App);
        }, 2000)
    }
};

ReactDOM.render(
    <Router history={ browserHistory } children={ rootRoute } />, 
    document.getElementById('app')
);
````
So the steps are:
````html
<div id="app">React is not loaded yet</div>
<div id="app"><!-- react-empty: 1 --></div>
...delay
<div id="app"><div data-reactroot="">I'm a huge component</div></div>
````
instead of:

````html
<div id="app">React is not loaded yet</div>
...delay
<div id="app"><div data-reactroot="">I'm a huge component</div></div>
````
Thanks!

**Comment by taion** [comment]
1. That looks fine
2. React Router renders a `null` when there's async stuff that isn't resolved. See caveats in the server rendering guide for details on what to do.

**Comment by taion** [comment]
ETA: Though on 1, you'll end up re-rendering twice when the load is ready, since `onUpdate` runs after the new routes render properly.

**Comment by iotch** [comment]
@taion, could you, please, advice how to deal with redirects when using `match({routes:..., location:...}, err, redirect, props)` on the client (I need to wait for all routes to resolve). 

Is it possible to re-render the app again somehow without reloading the page, or the only way is `window.location = redirect`?

I could re-render the app with the new location, but when `location` is set,  `props` are `undefined`, so it is not possible, if I understand correctly.

Thank you!

**Comment by taion** [comment]
You shouldn't need to – the server should resolve all the redirects before anything renders by 302ing the client to the ultimate redirect location. If you're doing SSR, the client shouldn't need to further do any redirects.

**Comment by iotch** [comment]
I'm not using SSR, I'm using `match()` to avoid rendering a blank space while routes being loaded, as you adviced. https://github.com/reactjs/react-router/issues/3338#issuecomment-211043018

Since my last post I figured out to use the following method, but not sure if it is correct:
````javascript
// When redirect from match() callback !== undefined
render(<Router { ...redirect } routes={ routes } history={ browserHistory } />)
````
It works, but I might miss something.

**Comment by taion** [comment]
You're going to get the blank space no matter what until routes are loaded. The page has to show _something_. Use `match` on the client side only to hydrate a server-side match.

**Comment by iotch** [comment]
Ok, forget about it, thanks
