### ISSUE TITLE
Error: Operation not permitted, rename...

### ISSUE THREAD

**Issue by dylanparry** [reactjs/react-router#3353]
I’m having an issue whereby the first attempt to update or install any of the recent versions will end with an error (see below). If I then install again after the error, it works okay. It looks like it's trying to rename a directory after it has been deleted, or that the operation isn't supported on my OS (Windows 10).

I’m not sure when I first encountered this error. It wasn't occurring in the original 2.0.0 release, I’m pretty sure of that, but I’ve seen it for the last few releases at least.

## Version
2.3.0

## Steps to reproduce

Install/update any of the recent versions. Using: `npm install --save-dev react-router` or `npm update --save-dev react-router`.

## Expected Behavior

I’ve shortened the paths shown below, and replaced them with `...` to make the output more concise.

```
E:\...\MyProject>npm install --save-dev react-router
npm@1.0.0 E:\...\MyProject
`-- react-router@2.3.0

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
```

## Actual Behavior

```
E:\...\MyProject>npm install --save-dev react-router
npm WARN install:react-router@2.3.0 EPERM: operation not permitted, rename 'E:\...\MyProject\node_modules\react-router' -> 'E:\...\MyProject\node_modules\.react-router.DELETE'
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
```

**Comment by taion** [comment]
This seems like an issue with your local package directory. Try wiping `node_modules` and reinstalling.

**Comment by hieverest** [comment]
I just ran into this problem. Solved by stopping running the localhost.

**Comment by scifutures** [comment]
@hieverest Thank you, I could not get `npm clean cache` to work, or the other solutions.  Looks like the react-scripts tie up the NPM modules while its running the dev server.

**Comment by amtili** [comment]
so what's is the solution about this problem?

**Comment by scifutures** [comment]
@amtili Stop any local processes running the server, then run `npm install` or `npm update`.
