### ISSUE TITLE
React component rendered by server is also rerendered on client side

### ISSUE THREAD

**Issue by lauterry** [reactjs/react-router#3354]
Hello

I'm building an isomorphic application with react router. My code is code splitted with webpack.
My react component rendered by server is also rerendered on client side resulting a blink effect.

I have described my issue in this repo - https://github.com/jaredpalmer/react-production-starter/issues/43

You can reproduce the problem with the same repo.

Best regards

**Comment by taion** [comment]
This is covered in the server rendering guide.

**Comment by lauterry** [comment]
Thx for missing this part of the documentation. Sorry for the noise.
