### ISSUE TITLE
'undefined' is not an object (evaluating 'routes.reduce') 

### ISSUE THREAD

**Issue by pseidemann** [reactjs/react-router#3355]
## Version
2.1.1

## Test Case
N/A

## Steps to reproduce
N/A

## Expected Behavior
exception doesn't happen

## Actual Behavior
exception `TypeError: 'undefined' is not an object (evaluating 'routes.reduce')` happens

I'm getting the following exception in a fairly old embedded webkit browser:
`TypeError: 'undefined' is not an object (evaluating 'routes.reduce')`
from this code snippet from react-router
```javascript
function getEnterHooks(routes) {
  return routes.reduce(function (hooks, route) { // <<< exception here, routes is undefined
    if (route.onEnter) hooks.push(createTransitionHook(route.onEnter, route, 3));

    return hooks;
  }, []);
}
```
same method in git repo: https://github.com/reactjs/react-router/blob/5573af08dc5e78612fdf3a106e0d5dfb7f2a51fb/modules/TransitionUtils.js#L17

this exception only happens on initial load of the page when the embedded device was freshly started.
when I do location.reload() via the javascript debugger, the app works just fine. the app also works just fine in other browsers.
the browser version seems to be Safari/534.34 (AppleWebKit/534.34) but this might not be exact because the embedded device uses proprietary software.
any ideas? I tried poking around the router's source code but I could only find out that it seems that the `routes` object in the state is undefined for some reason on the first load

**Comment by taion** [comment]
Do you have a repro? It's not clear to me how you can end up in this situation where the "nextState" routes are undefined.

**Comment by taion** [comment]
Closing pending repro.

**Comment by pseidemann** [comment]
@taion, could you re-open please? I still try to figure out how to reproduce this without having the actual hardware

**Comment by taion** [comment]
I'll be happy to re-open this once we have some sort of repro. Otherwise there just isn't any action item available.

**Comment by pseidemann** [comment]
@taion, I have some real trouble debugging this issue. could you maybe give some hints in which cases the nextState could be undefined? maybe you could also name on which es6 apis the state relies and where some bad browser behavior could break it? I wonder if this would also happen if the router would just use es5 apis

**Comment by taion** [comment]
React Router as released does not use ES6 – it's all transpired down to ES5. I'm not aware of any situation where `nextState` would be undefined, which is why I asked for a repro here.

**Comment by pseidemann** [comment]
I was able to find the origin of the bug.
it turned out that the native `Object.assign()` function of the browser has a bug. the function is used by react-router, if available. particularly `Object.assign({}, {a: 1, b: 2})` fails to merge property "a" which is "routes" in react-router's code.
I think there is no proper fix on react-router's side for this

**Comment by taion** [comment]
What the heck? Which browser?

**Comment by naw** [comment]
We've seen this behavior in certain conditions in the Qt WebKit browser while running browser-based specs with capybara-webkit.  Upgrading to Qt 5.5.1 (and reinstalling capybara-webkit) remedied the problem, however some machines running other/older versions of Qt were not affected.

This is in conjunction with core-js/shim.  I was not able to narrow down the exact combination of code which caused it, but it is _not_ directly related to `react-router`. 

Nevertheless, the problem manifests in the `'undefined' is not an object (evaluating 'routes.reduce')` error, which is why I'm posting here for anyone else who might stumble on this in a similar situation.
