### ISSUE TITLE
Glossary is Missing Documentation on ** (greedy matching)

### ISSUE THREAD

**Issue by ybot1122** [reactjs/react-router#3359]
Hi React-Router!

I noticed this discrepancy on the docs Glossary

The Route Matching guides describe and document **, greedy matching: https://github.com/reactjs/react-router/blob/master/docs/guides/RouteMatching.md#path-syntax

That guide references to the Glossary. Unfortunately, the glossary definition for RoutePattern makes no acknowledgement of greedy matching: https://github.com/reactjs/react-router/blob/master/docs/Glossary.md#routepattern

I think is a considerable discrepancy since
- inclination to treat glossary as truth over the implementation guide
- greedy matching is a major feature and should be conveyed consistently

Let me know if you have preferred intake for doc updates.
Toby

**Comment by timdorr** [comment]
> Let me know if you have preferred intake for doc updates.

A PR is better than an issue.

**Comment by taion** [comment]
Merged into https://github.com/reactjs/react-router/issues/2933.
