### ISSUE TITLE
Bug: The `route` PropType doesn't support object routes

### ISSUE THREAD

**Issue by EvNaverniouk** [reactjs/react-router#3363]
Using React Router 2.3.0. It appears that the `route` PropType doesn't support object routes.

Consider this:

```javascript
import RouterPropTypes from 'react-router';

export default class MyComponent extends Component {
	static propTypes = {
		route: RouterPropTypes.route.isRequired
	};

	static contextTypes = {
		router: PropTypes.object.isRequired
	};

	render () {
		return <span />
	}
}
```

Will throw with:

```Warning: Failed propType: MyComponent: prop type `route` is invalid; it must be a function, usually from React.PropTypes. Check the render method of `RouterContext`.```

The route is defined as:

```javascript
const routes = {
	childRoutes: [{
		getComponent: Another,
		path: "another"
	}],
	getComponent: (location, cb) => require(MyComponent)),
	path: "my_route"
}
```

And if I console log the `this.props.route` I see:

```javascript
console.log(this.props.route);

{
	__id__: 1,
	getComponent: function MyComponent(location, cb),
	path: "my_route"
}
```

Looking at the source code for React Router, I see the proptype is defined as `object` or `array`, so I'm not sure where this error message is coming from.

**Comment by taion** [comment]
1. `import RouterPropTypes from 'react-router';` is not valid; there's no default export from `react-router`
2. The `route` prop type used as an internal prop type for validation; it doesn't refer to the `route` prop injected into a route component
3. These prop types are all deprecated anyway because of (2)
