### ISSUE TITLE
How to dynamic load Named Components?

### ISSUE THREAD

**Issue by agile116** [reactjs/react-router#3364]
Hi All,

I have the following route config now, I'd like to convert it to dynamic routes using System.import, any solutions there? Thanks.
<Route path='admin' components={{leftSide: LeftComp, main: Admin, rightSide: RightComp}}/>

**Comment by mxstbr** [comment]
There's no route config attached. Take a look at this for an example diff: https://github.com/mxstbr/react-boilerplate/pull/254/files#diff-6db976b763ed71154781e45807c0d4e5
