### ISSUE TITLE
documentation change

### ISSUE THREAD

**Issue by fedgrant** [reactjs/react-router#3365]
Hey, I was getting a invariant.js?d9d8:39 Uncaught Invariant Violation: error after following a example in the API documentation. I made a change for it if you would like to merge it.

https://github.com/fedgrant/react-router/commit/74a955243b0b658200f682712d7c70b642d4e928

**Comment by taion** [comment]
Can you PR that?

**Comment by fedgrant** [comment]
Which branch?

**Comment by taion** [comment]
master
