### ISSUE TITLE
Uncaught TypeError: hook.apply is not a function on using onEnter in react-router

### ISSUE THREAD

**Issue by srahulprdxn** [reactjs/react-router#3372]
Below is the code snippet:

```
function requireAuth(nextState, transition, callback) {
  console.log('hey');

  callback();
}
```

```
export const AdminList = {
  'path': 'admin-area/admin-list',
  getComponent(location, cb) {
    require.ensure([], (require) => {
      cb(null, require('components/admin/admin-list/admin-list').default);
    }, 'admin-list');
  },
  'onEnter': {requireAuth}
};
```

On entering the path /admin-area/admin-list, I get the error mentioned in the title from the file TransitionUtils.js.

I am not sure what is causing this error. Can anyone please help?

StackOverflow: [hook.apply is not a function](http://goo.gl/lUa5g6)

**Comment by taion** [comment]
`onEnter` needs to be a function

**Comment by growtofill** [comment]
So that's it, issue closed? How about adding a PropTypes or other validation to provide a concise error message?

**Comment by taion** [comment]
That's not even going through the React route definition above.

**Comment by growtofill** [comment]
> That's not even going through the React route definition above.

Sorry, didn't get what you mean.

**Comment by timdorr** [comment]
It's not a React component, so there's no PropType validations to be done.
