### ISSUE TITLE
this.context.router.listenBefore called twice when I click on <a href="#/....">

### ISSUE THREAD

**Issue by IAkumaI** [reactjs/react-router#3373]
```
this.context.router.listenBefore((loc, cb) => {
 console.log('called');
cb();
});
```

And when I just click on ```<a href="#/catalog/123">To 123</a>``` (example) it called twice.
Same result with ```this.context.router.setRouteLeaveHook```

If I use ```<Link />``` component - all works fine.

**Comment by taion** [comment]
Use `<Link>` – normal anchors trigger that twice because they go through page navigation, and extra work is required to e.g. set query keys, &c.
