### ISSUE TITLE
<Link> dosn't respect current hash

### ISSUE THREAD

**Issue by FezVrasta** [reactjs/react-router#3374]
Hi,

I have several `<Link>` elements which have all the same `pathname` but different `hash`.

When the page get loaded, all of them are set as `active` even if the URL hash should match just one of them.

Is it something not supported, am I doing something wrong or is it a bug?

```jsx
// url: /pathname#a
<Link to={{pathname: 'foo', hash: 'a'}} activeClassName='active'>a</Link> // active
<Link to={{pathname: 'foo', hash: 'b'}} activeClassName='active'>b</Link> // active
```

**Comment by taion** [comment]
Active state based on hash is not supported. We've chosen to make active state correspond to just the path and query, as this is what we believe satisfies most use cases.

**Comment by fedgrant** [comment]
This might also have been already decided with the above, but I have a url 
```
:3000/referral/a?class_ids=1435,1439&promo=FREEBIE
```
with the routes in router 

```
<Route path="referral" component={ReferralCont} onEnter={checkForReferral}> 
    <Route path=":refId" component={Referral} />
</Route> 
```

when navigating to url from a external page it works fine, but if i come from a link 

```
<Link style={styles.link} to={/referral/a?class_ids=1435,1439&promo=FREEBIE}>
  Back to your referral
</Link>
```

something is eating the query part of the url.
