### ISSUE TITLE
RegExp param for `router.isActive`

### ISSUE THREAD

**Issue by Rokt33r** [reactjs/react-router#3375]
`router.isActive(/^\/hello/)` would be great to deal with the problem like #3277
It makes the method much flexible and doesn't seem to destructive.

I know #3277 is due to wrong structure of routes.
But, it is quite annoying to take care about it when prototyping app.
> I, therefore, prefer to use `this.props.location.pathname.match(/^\hello/)` for my new app.

**Comment by taion** [comment]
You can use whatever semantics you want in user space – checking the pathname explicitly like that is fine, if it's what your application requires.
