### ISSUE TITLE
Absolute path question

### ISSUE THREAD

**Issue by deser** [reactjs/react-router#3376]
Guys, is it ok to configure application in this way:
I have Viewport.react.js which is:
```
render() {
        return (
            <div>
                {this.props.children}
                <Footer />
                <ModalRoot />
            </div>
        );
    }
```

And I have the next route config:
```
<Route component={require(`${pagePath}/Viewport.react`)}>
        <Route path='/suppliers' onEnter={onRouteEnter} component={require(`${pagePath}/SuppliersView.react`)} />
        <Route path='/suppliers/supplier/:supplierId' component={require(`${pagePath}/SupplierView.react`)} />
        <Route path='/suppliers/supplier/:supplierId/product/:productId' component={require(`${pagePath}/ProductView.react`)} />
        <Route path='/suppliers/supplier/:supplierId/product/:productId/version/:versionId' component={require(`${pagePath}/VersionView.react`)} />
        <Route path='/suppliers/supplier/:supplierId/product/:productId/version/:versionId/screen/:screenId' component={require(`${pagePath}/ScreenDesigner.react`)} />
        <Route path='/suppliers/supplier/:supplierId/product/:productId/version/:versionId/screen/:screenId/grid_detail_view/:gridId' component={require(`${pagePath}/GridPopupDesigner.react`)} />
        <Route path='/suppliers/supplier/:supplierId/product/:productId/preview/version/:versionId/:destiny' component={require(`${pagePath}/PreviewView.react`)} />
        <Route path='/suppliers/supplier/:supplierId/product/:productId/preview/version/:versionId/screen/:screenId' component={require(`${pagePath}/ScreenPreviewView.react`)} />
        <Route path='/suppliers/supplier/:supplierId/product/:productId/preview/version/:versionId/screen/:screenId/grid_detail_view/:gridId/:gridDetailViewId' component={require(`${pagePath}/ScreenPreviewView.react`)} />
        <Redirect from="/" to="/suppliers" />
    </Route>

```

All these nested routes are practically rendered inside Viewport.react. 

1. Is this approach still alive or I should do the things in other way?
2. How can I transit from one page to other? I have an idea to use lodash.template for creating path for router.push. Is it correct?
3. How can I check if the route ( let's say `/suppliers/supplier/:supplierId/product/:productId/preview/version/:versionId/screen/:screenId` ) is active?

Thanks a lot for help! 
P.S. I'm migrating from 0.13 to 2.3.0 and this is very painful process :(

**Comment by taion** [comment]
You should generally prefer to use route nesting + index routes for a configuration like that to avoid path duplication.

For page transitions, you can use something like `use-named-routes`, or use `formatPattern` yourself based on the path templates.

If you need to check activity for an arbitrary route with unspecified parameters, you'll have to handle that yourself. The router active checks only cover routes with parameters.

**Comment by deser** [comment]
Thanks
