### ISSUE TITLE
withRouter() and latest version

### ISSUE THREAD

**Issue by iotch** [reactjs/react-router#3378]
Hello.
It seems like docs and "passing-props-to-children" example has the new `withRouter()` method mentions from upcoming 2.4.0, but the latest released version is 2.3.0. So, for obvious reasons, it doesn't work.
Thanks.

**Comment by taion** [comment]
That's correct. Documentation corresponds to master, which is a little bit ahead of the latest release right now.

**Comment by taion** [comment]
2.4.0 is out now.
