### ISSUE TITLE
Examples don't work on windows

### ISSUE THREAD

**Issue by deser** [reactjs/react-router#3381]
If I simply run `npm start` then I see `'BABEL_ENV' is not recognized as an internal or external command` error. Ok, I fixed it in package.json - https://monosnap.com/file/Kaf4rRheIBFK8w6ogpSlHcLdT1CYzn

And when try to open any example I see in browser console:
`app.js:1 Uncaught SyntaxError: Unexpected token import`

**Comment by deser** [comment]
Still doesn't work https://monosnap.com/file/Kaf4rRheIBFK8w6ogpSlHcLdT1CYzn

**Comment by deser** [comment]
And when try to open any example I see in browser console:
app.js:1 Uncaught SyntaxError: Unexpected token import

**Comment by deser** [comment]
Still doesn't work

**Comment by deser** [comment]
Seems that babel doesn't transpile

**Comment by taion** [comment]
Make sure you've updated your dependencies. We are using cross-OS safe environment settings now, and this works elsewhere.

**Comment by deser** [comment]
But it doesn't work :)

So I'm doing the next:
To run the examples in your development environment:

Clone this repo   --- git@github.com:reactjs/react-router.git
Run npm install  --- done
Start the development server with npm start   ---- done
I see: 
![image](https://cloud.githubusercontent.com/assets/3010698/14862312/74a5a696-0cb9-11e6-9097-52ac3c797f7b.png)

Point your browser to http://localhost:8080 ---- done
I see: 
![image](https://cloud.githubusercontent.com/assets/3010698/14862324/8536f10e-0cb9-11e6-988a-78c9140d585f.png)

Seems work but if I go to any page I see an error:
![image](https://cloud.githubusercontent.com/assets/3010698/14862359/a7d9b066-0cb9-11e6-963f-91184319d813.png)

**Comment by taion** [comment]
cc @kentcdodds

**Comment by taion** [comment]
cc @kentcdodds Am I using `cross-env` incorrectly here for the `start` script?

**Comment by kentcdodds** [comment]
Looks like you're using it correctly. My guess is that cross-env is incorrectly detecting the environment.

**Comment by taion** [comment]
Thanks! I'm going to re-close this unless I hear more reports of issues on Windows then.

**Comment by deser** [comment]
Did you check it by yourself on windows?

**Comment by taion** [comment]
![image](https://cloud.githubusercontent.com/assets/3112159/14890817/04e22c2a-0d32-11e6-8da2-e007b4900b1d.png)

**Comment by deser** [comment]
Magic :)
