### ISSUE TITLE
Issue with the listener and the params

### ISSUE THREAD

**Issue by florian-barbare** [reactjs/react-router#3384]
Hello,
I'm trying to do trigger actions when the URL has changed, so I'd use the `listen` function.
The problem there is that my action depends on a URL param `/something/:param` and I can't get the URL params from the listener location.
I've open a stackoverflow question as I'm not sure it's the best way to do what I'm trying to do:
http://stackoverflow.com/questions/36826453/react-router-listen-get-params
Thanks

**Comment by taion** [comment]
We don't really support observing params from `listen`. If you need access to your params, get them from inside your component. This allows us to avoid subtle lifecycle issues where e.g. what you have in your Flux store doesn't match what's rendered.
