### ISSUE TITLE
Can't unlisten browserHistory

### ISSUE THREAD

**Issue by FezVrasta** [reactjs/react-router#3385]
I've tried asking on StackOverflow without results...
http://stackoverflow.com/questions/36851800/react-router-browserhistory-removelisten

How can I `unlisten` `browserHistory`?

**Comment by timdorr** [comment]
The return from `listen` is a function that will remove the listener when called.

**Comment by FezVrasta** [comment]
Is it documented somewhere?

**Comment by timdorr** [comment]
Not here, but on the related `history` project: https://github.com/mjackson/history/blob/master/docs/GettingStarted.md

**Comment by FezVrasta** [comment]
thanks
