### ISSUE TITLE
Deprecation warning when using browserHistory

### ISSUE THREAD

**Issue by ochowie** [reactjs/react-router#3390]
When I try to run the example listed in the repo I get the following warning:

Warning: Automatically setting basename using <base href> is deprecated and will be removed in the next major release. The semantics of <base href>are subtly different from basename. Please pass the basename explicitly in the options to createHistory.

This is using react-redux-router 4.0.4 and react-router 2.3.0. I've tried passing basename in a few places but I'm not sure how to pass this down to the createHistory call.

**Comment by taion** [comment]
Dupe https://github.com/reactjs/react-router/issues/3387
