### ISSUE TITLE
Static and segments paths problems

### ISSUE THREAD

**Issue by FezVrasta** [reactjs/react-router#3393]
## Version
2.3.0

## Test Case
http://jsbin.com/kolevevune/1/edit?js,output

## Steps to reproduce
- click on "a/1"

## Expected Behavior
the link pointing to `/a` should be active as well, instead it's not.

Note: I'm using a segment just for the top path because I need to know the current segment just when I'm inside the first path, but I want then to define different components for the sub routes.

my full route is:

```
  <Router history={browserHistory}>
    <Redirect from='/' to='/tv-shows' />

    <Route path='/:category' component={App}>
      <IndexRoute component={Content} />
      <Route path='/tv-shows/:id' component={TVShow}>
          <IndexRedirect to='/tv-shows/:id/about' />
          <Route path='/tv-shows/:id/about' component={TVShowAbout} />
          <Route path='/tv-shows/:id/season/:season' component={Season} />
      </Route>
      <Route path='/movies/:id' component={Movie} />
    </Route>
  </Router>
```

PS. the jsbin provided in the template is outdated and doesn't work, you may want to update it

**Comment by taion** [comment]
See https://github.com/reactjs/react-router/blob/master/docs/Troubleshooting.md#parent-path-does-not-show-as-active.

**Comment by FezVrasta** [comment]
That's nice but I don't think it's a solution for my problem...

I can't change my router to look like this:
  <Router history={browserHistory}>
    <Redirect from='/' to='/tv-shows' />

    <Route path='/:category' component={App}>
      <IndexRoute component={Content} />
      <Route path=':id' component={TVShow}>
          <IndexRedirect to='about' />
          <Route path='about' component={TVShowAbout} />
          <Route path='season/:season' component={Season} />
      </Route>
      <Route path=':id' component={Movie} />
    </Route>
  </Router>

doing so the router doesn't know when to load TVSHow or Movie...

**Comment by taion** [comment]
Split the two branches out.

**Comment by FezVrasta** [comment]
Sorry I don't get what you mean. May you give me an example?

**Comment by taion** [comment]
Use separate top level routes for each category.

**Comment by FezVrasta** [comment]
Thanks, but then I have to assign a different component for each of them... I wanted to share the same component and use the segment value. I thought it was the purpose of it. I'm used to Ember and there they work in this way.

**Comment by taion** [comment]
You can use the same component just fine. You should just declare two separate routes. You can check `this.props.route` to check which route actually rendered.

**Comment by FezVrasta** [comment]
Thanks it seems to work, even if it looks like an horrible hack and I don't think this issue should be closed...

**Comment by taion** [comment]
You can set e.g. `<Route category="foo">` and read `this.props.route.category`.

The earlier configuration you have is not quite semantically correct anyway, since it would match on e.g. `/random-string`.
