### ISSUE TITLE
How to get object 'router' in react-router@2.3.0

### ISSUE THREAD

**Issue by hhhyaaon** [reactjs/react-router#3399]
##Question
As the v2.0.0 upgrade guide shows, I can use a `router` to navigate instead of `history` 
![image](https://cloud.githubusercontent.com/assets/17123400/14873786/7e80fa58-0d2c-11e6-84ed-7f979a70f32b.png)

However, how can I get the object `router`?
I try to get the `router` by `<RouterContext>` or `withRouter`(v2.4.0), but they aren't work.

![image](https://cloud.githubusercontent.com/assets/17123400/14873828/f4070358-0d2c-11e6-9a41-86f79ffd370c.png)

How can I solve the problem?
Thx

## Version
2.3.0

**Comment by timdorr** [comment]
Apologies, as what's on master right now is unreleased. In the meantime, browse the 2.3.0 docs: https://github.com/reactjs/react-router/blob/v2.3.0/upgrade-guides/v2.0.0.md

**Comment by taion** [comment]
2.4.0 is out now.
