### ISSUE TITLE
router can not recognize dot in path

### ISSUE THREAD

**Issue by sonenko** [reactjs/react-router#3402]
how to reproduce:
1. create route `{path: "some/:id", component: SomeCmp}`
2. now! use this route, but type directly in browser something with dot ex: `localhost:3000/some/hello.world` - dot here.
3. view `SomeCmp` will not appear at page. But if type `localhost:3000/some/hello` - we will see contents of SomeCmp.
PS: I wondering but similar steps for `search params` works just fine.

**Comment by taion** [comment]
Works fine for me. Please provide a repro demonstrating this if you continue to see problems.

**Comment by sonenko** [comment]
strange I can not reproduce same using your repository, it is definitely works for this repo and not a bug of react-router. Sorry guys, wrong report.
