### ISSUE TITLE
Make the <Link> rendered <a> dynamic.

### ISSUE THREAD

**Issue by aaronbeall** [reactjs/react-router#3408]
## Version
2.0.0

## Description

The `<Link>` component [renders a `<a>` tag](https://github.com/reactjs/react-router/blob/master/modules/Link.js#L136), but in some cases we want to use a `<button>` or a `<div>` or something else. It would be nice if the `<Link>` component had a property like `element` which defaults to `"a"` but could be anything you want.

**Comment by taion** [comment]
See earlier discussion in https://github.com/reactjs/react-router/issues/83, https://github.com/reactjs/react-router/pull/816, and others.

We want to keep `<Link>` as simple as possible, and give it optimal a11y by default as an anchor.
