### ISSUE TITLE
Changing url triggers page reload in version 2.0

### ISSUE THREAD

**Issue by anton-aleksandrov** [reactjs/react-router#3411]
When I was using react-router 0.13.3, it was ok: i was changing url and transition without reload was happening.

Now, in react-router 2.0 if I'm changing url manually, my app gets reloaded entirely instead of simple redirect.
How do i fix it?

I want to use this:

    <a href="/routename">link</a>

instead this:

    <Link to="/routename">link</Link>

I know, it's not quite correct, but i need it in few special cases

Routes:

    import {Router, Route, IndexRoute} from "react-router";
    import App from './components/App';
    import FrontPage from './components/frontPage/FrontPage';
    import User from './components/user/User';
    module.exports = (
    	<Router>
    		<Route path="/" component={App}>
    			<IndexRoute component={FrontPage}/>
    	        <Route path="/user/:userid" component={User}/>
    		</Route>
    	</Router>
    );

**Comment by taion** [comment]
When using a browser history, you need to run the transition in JavaScript to update the URL and trigger navigation. You can't use an `<a>` to do so, as the browser will always refresh the location when you do that.

**Comment by anton-aleksandrov** [comment]
can you advice any way around?

**Comment by taion** [comment]
You need an `onClick` handler on the `<a>` to do SPA-style navigation.

**Comment by rivers-dash** [comment]
But it will keep refreshing the page unless you use `e.preventDefault()` but then you'll lose the `href="/routename"` redirection which is the purpose of this routing maneuver.
