### ISSUE TITLE
Android webview does not support history.goBack();

### ISSUE THREAD

**Issue by ibufu** [reactjs/react-router#3412]
I have tested hashHistory and html5history, but both of them failed with history.goBack() at android webview.

## Version
2.1.0

**Comment by taion** [comment]
Those underlying web APIs don't work in that context. Try using the `createMemoryHistory` instead.

**Comment by netpro2k** [comment]
@taion Can you explain what you mean by "Those underlying web APIs don't work in that context"? MemoryHistory doesn't fit my usecase but id still like the ability to go back on android. (It seems to sometimes work, but has issues other times, without a very clear pattern.

**Comment by acomito** [comment]
@netpro2k did you ever figure out a solution for this? I just noticed it on an app.
