### ISSUE TITLE
can I change the window.location without transition

### ISSUE THREAD

**Issue by beku8** [reactjs/react-router#3413]
Hello,
I'm trying to find a way to navigate without affecting the scroll, I can't find documentation for ```ignoreScrollBehavior``` I tried this attribute set all the way up to the hierarchy, but can't manage it to work. Does it still work?
Another option would be if I can change the window.location without transition or refresh, and that will be handled inside the component. On page refresh it will have its correct "view" set.

Any advice will be highly appreciated, thanks.

**Comment by taion** [comment]
Only old versions of React Router (0.13.x and earlier) had scroll management built-in. We don't support them any more.
