### ISSUE TITLE
How to make server-side and client side rendering work together seamlessly?

### ISSUE THREAD

**Issue by ericntd** [reactjs/react-router#3417]
I know this isn't the best place for Q & A and I have my question on StackOverflow: http://stackoverflow.com/questions/36855744/react-server-side-and-client-side-rendering-not-seamless

I don't think the question has received enough attention so far so I've added 50 reputation bounty.

I'm sure I'm not the only person trying to achieve this.
Please point me to the correct direction.

Thanks,

**Comment by timdorr** [comment]
You need to provide more context on the question. If you have a publicly-accessible repo that someone can see what you're building, that might help. But there isn't enough code to look at there to see what's going on.
