### ISSUE TITLE
Routing with Objects and Arrays

### ISSUE THREAD

**Issue by thefirstave** [reactjs/react-router#3421]
Hi, 

can someone please help me to implement the dynamic routing with objects and arrays?

I want to do something like this:

```javascript
const routes = {
 path: '/',
 component: App,
 indexRoute: { component: Dashboard },
  childRoutes: [
    { path: 'staff', component: Staff },
    { path: 'customer/:customersID', component: Customer },
    { path: 'customer(/:customerID)', component: Customer },
    { path: 'customer', component: Customer, childRoutes: [
        { path: ":customerID", component: Customer, id: customerID }
      ]
    },
    { path: 'about', component: About },
    { path: 'tac', component: TaC },
  ]
};
```

Unfortunately, none of the paths linking to Customer work.

FYI: App, Dashboard, Staff, Customers, Customer, About and TaC are predefined

**Comment by timdorr** [comment]
You have a redundant path. Get rid of these two lines:
```js
    { path: 'customer/:customersID', component: Customer },
    { path: 'customer(/:customerId)', component: Customer },
```
The route below that will serve the exact same purpose.

**Comment by thefirstave** [comment]
Hi, 

no, I just provided all the possibilities I used. I only use one of the options.

**Comment by taion** [comment]
You're getting that because you're not using an absolute path to your JS bundle.

**Comment by thefirstave** [comment]
@taion 

How can I do that?

Sorry but I just started with react-router and webpack.

**Comment by taion** [comment]
In your `<script>` tag, do `src="/bundle.js"` instead of `src="bundle.js"`.

**Comment by thefirstave** [comment]
@taion 

thx.
