### ISSUE TITLE
The tutorial...

### ISSUE THREAD

**Issue by kareltucek** [reactjs/react-router#3423]
I would really appreciate if a generally accepted form of tutorials was some text form. Plain text usually works. Can be printed. Can be read on anything that supports plain text. And one does not have to solve problems of tools he does not understand:

[err.txt](https://github.com/reactjs/react-router/files/245314/err.txt)

**Comment by timdorr** [comment]
See #2933 or submit a PR on https://github.com/reactjs/react-router-tutorial/
