### ISSUE TITLE
History warning

### ISSUE THREAD

**Issue by pavelagapov** [reactjs/react-router#3425]
## Version
2.4.0

I get warning from history with current react-router:

"Warning: Automatically setting basename using <base href> is deprecated and will be removed in the next major release. The semantics of <base href> are subtly different from basename. Please pass the basename explicitly in the options to createHistory."

Looks like history dependency of react-router was updated, but react-router does not support new changes.

**Comment by taion** [comment]
Setting `basename` using `<base>` is in fact deprecated. If you need a basename, create a custom history and pass in `basename`.
