### ISSUE TITLE
Components imported with an alias will result in empty props.children

### ISSUE THREAD

**Issue by Thinkscape** [reactjs/react-router#3426]
## Version
react@15.0.2
react-router@2.4.0
history@2.1.1
babel-loader@6.2.4
babel-preset-react@6.5.0
babel-preset-es2015@6.6.0
babel-plugin-add-module-exports@0.1.4

## Test Case
Consider the following files:
````jsx
// About.jsx
import React from "react";
export default class About extends React.Component {
  render(){ return <h1>About page here</h1>; }
}
````

````jsx
// Layout.jsx
import React from "react";
export default class Layout extends React.Component {
  render(){ return <div>{this.props.children}</div>; }
}
````
````jsx
// app.jsx
import React from "react";
import ReactDOM from "react-dom";
import { Router, Route, IndexRoute, hashHistory} from "react-router";

import Layout from "./Layout";
import { About as AboutPage } from './About';

ReactDOM.render(
  <Router history={hashHistory}>
    <Route path="/" component={Layout}>
      <Route path="about" component={AboutPage}></Route>
    </Route>
  </Router>
  , document.body
);
````
````json
// .babelrc
{
  "presets": ["react", "es2015"],
  "plugins": ["react-html-attrs", "transform-class-properties", "transform-decorators-legacy"]
}
````
## Steps to reproduce
Import the page component with an alias.
```jsx
import { About as AboutPage } from './About';
<Route path="about" component={AboutPage}></Route>
````
## Expected Behavior
The page renders when path matches.

## Actual Behavior

 * The page is blank
 * `this.props.children === null`
 * `this.props.route.childRoutes[0].component === undefined`

![image](https://cloud.githubusercontent.com/assets/270528/14984023/e531fb9a-1140-11e6-9158-8ac0fe939d23.png)

**Comment by taion** [comment]
If you're doing `export default About`, you can't do `import { About as AboutPage } from './about'`. You could do `import AboutPage from './about'`.
