### ISSUE TITLE
Any solution to Serverside render in express.js

### ISSUE THREAD

**Issue by yoyeung** [reactjs/react-router#3437]
I cannot find any solution with express.js
i am using react-router 2.0.
i find it there will have listenBeforeLeavingRoute error.
But i don't how to implement the solution when i using express.js

**Comment by yoyeung** [comment]
[My project.](https://github.com/yoyeung/server-react)

**Comment by taion** [comment]
Follow the serving rendering guide: https://github.com/reactjs/react-router/blob/master/docs/guides/ServerRendering.md.

**Comment by yoyeung** [comment]
I follow the guide, but the problem is when I start the server using Web dev server it throw error. 
I search in the tutorial said need to add a library in externals setting. But I did not success on it. 
If not solution for express.js I will back to use v1.x

**Comment by yoyeung** [comment]
Finally i find a solution to fix the problem.
in the server.js add "react/addons" to replace "react"
But this one only working in 0.14.
Cannot work on v15.0 because "addons" no longer available.

**Comment by timdorr** [comment]
They have been isolated into separate packages:

react-addons-clone-with-props - v0.14.8 - This package provides the React cloneWithProps add-on.
react-addons-create-fragment - v15.0.2 - This package provides the React createFragment add-on.
react-addons-css-transition-group - v15.0.2 - This package provides the React CSSTransitionGroup add-on.
react-addons-linked-state-mixin - v15.0.2 - This package provides the React LinkedStateMixin add-on.
react-addons-perf - v15.0.2 - This package provides the React Perf add-on.
react-addons-pure-render-mixin - v15.0.2 - This package provides the React PureRenderMixin add-on.
react-addons-shallow-compare - v15.0.2 - This package provides the React shallowCompare add-on.
react-addons-test-utils - v15.0.2 - This package provides the React TestUtils add-on.
react-addons-transition-group - v15.0.2 - This package provides the React TransitionGroup add-on.
react-addons-update - v15.0.2 - This package provides the React updates add-on.

**Comment by yoyeung** [comment]
I know they split it into a small package. 
When I working on server rendering. 
I am using 
import React from 'react/addons'
For import react. 
But I don't know any solution for v15.

**Comment by timdorr** [comment]
Just `import React from 'react'`. You don't need the addons.

**Comment by yoyeung** [comment]
@0@ ur right. Sorry about that. May be my match route function have problem.

**Comment by Nishchit14** [comment]
Node doesn't support `import`

How to handle it ?

**Comment by timdorr** [comment]
https://babeljs.io/docs/usage/require/
