### ISSUE TITLE
error with typings

### ISSUE THREAD

**Issue by cramhead** [reactjs/react-router#3438]
## Version
2.0.0

## Steps to reproduce

1. Clone https://github.com/rangle/typescript-react-redux-starter and get it running, i.e. ```npm install; npm run dev```
2. run  ```node_modules/typings/dest/bin.js install react-router --ambient --save```
3. run ```npm run dev```

## Expected Behavior
Typings throw no errors
## Actual Behavior
Typings compilation throw three errors:
```
ERROR in /Projects/REACT/rangle/typescript-react-redux-starter/typings/browser/ambient/react-router/index.d.ts
(32,22): error TS2305: Module 'HistoryModule' has no exported member 'LocationDescriptor'.

ERROR in /Projects/REACT/rangle/typescript-react-redux-starter/typings/browser/ambient/react-router/index.d.ts
(111,30): error TS2305: Module 'HistoryModule' has no exported member 'LocationDescriptor'.

ERROR in /Projects/REACT/rangle/typescript-react-redux-starter/typings/browser/ambient/react-router/index.d.ts
(211,31): error TS2305: Module 'HistoryModule' has no exported member 'LocationDescriptor'.
```

**Comment by taion** [comment]
We don't maintain those typings. Please file relevant issues against the repos that actually do contain said typings.

Per https://github.com/reactjs/react-router/issues/3193, we're considering adding Flow typings, though.
