### ISSUE TITLE
Swap out base href

### ISSUE THREAD

**Issue by ev1stensberg** [reactjs/react-router#3447]
Just wanted to remind you to update the examples when the next release is out. 

![skjermbilde 2016-05-10 kl 02 58 34](https://cloud.githubusercontent.com/assets/16735925/15132550/2aea49ac-165b-11e6-9862-43deb2276e16.png)

**Comment by ev1stensberg** [comment]
@taion close this once read :tada:

**Comment by taion** [comment]
Nah this is a real issue, we should fix this separately from the 3.0 release.
