### ISSUE TITLE
Add Component to <Redirect>

### ISSUE THREAD

**Issue by ev1stensberg** [reactjs/react-router#3449]
In order to have a even more interactive website, would it be convenient to let users add `component` to `<Redirect>`? This would allow them to have a mid-component on redirections, like a loading bar or notification that the user is being redirected. 

Sample Code: 

```
<Route path="/" component={App}>
      <Route path="user/:userID" component={User}>
        <Route path="tasks/:taskID" component={Task} />
        <Redirect from="todos/:taskID" to="tasks/:taskID" component={Load} />
      </Route>
    </Route>
```

**Comment by taion** [comment]
We don't actually render at all on redirects – the redirect happens entirely in the router.

**Comment by ev1stensberg** [comment]
Hypothetically: Could we leave  `component` as optional and render the redirect if `component` is supplied to it?

**Comment by taion** [comment]
No, we don't render anything for redirects – the transition manager `listen` callback (normally) won't fire at all until the redirect is fully resolved.

We should have something better in place for async handling in routes, but it's not really redirect-specific. A redirect is just a route that redirects you in `onEnter`.
