### ISSUE TITLE
activeClassName not working as expected

### ISSUE THREAD

**Issue by theskabeater** [reactjs/react-router#3451]
I'm having issues with nested routes not applying the active class when rendered. Am I missing something? I'm using React Router 2.3.0 w/ React Router Redux 4.0.2

```
// Routes
export default function Root(props) {
  return (
    <Provider store={store}>
      <Router history={history}>
        <Route path="/" component={App}>
          <IndexRoute component={Home} />
          <Route path="/public-gallery" component={PublicGallery} />
          <Route path="/public-gallery/:slug" component={PublicGallery} />         
        </Route>
      </Router>
    </Provider>
  );
}
```
```
// Nav link
<Link to="/public-gallery" activeClassName="active">Public Gallery</Link>
````

The active class is being applied to _/public-gallery_ but not to _/public-gallery/:slug_

**Comment by taion** [comment]
https://github.com/reactjs/react-router/blob/master/docs/Troubleshooting.md#parent-path-does-not-show-as-active
