### ISSUE TITLE
Disabled Link

### ISSUE THREAD

**Issue by vferko** [reactjs/react-router#3454]
I wanted to comment on #1082 but it's locked.

Using 

```
  <Link
    onClick={(e) => !canHasLink ? e.preventDefault() : true}
    style={!canHasLink ? {pointerEvents: 'none'} : {}}
  > IDontThinkSo </Link>
```

still lets the user see the source code and manually enter the target location into address bar.
Not using the changed style even let's the user right-click the link and open the target in new tab.

If I really want to disable the Link, I need to replace the Link with a flat text likeso, (which can, of course, be wrapped in a component...)

```
{canHasLink // not so sexy
  ? <Link>YouShallPass</Link>
  : 'YouShallNopePass'}
```

But all those workarounds are not that elegant... Can we have proper Disabled links that mask any evidences of it being a link but still using the same component for the sake of styles (i.e. remove target url from disabled link)?

**Comment by taion** [comment]
There is no support for `disabled` on `<a>`. As we're trying to match the API of an anchor as closely as possible, doing this is out-of-scope.

**Comment by vferko** [comment]
Right, of course, that's understandable, but what I had on mind actually is that by using `disabled` on a `<Link/>` the rendered `<a>` would be without a target url, ie. effectively disabled.

**Comment by shirbr510** [comment]
even though this issue is 2 and a half years old,
I believe that this is quite a common behavior that most users would like to have.
according to the way that `<a>` works, I do think that @ackvf 's solution is the best to fit everybody's interests (and support the intended way of disabling an `<a>`
