### ISSUE TITLE
had better synchronize eact-router.d.ts to react-router

### ISSUE THREAD

**Issue by iktakahiro** [reactjs/react-router#3455]
I assumed that typings file for react-router was managed by a official repository.

- https://github.com/andrew-w-ross/typings-react-router

> // Type definitions for react-router v2.0.0

react-router.d.ts is following older version.

react-router is one of the measure packages, TypeScript also. Especially, The progress of react-router is remarkable. I'm worried that TypeScript users will be divided.

Do you have any plans?

**Comment by taion** [comment]
Why not use DefinitelyTyped?

I don't believe any of the maintainers on this project use TypeScript, so just putting an `index.d.ts` is not going to give reasonable guarantees that the typings will stay up-to-date.

See also https://github.com/reactjs/react-router/issues/3193.

**Comment by iktakahiro** [comment]
@taion 

Thank you for your response.

Why not use DefinitelyTyped?

Below is a that reason:

> DEPRECATED: TSD is deprecated, please use Typings and see this issue for more information.

https://github.com/DefinitelyTyped/tsd/blob/master/README.md#tsd

but I found react-router.d.ts on DefinitelyTyped.

> See also #3193.

Thanks. I'll read.
