### ISSUE TITLE
createRoutes(routes): TypeError: Cannot read property 'createRouteFromReactElement' of undefined

### ISSUE THREAD

**Issue by MoOx** [reactjs/react-router#3457]
I am trying (for [phenomic](http://phenomic.io/)) to generates a list of routes from JSX Route(s).

So I want to loop on Route(s) to build all possibles routes (I have static data, so all parameters like :stuff are known).

I just took a look to the docs and thing "createRoutes" might help me so I tried this:

```js
import React from "react"
import Route from "react-router"
import { createRoutes } from "react-router"
const Noop = () => {
  // return <div />
}

const routes = (
  <Route component={ Noop }>
    <Route path="/author/:author" component={ Noop } />
    <Route path="/blog" component={ Noop }>
      <Route path="/category/:category" component={ Noop } />
      <Route path="/tag/:tag" component={ Noop } />
    </Route>
    <Route path="*" component={ Noop } />
  </Route>
)

console.log(createRoutes(routes))
```

And I am getting this issue

```
TypeError: Cannot read property 'createRouteFromReactElement' of undefined
    .../node_modules/react-router/lib/RouteUtils.js:87:23
    forEachSingleChild (.../node_modules/react/lib/ReactChildren.js:52:8)
    traverseAllChildrenImpl (.../node_modules/react/lib/traverseAllChildren.js:67:5)
    traverseAllChildren (.../node_modules/react/lib/traverseAllChildren.js:155:10)
    Object.forEachChildren [as forEach] (.../node_modules/react/lib/ReactChildren.js:70:3)
    createRoutesFromReactChildren (.../node_modules/react-router/lib/RouteUtils.js:84:28)
    createRoutes (.../node_modules/react-router/lib/RouteUtils.js:106:14)
    exports.default (.../src/static/routes-to-urls/index.js:12:45)
    Test.fn (index.js:60:16)
```

Not sure if createRoutes is for my need, but an error thrown like this does not seems to be intentional.

**Comment by taion** [comment]
This is not the right import:

```js
import Route from "react-router"
```

(BTW see also https://github.com/reactjs/react-router/blob/master/docs/guides/MinimizingBundleSize.md)

**Comment by MoOx** [comment]
Ouups. Indeed it works correctly now. Thanks and sorry for the noize.

**Comment by oojacoboo** [comment]
Hey @MoOx did you have luck going this route?  I'm trying to do the same thing pretty much, passing the JSX Routes, via createRoutes() to the react-router match() function.  However, for some reason it won't match on any routes.  If I pass in a custom route object, I don't have this same issue.

Would be appreciative if you have any insight there.  Thanks!

**Comment by MoOx** [comment]
@oojacoboo sorry I didn't used that to match routes, but to build an array if possible routes. My work is here https://github.com/MoOx/phenomic/blob/bab74b8647ccfc20491f381303fdc340ae27ee24/src/static/routes-to-urls/index.js

**Comment by oojacoboo** [comment]
Thanks @MoOx
