### ISSUE TITLE
Incorrect work with folder path in <base> and trailing slash

### ISSUE THREAD

**Issue by IDVsbruck** [reactjs/react-router#3458]
Version: 2.2.0 - 2.4.0

If I want to use relatives paths in links I set href of **base** tag as **myproject.com/console/**' (relative links don't work without trailing slash in URL). And my route config looks like that:
```
var history = router.useRouterHistory(require('history').createHistory)();
var routeConfig = [
    {path: '/',
        component: require('app'),
        indexRoute: {component: require('app_default')},
        childRoutes: [
            ...
            {path: '/*', component: require('app_notfound')}
        ]
    }
];
require('react-dom').render(require('react')
        .createElement(router.Router, {routes: routeConfig, history: history}), document.body);
```
If I set URL as **myproject.com/console/** it works correct. But without trailing slash I get context for 'app_notfound' component.
I added onEnter handler for path '/*' like that:
````
function test(nextState, replace, callback) {
    if (nextState.location.pathname == '/console') {
        replace('/');
    }
    callback();
}
````
It works but new URL in address bar has 2 trailing slashes ))) - 'myproject.com/console//'.

Another trouble: I add in useRouteHistory **basename** parameter:
```
    var history = router.useRouterHistory(require('history').createHistory)({
        basename: document.baseURI.replace(/\/$/, '')
    });
```
And after this entered URL **myproject.com/console** works correct (but shows in location bar with trailing slash), but refreshing this URL or entering **myproject.com/console/** allows to 'notfound' page content.

I tried also to set **basename** as **/console** and to handle root route **/console/**. It works with root paths (with and w/o trailing slash) but child routes work incorrect.

Now I changed tag **base** as **myproject.com/**, add to each relative link at start 'console/', set parameter **basename** as **/console** and all routes work correctly. But this behavior of Router is puzzling. I also admit that I am something missing or doing wrong.

**Comment by taion** [comment]
Please provide a runnable repro or example showing this.

**Comment by timdorr** [comment]
Without a reproducible test case, we can triage this. I'll re-open if one can be provided.
