### ISSUE TITLE
React-router not working when after update from 1.0.3 to 2.4.0

### ISSUE THREAD

**Issue by thnhat51202574** [reactjs/react-router#3459]
I wanted to build a my react/react-router/flux application and of course,I used React-router. This is my problem.Before i updated react-router to version 2.4.0, the old version was 1.0.3, It worked successful.

But when I updated it to version 2.4.0(I want to use router in reactcontext).I had proplem, it wasn't work.

Here is myproblem:

```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).warning @ vendor.bundle.js:25359
vendor.bundle.js:24916 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
```
Here is my code: server.js:

```
app.use(function(req, res) {
Router.match({ routes: routes.default, location: req.url }, function(err, redirectLocation, renderProps) {
if (err) {
  res.status(500).send(err.message)
} else if (redirectLocation) {
  res.status(302).redirect(redirectLocation.pathname + redirectLocation.search)
} else if (renderProps) {
  var html = ReactDOM.renderToString(React.createElement(Router.RouterContext, renderProps));
  var page = swig.renderFile('views/admin/index.html', { html: html });
  res.status(200).send(page);
} else {
  res.status(404).send('Page Not Found')
}
});});
```
Main.js

```
import routers from './router';
let history = createBrowserHistory();
ReactDOM.render(<Router history={history}>{routers}</Router>, document.getElementById('app'));
router.js

<Route component={App}>
  <Route path='/' component={Homepage} />
</Route>
```
I didn't know why it had problem. Please help. Thanks a lot!

I also posted it in [stackoverflow](http://stackoverflow.com/questions/37214498/react-router-not-working-when-after-update-from-1-0-3-to-2-4-0)

**Comment by taion** [comment]
You're probably importing `Router` incorrectly. It's now a named import along with everything else. That or importing `Route` incorrectly.

**Comment by thnhat51202574** [comment]
Can you explain more detail? I don't what you mean. 
I import : 
`import {Route} from 'react-router';` in router.js
`import Router from 'react-router';` in main.js and server.js
Can you show me where i did it wrong!

**Comment by taion** [comment]
You should be doing `import { Router } from 'react-router'`.

**Comment by thnhat51202574** [comment]
I try `import { Router } from 'react-router'`.
But it has problem `Router.match is not a function` in server.js.
So now, we can't use Router.match ?

**Comment by taion** [comment]
No, you import that as `import { match } from 'react-router'`. They're all named exports. Check the docs.

**Comment by thnhat51202574** [comment]
It's worked. Many thanks.
