### ISSUE TITLE
Mobile Safari: SecurityError: DOM Exception 18 after 100 times of url update

### ISSUE THREAD

**Issue by amarchen** [reactjs/react-router#3462]
Mobile Safari has a known bug "by design" issue that does not update url over 100 times.
See https://forums.developer.apple.com/thread/36650 and http://jdurand.com/blog/2016/05/03/ember-history-pushstate-dom-exception-18/

For reproducing e.g. make url update on a slider move, then it's easy to generate 100 url updates by moving slider on the iPhone.

Therefore if you update url with pushState or replaceState, after a 100 of updates you'll be only getting security exception during the url update and in my case it also breaks further action processing (but that might be specific to my app).

Ember folks solved it by reloading the browser window http://jdurand.com/blog/2016/05/03/ember-history-pushstate-dom-exception-18/

P.S.
Sorry for not filling the proper bug template. I am not using the react-router directly (but via the react-router-redux, case is rather clear, confirmed by Embed.JS folks and by Apple folks, so I guess it's better to fill the bug report in a not the best way rather than not to report at all - it took several hours from me to figure the reason for these DOM Exception.

**Comment by taion** [comment]
Tracking this on https://github.com/mjackson/history/issues/291.
