### ISSUE TITLE
setRouteLeaveHook should undo last push to history when user returns false in callback

### ISSUE THREAD

**Issue by deser** [reactjs/react-router#3464]
Let's say I want to prevent going to next location until something asynchronous is executed and then I want to go to the next location: 
``` 
let unlistenLeave = router.setRouteLeaveHook(this.props.route, nextLocation => {
            this.onLeave().then(() => {
                unlistenLeave();
                router.push(nextLocation);
            }).catch(() => {
                unlistenLeave();
                router.push(nextLocation);
            });

            return false;
        });
```

In this case react-router will preserve previous push (which caused leave hook) and will add the same location to history. 

I presume that problem could be here: https://monosnap.com/file/7n5n72TAp7HKHSRTFb3y3UtpbQIEEV 

Every time `createHistory` generates new key and here https://monosnap.com/file/i9k9o3AJWkzZETeMyVBOZlKCa9wK6y locations couldn't be the same.

Let's go deeper and see what `locationsAreEqual` does:
```
function locationsAreEqual(a, b) {
  return a.pathname === b.pathname && a.search === b.search &&
  //a.action === b.action && // Different action !== location change.
  a.key === b.key && _deepEqual2['default'](a.state, b.state);
}
```

So in my case only `key` differs

**Comment by deser** [comment]
I

**Comment by taion** [comment]
That's not true. `confirmTransitionTo` blocks the transition whenever possible, if initiated from JS: https://github.com/mjackson/history/blob/v2.x/modules/createHistory.js#L115

**Comment by deser** [comment]
Please reconsider my bug one more time. All what I see is that `window.history.length` is changed twice: one time before leave hook and second inside leave hook. Please try to repeat it by yourself or say me how I can proof it to you
