### ISSUE TITLE
How to do add(not replace the exist one) component when I route to a child path?

### ISSUE THREAD

**Issue by wufeng87** [reactjs/react-router#3469]
Consider the example "master-detail" in the react-router example directory, how can I do like this:
When I select a contact in the left list, I want to add a new contact in the right container, so I can see lots of contacts in the right container.

And in the real world, the right container could be a Tabs component.

Best regards. sorry for my bad English.

**Comment by taion** [comment]
You'd handle this outside the router in something like Flux, or else update location state, or use higher-level component state. The router is not really the right level abstraction to handle this.
