### ISSUE TITLE
Distinguish between local and remote history frames in router.goBack()

### ISSUE THREAD

**Issue by s-ol** [reactjs/react-router#3470]
This is sort of a continuation of #408, which was resolved before 1.0 but then basically un-resolved again later.

The core problem case is the following: Users visiting a page in an application might come there either from inside the application or from an external communication channel, possibly also a web app, that might live in the same browser history. When using `browserHistory` one is unable to distinguish between the two, so that a button triggering `router.goBack()` may lead outside the app, which is unwanted behaviour in many cases.

Ideally, there would be a `router.peek()` or `router.canGoBack()` etc. that can tell whether a consecutive `router.goBack()` would trigger a page unload or a router transition that can be used for example to hide "go back" navigation from the end user.

A partial solution would be to at least let the developer decide whether `router.goBack` should lead outside the domain (optional boolean argument indicating whether it should be left or trigger no action, boolean return value indicating whether a transition was triggered or not).

**Comment by taion** [comment]
Please follow up on https://github.com/mjackson/history/issues/26 and related issues on history – these methods are proxied from the underlying history, and the routing logic does not manage the navigation.
