### ISSUE TITLE
`router.isActive` do not ignore case

### ISSUE THREAD

**Issue by snadn** [reactjs/react-router#3472]
path: '/testActive'

`router.isActive('testActive')` return true.
`router.isActive('testactive')` return false.

**Comment by timdorr** [comment]
This is correct. RFC 3986 states that other than the host name and scheme of the URL, it is case sensitive.

**Comment by snadn** [comment]
@timdorr i konw URL is case sensitive,but the path of react-router set in routes.js not.

so ’testActive‘ and ’testactive‘ can be match to ’path: testactive‘.

when i need use router.isActive('testactive') to active nav. i failed with url 'testActive'.
