### ISSUE TITLE
onEnter hook triggered twice

### ISSUE THREAD

**Issue by nvartolomei** [reactjs/react-router#3473]
## Version
2.4.0

## Test Case
http://jsbin.com/kugodumaqe/1/edit?js,console

## Steps to reproduce

1. Navigate to http://output.jsbin.com/kugodumaqe/1#/app/?_k=loky8t

## Expected Behavior

See `app enter` logged to console once

## Actual Behavior

`app enter` is logged to console twice

**Comment by taion** [comment]
Same as https://github.com/reactjs/react-router/issues/3220
