### ISSUE TITLE
about router rules

### ISSUE THREAD

**Issue by enjoydiy** [reactjs/react-router#3475]
Hi,

I am using nginx server. It can not work well. It shows 404 error. I try any ways. But fail.
I just want to ask if there is other way to visit.

For example,

domain: abc.com
router: /getbooks

visit url: http://abc.com/index.html#/getbooks

**Comment by timdorr** [comment]
You need to configure your server: https://github.com/reactjs/react-router/blob/master/docs/guides/Histories.md#configuring-your-server

**Comment by enjoydiy** [comment]
But this can not solve my problem.
my index file:
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <title></title>

    <link rel="stylesheet" href="css/vendor.bundle.css">
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/app.css">
</head>
<body>

    <div id="app"></div>

    <script src="js/vendor.bundle.js"></script>
    <script src="js/app.bundle.js"></script>
</body>
</html>`

There are some css/js files to be loaded.
When visiting the index.html, no issue.
When visiting some router such as http://abc.com/getbooks/, the chrome will find the js file from http://abc.com/getbooks/js/app.bundle.js, however, the actual url is http://abc.com/getbooks/app.bundle.js.

Can the rewrite rule solve the issue?
