### ISSUE TITLE
How can I force componnent to rerender when url changed?

### ISSUE THREAD

**Issue by twoeo** [reactjs/react-router#3479]
Have a route:
```
<Router>
	<Route path="/create" component={Editor} />
	<Route path="/edit/:id" component={Editor} />
</Router>
```

**Expect**
/create to create a new article
/edit/:id to edit a exist one

Hope the component Editor rerender when I jump to /create from /edit/123

**Problem**
When I was at /edit/123 , and jump to /create, the page not rerender.

**Comment by timdorr** [comment]
`componentWillReceiveProps` or other React lifecycle methods.

**Comment by tplee923** [comment]
In the Route component, specify a random key.

`<Route path={YOURPATH} render={(props) => <YourComp {...props} key={randomGen()}/>} />`

when react see a different key, they will trigger rerender.
