### ISSUE TITLE
Bug report for redirects from broken child components.

### ISSUE THREAD

**Issue by dedan** [reactjs/react-router#3487]
## Version
2.0.0

## Test Case
https://github.com/dedan/router-redirect-debugging

## Steps to reproduce
Clone the above repo and follow the instructions in the README.

## Expected Behavior

The redirect in `componentWillMount` of the `Container` will kick in before the `BrokenChildComponent` gets rendered and therefore the redirect will not only update the URL, but will also correctly display the `HappyChildComponent`.

## Actual Behavior

The URL gets updated to `http://localhost:8100/#/happy`, because of the redirect in the container. However the `HappyChildComponent` won't get displayed.

**Comment by taion** [comment]
Use `onEnter` for redirects, not component lifecycle hooks.

**Comment by dedan** [comment]
Thank you very much for the fast answer.
