### ISSUE TITLE
setRouteLeaveHook not documented in API.md

### ISSUE THREAD

**Issue by nvartolomei** [reactjs/react-router#3488]
`setRouteLeaveHook` is found here [docs/guides/ConfirmingNavigation](https://github.com/reactjs/react-router/blob/master/docs/guides/ConfirmingNavigation.md)

But I couldn't found this method documented in [docs/API](https://github.com/reactjs/react-router/blob/master/docs/API.md).

Create a PR?

**Comment by timdorr** [comment]
Yes, please. And it's actually listed incorrectly in the Glossary too.
