### ISSUE TITLE
Not found route configuration

### ISSUE THREAD

**Issue by bensampaio** [reactjs/react-router#3491]
I would like to be able to specify the not found route in this way:

```js
const routes = {
  component: App,
  childRoutes: [],
  indexRoute: {
    component: Home
  },
  notFoundRoute: {
    component: NotFound,
    path: '*'
  },
  path: '/'
}
```

The relevant part in the example above is the `notFoundRoute` property. With this property I wouldn't need to make sure this route always need to stay in the end of the childRoutes array. I found some threads on StackOverflow with a `NotFoundRoute` component but from the documentation I couldn't understand if that still exists and if there is an equivalent for it in the object config structure.

What do you think? Thank you!

**Comment by taion** [comment]
We discussed this on https://github.com/reactjs/react-router/issues/3212 and decided to not do this – it's just not an interesting enough special case of the current API, which handles things quite well enough.
