### ISSUE TITLE
react-router match() can't match any routes

### ISSUE THREAD

**Issue by markstock7** [reactjs/react-router#3493]
i am doing the  server rending using react-router,but i got some issue, the following is my code
match function can't match any route, so the renderProps is always null

<img width="633" alt="screen shot 2016-05-23 at 9 19 27 pm" src="https://cloud.githubusercontent.com/assets/9659974/15472108/09f44de8-212c-11e6-8353-35b151ec3458.png">
<img width="975" alt="screen shot 2016-05-23 at 9 19 40 pm" src="https://cloud.githubusercontent.com/assets/9659974/15472109/0a04ee14-212c-11e6-99d8-5502afdf1eb7.png">

**Comment by Nishchit14** [comment]
did you solved this ?
