### ISSUE TITLE
Route with params not found!

### ISSUE THREAD

**Issue by rsflow** [reactjs/react-router#3496]
Hi,

I keep having this issue with url params in routes. The normal route works ok but the one with the params either loads the `Not Found` route or doesn't load the page at all with a `404 Error`. 
The route is like this `<Route component={Users} path="users(/:userID)" />`. 
Does react-router have any issues with any specific `webpack configurations` or `middlewares` because other than those the project is really simple?

Thank You!

**Comment by taion** [comment]
Check the examples – we show this pattern working successfully in multiple places.

**Comment by rsflow** [comment]
@taion I copy pasted the examples in my react project ... but there is a configuration in the webpack file that maybe doesn't make the url with params to work. Please leave the issue open for a day maybe there is someone who had the same issue who can help me.

**Comment by rsflow** [comment]
If anyone is having this problem the solution is to put 
`output: {
    publicPath: '/'
  }` in your webpack config.
