### ISSUE TITLE
if I go to nested route directly, error ReactJS

### ISSUE THREAD

**Issue by Kenzku** [reactjs/react-router#3497]
Hej, 

I can go to a nested route by starting from the entry point e.g. `localhost/`, step by step to `http://localhost:8080/huge-apps/course/0/assignments`, but if I copy this link and paste to browser, it will give me error. 

`app.js:1 Uncaught SyntaxError: Unexpected token <`  the page is not render at all, with this info it is really hard to tell where goes wrong.

I was wondering if it is caused by webpack configuration, as before I had the problem with `require.ensure([], (**require**) 0 => {})` as the second require in parameter caused problems.

Any idea?

**Comment by taion** [comment]
You probably need to configure your server appropriately. See the guides.

**Comment by Kenzku** [comment]
Hej, can you please be more specify, like which guides? I use express server, do you mean the server route?

**Comment by rizkiandrianto** [comment]
Hey @Kenzku what did you mean with `ok, never mind, it was the . in the index.html page where it fetches the entry point causing the problem.` ?
How did you get it works?

**Comment by shoesandsocks** [comment]
since this page comes up near the top of searches for “react router redux Uncaught SyntaxError: Unexpected token <”, I'll add my 2 cents. Like @rizkiandrianto, my problem was in the script tag. The tutorial I was following used `src='./bundle.js'` which was fine until new routes were introduced. Dropping the `.` and going with `src='/bundle.js'` was the solution.

**Comment by rikvanderkemp** [comment]
> The tutorial I was following used src='./bundle.js' which was fine until new routes were introduced. Dropping the . and going with src='/bundle.js' was the solution.

Thanks @shoesandsocks this solved my hours of hunting down the same issue!

**Comment by wuzhuzhu** [comment]
add '/' before importing bundled js in  static html file solved my problem , thanks!

**Comment by GustavoHGS** [comment]
@shoesandsocks You're a life saver man!!

**Comment by OlegStotsky** [comment]
@shoesandsocks this has solved it for me.

**Comment by Kenzku** [comment]
Hej @rizkiandrianto yes, in the entry html or js, whatever you use as an entry point to load the rest of the files. like what @shoesandsocks said. Sorry, I have been hibernating for 2 years in bed.
