### ISSUE TITLE
Best practice to redirect within action creator?

### ISSUE THREAD

**Issue by olalonde** [reactjs/react-router#3498]
There seems to be two ways to redirect from an action creator (react-redux):

1) Use withRouter() on component which calls the action creator and pass `props.router` to the action creator (e.g. `dispatch(login(username, password, this.props.router))` and `router.push('/success')` inside my action creator)

2) `import { browserHistory } from 'react-router'` inside the action creator file and `browserHistory.push('/success')` as mentioned here: https://github.com/reactjs/react-router/blob/master/docs/guides/NavigatingOutsideOfComponents.md

I was wondering which one would be preferable.

**Comment by timdorr** [comment]
You're calling the exact same function in both cases. But since you might use your action outside of the React context, you should probably use browserHistory.

**Comment by murashki** [comment]
Guys, what about 4.0.0 version?

**Comment by malimichael** [comment]
How do we do this in v4?

**Comment by pshrmn** [comment]
Starting with the beta, the answer will be the same. If you need to navigate outside of React, you can create your own history instance and import it throughout your project.

**Comment by wjin0352** [comment]
How do we do this in v4???

**Comment by thekarel** [comment]
@wjin0352 

The simplest working example:

`history.js`:

```
import createHistory from 'history/createHashHistory'

export default createHistory()
```

`actions.js`:

```
import history from './history'

history.push('/abc')
```

**Comment by Aprillion** [comment]
@thekarel unfortunately, react-router-dom does not re-render the component that I pass to a Route when using history this way, but it works (i.e. re-renders the component) when I pass `this.context.router.history.push` into my action creator...

is that a general problem or only happening in my use case => should I create a simplified test case?

**Comment by m-mik** [comment]
@Aprillion That's the expected behavior. Take a look at: https://github.com/ReactTraining/react-router/issues/4059#issuecomment-254437084

> 1. Creating a new browserHistory won't work because BrowserRouter creates its own history instance, and listens for changes on that. So a different instance will change the url but not update the BrowserRouter.


> 2. browserHistory is not exposed by react-router in v4, only in v2.

> If you want the full history object you can also grab that off context like router.
> this.context.history.push('/path')

**Comment by Aprillion** [comment]
@m-mik I understand that 2 instances of `browserHistory` would not communicate, but it was definitely NOT my expectation that creating single instance directly from `history` module, importing to multiple files, using it as `<Router history={myHistory}` and then running `myHistory.push` in another file somehow does not re-render the routed component

**Comment by m-mik** [comment]
Are you sure you're using Router, and not BrowserRouter when passing the history instance? Perhaps, you're importing BrowserRouter as Router?

```
import { BrowserRouter as Router } from 'react-router-dom'
...
<Router history={history}> // this won't work, BrowserHistory does not accept history property
```

---

**history.js**
```
import createHistory from 'history/createBrowserHistory'

export default createHistory()
```

**Root.jsx**
```
import { Router } from 'react-router-dom'
import history from './history'
...
<Router history={history}>
 <Route path="/test" component={Test}/>
</Router>
```

**another_file.js**
```
import history from './history' 

history.push('/test') // this should change the url and re-render Test component
```

**Comment by Aprillion** [comment]
that was probably it.. I didn't get any proptypes error, so I forgot to check.. thanks @m-mik for the tip, I will try again!

**Comment by rishabh09** [comment]
@m-mik i am getting error history.push is not a function from my action creator.

**Comment by vvinhas** [comment]
Hey guys, is history navigation inside actions considered a good practice? I try to avoid it at all costs but I'm in a situation where this approach would be easier to implement.

**Comment by Aprillion** [comment]
@vvinhas I probably don't understand the question, for me history navigation can ONLY happen as an action.

e.g. `<Link>`is just a component that wraps the onClick event handler creating a history action (push). so a custom history action would be similar but using a custom component instead of a library-provided one. 

I can't imagine when it would make sense to navigate back inside render, constructor, redux reducer, selector or something else, only inside an event handler => action creator.

But if you have a different concrete example..?

**Comment by vvinhas** [comment]
Hey @Aprillion! Thanks for your reply!

My case is an auto redirect, based on a response from a Http Request. I know it's easier to put `history.push` into my `thunk`, but generally, I let my components decide when to redirect the user based on Redux State, wrapping `withRouter` around it and using the `history` prop.

I'm actually asking it honestly, I don't know if it's a common practice to put `history.push` inside a thunk.

**Comment by Aprillion** [comment]
Imagine new team members arriving and copy&pasting some pattern to other places in the code. Then 6 months later you get a bug report that some redirect is incorrect. Will you be able to debug the issue? If yes, then it's a good pattern for you :)

Not speaking for the whole community though, just how I would think about it.

**Comment by thekarel** [comment]
> I let my components decide when to redirect the user based on Redux State

I would not recommend that practice. Components are either "dumb" and simply render a view based on data or "higher level" i.e. they connect the store's data to the dumb components. Other than that, your business logic should live in the store and side-effects handled in actions.

**Comment by EzeRangel** [comment]
Why not just make an static method? `Router.push('/admin/')`
