### ISSUE TITLE
export matchPattern utility for end users

### ISSUE THREAD

**Issue by andrewmclagan** [reactjs/react-router#3501]
We should be exporting the `matchPattern` utility for end users:

**Use case**

Matching routes within authorization / onEnter functions:

````
function canAccessRoute(user, currentRoute) {
    const deny = ['/admin/*', '/statistics/*','/secret/*'];
  
    if (! user.isAdmin()) {
        return deny.reduce(route => !! matchPattern(route, currentRoute));
    }
    return true;
}
````

pseudo code obviously...

**Comment by taion** [comment]
This is intentionally not exported – we want to keep it as an implementation detail, as we may well change this to be something configurable per-route or whatever.

**Comment by andrewmclagan** [comment]
So in that case is there a suggested approach to matching routes in external functions?

**Comment by timdorr** [comment]
The better way will be via #3098 or something like it.
