### ISSUE TITLE
Webpack -p command doesn't work with browser history

### ISSUE THREAD

**Issue by jasan-s** [reactjs/react-router#3504]
i'm using browserHistory in routes and webpack-dev-server works, yet webpack-p production build render page blank. If  I change to hashHistory in my routes the production build works.  any suggestions?

**Comment by timdorr** [comment]
You need to set up a server. Please read the guide: https://github.com/reactjs/react-router/blob/master/docs/guides/Histories.md#configuring-your-server

**Comment by MadeInMoon** [comment]
what is the link between a server and a prod bundle?
