### ISSUE TITLE
An invalid URI will make react-router crash

### ISSUE THREAD

**Issue by pucka** [reactjs/react-router#3507]
## Version
2.4.0

## Test Case
http://codepen.io/anon/pen/VjYREm

## Steps to reproduce
Use any non-valid UTF-8-encoded character sequence in the URI

## Expected Behavior
This one is hard. I think you want react-router just to ignore the faulty values

## Actual Behavior
react-router crashes making your site crash

**Comment by Aweary** [comment]
This error is thrown by the [`query-string`](https://github.com/sindresorhus/query-string) which is used by `history` to parse URIs. Ignoring the faulty values in react-router would be dependent on that package being able to return the valid portions of the URL.

**Comment by pucka** [comment]
Yes, that's one the cases. The second case, when the pathname is invalid, the error is thrown in react routers PatternUtils

**Comment by timdorr** [comment]
You can [provide your own query string parsing methods](https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md#custom-query-string-parsing), which can work around this. It's really an upstream issue with `query-string`, so I would [file an issue there](https://github.com/sindresorhus/query-string/issues/new).

**Comment by pucka** [comment]
Ok, i'll do that. But it still breaks in react-routers own library @ https://github.com/reactjs/react-router/blob/master/modules/PatternUtils.js#L120 not related to `query-string`

May not be a case if you take care of this server side, but it's still breaks on client side.

**Comment by taion** [comment]
Alternatively, catch the error and hit the error callback, as with https://github.com/reactjs/react-router/pull/3453 – we'd be happy to accept a PR that does that (if it works, &c.)
