### ISSUE TITLE
Feature request: setRouteLeaveHook equivalent for url parameters change

### ISSUE THREAD

**Issue by jurcovicova** [reactjs/react-router#3508]
I would like to have something like `setRouteLeaveHook` which would prevent transition for url parameters change. Right now, I can ask user for confirmation when url path changes, but can not when only some parameter change. 

E.g. following url change:
* from: /myUrl/23
* to: /myUrl/24

does not trigger `setRouteLeaveHook` since only parameter changed. It would be nice to have an equivalent function `setParametersChangedHook ` or something of the sort.

**Comment by timdorr** [comment]
Your route component receives those as props, so you can use the `componentWillReceiveProps` lifecycle hook. Or you can use the newer `onChange` hook.

**Comment by jurcovicova** [comment]
@timdorr Yes, but unless I am missing something, they don't allow me to prevent the change. `setRouteLeaveHook` allows me to easily say 'no I want to stay where I am now' and show warning  without changing anything inside the component itself.

**Comment by taion** [comment]
Add a child route of the route with params then – the leave hooks will actually be invoked there.

**Comment by alvestjo** [comment]
I am having the same problem. Can you please explain with an example how to solve this?
//Jonas

**Comment by cgarg** [comment]
Facing the same issue. Can somebody please elaborate on this?
