### ISSUE TITLE
Documentation regarding this.context.location ambiguous

### ISSUE THREAD

**Issue by justin-hackin** [reactjs/react-router#3509]
Enjoying the improvements in 2.4, thanks for all your hard work :+1: 

In https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md#changes-to-thiscontext, it is said:

"Accessing ... this.context.location .... are all deprecated."   However, in the next section it is stated " If you'd like to get [location] deeper in the tree ... One option is to provide it on context yourself".  Could someone help clear up the ambiguity I'm experiencing in these statements ?

**Comment by taion** [comment]
Right – the provided one is deprecated, but you can override it yourself; or use 3.x + `withRouter`.
