### ISSUE TITLE
React Router render own Component which returns dynamic Routes

### ISSUE THREAD

**Issue by aight8** [reactjs/react-router#3512]
I have something like this:
```JS
<Router>
   {myRoutesComponent}
</Router>
```

myRoutesComponent is a custom Element which returns a main Route and some child Routes. The component is connected with redux with ```connect```. This because the routes can change over time.

But that's not working! The ```myRoutesComponent``` is not rendered at all - so no routes are initialized.

Why it's not working this way?

ps: I don't want to use the react-route dynamic url functionality. I want to define all routes by myself but dynamically based on redux data.

**Comment by taion** [comment]
https://github.com/reactjs/react-router/issues/2182
