### ISSUE TITLE
Different transition animation between pages

### ISSUE THREAD

**Issue by thomasarbona** [reactjs/react-router#3513]
Hi everyone,

I need a solution for implement different animations between pages. For exemple, I have tree route:
RouteA <=> RouteB <=> RouteC
When I am on RouteA and I request RouteB or C, I want an animation which moves the pages on the right. But, when I am on RouteC and I request RouteA or B, I want an animation which moves the pages on the left.

For that, for each change, I think that I must analyse the current route and the next route and compare it with a route's list to see which route is before other route in the order (A -> B -> C).

There is a better solution for my problem ? Otherwise, how to do it ? I have no idea how to get the next or previous route. And it would be cleaner if I can get the order of the route (A -> B -> C) with the declaration of the router like that:

``` html
<Router history={browserHistory}>
        <Route path="/routeA" component={RouteA}></Route>
        <Route path="/routeB" component={RouteB}></Route>
        <Route path="/routeC" component={RouteC}></Route>
</Router>
```

Thank you in advance.

**Comment by taion** [comment]
You can attach whatever metadata you need to the route object if you want to know more about which route you're on, and a parent can always see both the next and previous props in the React lifecycle hooks to see how e.g. the array of active routes changes upon transitions.

**Comment by thomasarbona** [comment]
Can you give me more details on the parent whoo see both the next and previous props, please ?
