### ISSUE TITLE
ES6: withRouter appears to prevent the ability to call base class constructors.

### ISSUE THREAD

**Issue by benlakey** [reactjs/react-router#3514]
When using ES6 classes, extending a base component that was enhanced with the new 'withRouter' appears to prevent any children class constructors from calling the base class constructor. JSBin linked below to illustrate.

## Version
2.4.1

## Test Case
http://jsbin.com/lepumusavu/edit?html,js,output

## Steps to reproduce
Create an ES6 component that extends a base component that was enhanced using 'withRouter'.

## Expected Behavior
Child classes can call the base class constructor.

## Actual Behavior
Base class constructor is never called.

**Comment by taion** [comment]
That's expected behavior when using HoCs.

**Comment by taion** [comment]
As in don't extend the wrapper class.

**Comment by timdorr** [comment]
More specifically, the HoC isn't returning your original class. It's building a new React Component Class that renders your original component/class. It is not extending your class, so the prototype chain is essentially broken.

**Comment by benlakey** [comment]
I know that is what is happening; I'm arguing that we should allow the constructor to call the original.

**Comment by taion** [comment]
That's just how HoCs work – every HoC throughout the ecosystem has this caveat.

General extending component classes should be avoided, and even if used, should not be used on "smart" connected components anyway – prefer composition over inheritance for React components.

**Comment by benlakey** [comment]
That is not just how high order components work, and there are plenty in the ecosystem that support calling constructors appropriately. You can implement them where they call through. 

Sample implementations:

https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775

http://natpryce.com/articles/000814.html

It sounds like you'd rather not, which is fine, I guess.

Thanks for your time.

**Comment by taion** [comment]
That's incorrect.

You cannot implement a generic HoC that extends a component for the simple reason that the HoC has to work with all three forms of React component declaration.

Additionally, for HoCs that inject props, the relevant HoC _must_ wrap the supplied component.
