### ISSUE TITLE
browserHistory does not work?

### ISSUE THREAD

**Issue by abellee** [reactjs/react-router#3518]
when I launch my project under Apache, 

`Location "path to my project" did not match any routes`

but if I use web-dev-server everything is fine!

and I tried to add .htaccess file in root dir of my project just like the documentation said.

but seems no any effect.

**Comment by taion** [comment]
See documentation on configuring server for browser history.

**Comment by abellee** [comment]
@taion sorry, I'm using Apache and I have tried

**Comment by abellee** [comment]
the browser shows me `did not match any routes`

**Comment by eddOrnelas** [comment]
i have the same problem, how i can fix it?
