### ISSUE TITLE
replace() doesn't work inside of a resolved Promise

### ISSUE THREAD

**Issue by thibmaek** [reactjs/react-router#3520]
## Version
2.4.0

## Test Case
http://jsbin.com/sabovu/edit?html,js,output

## Steps to reproduce
1. Resolve a new Promise
2. When the promise is resolved, try and call `replace()` which will not work
3. Calling `browserHistory.push()` will work

## Expected Behavior
`Router.replace()` replaces the history with given pathname

## Actual Behavior
`Router.replace()` doesn't work inside a resolved promise (`.then()`) but browserHistory.push does.

**Comment by taurose** [comment]
You need to declare a third `callback` parameter in onEnter hooks for `replace` to work asynchronously.

```js
const logout = (nextState, replace, cb) => {
  let promise = Promise.resolve();
  promise.then(() => {
    replace({pathname: '/home'});
    cb();
  });
};
```
