### ISSUE TITLE
Bug with unclosed parenthesis in pathname

### ISSUE THREAD

**Issue by albertoblaz** [reactjs/react-router#3523]
Hi,

I think I found a bug that I wanted to report. Sorry if it is duplicated.

## Version
2.4.1

## Test Case
https://jsfiddle.net/qd9wLLsz/1/
Obs: It is hard to reproduce routing issues in JSFiddle, or at least I don't know how to configure it

## Steps to reproduce
1. Download this code
2. Go to this route: /152  (a specific 'site')

## Expected Behavior
It should either:
- Throw a syntax error saying that the pathname is incorrect
- or skip the unclosed parenthesis

## Actual Behavior
It runs an infinite loop because of the unclosed parenthesis in the Route path (for sites)

Thanks!

**Comment by taion** [comment]
Might be a non-issue once we do https://github.com/reactjs/react-router/issues/2286.

**Comment by timdorr** [comment]
Technically a bug in your route config. I was unable to repro the infinite loop. However, I get an invalid regex error: http://output.jsbin.com/varehufabo#/123?_k=03gzs4

I don't think we have anything to do here. And #2286 might replace this anyways.
