### ISSUE TITLE
Replacing route component from within an onEnter() hook

### ISSUE THREAD

**Issue by iotch** [reactjs/react-router#3526]
Hello. Is there any "legal" way to replace route component from within `onEnter()` hook? I'd like to show, for example, a 404 page without redirect, but keeping the same url.
Now it's possible to render 404 from route component, but it requires checking for 404 conditions in every component for every route.

Something like: 
````js
onEnter: function(nextState, replace, callback) {   
    if(someCondition) {
       callback(Error404);
    } else {
       callback();
    }
}
````

Now I'm using:
````js
onEnter: function(nextState, replace, callback) {    
    nextState.routes.forEach(function(route, idx) {
        if(route.path === this.path) {
            route.component = Error404;
            callback();
        }
    })
}
````
but it looks hackish. Thanks!

**Comment by timdorr** [comment]
A better way would be to use `getComponent` and some global state store to communicate which component that should return. And for 404-ish pages, just having a wildcard catch-all route is normally the easiest way to do this.

**Comment by taion** [comment]
See also https://github.com/reactjs/react-router/pull/3098.

**Comment by iotch** [comment]
What I'm trying to do is to show a global error page depending on request response status code made within `onEnter`. For example, before `User` component  with an url `/users/123` rendered, I need to get data for that component, and if there is no such user with id 123 and got 404, or server returned any other response than 200, I want to show an error page with relevant text.
I don't want to interpret server's response in the component's 'componentDidMount()' because I want to delay any rendering before I got the response and to mimic classical behavior when visitor sees previous page during request and transition occurs only on response.
