### ISSUE TITLE
document.body in README.md

### ISSUE THREAD

**Issue by polkovnikov-ph** [reactjs/react-router#3528]
Rendering in `document.body` is an anti-pattern. A lot of browser extensions and third-party scripts append to `document.body`, and it causes reconsolidation issues. New versions of React even log a warning for this case, because it can perfectly work on developer's PC. Please, don't trick `react-router`'s users into using such code.

**Comment by taion** [comment]
Sure, we'd be happy to take a PR that fixes this.

**Comment by polkovnikov-ph** [comment]
@taion [Here.](https://github.com/reactjs/react-router/pull/3529)
