### ISSUE TITLE
Incorrect routing when using nonstandard scheme urls

### ISSUE THREAD

**Issue by victorporof** [reactjs/react-router#3531]
## Version
2.0.0

## Steps to reproduce
Try to use react router in a context without standard protocols such as http or https, e.g. in electron.

In our case, we're defining a custom content protocol that has a custom scheme. While we were on a standard scheme, `http://bar/baz` correctly routed to  `baz`, but in the case of `foo://bar/baz`, react router redirects to `*`. These are the props passed into our component that routes to `*`:

```json
{
  "history": {},
  "location": {
    "pathname": "/",
    "search": "",
    "hash": "",
    "state": null,
    "action": "POP",
    "key": "xdtte0",
    "query": {},
    "$searchBase": {
      "search": "",
      "searchBase": ""
    }
  },
  "params": {
    "splat": ""
  },
  "route": {
    "path": "*"
  },
  "routeParams": {
    "splat": ""
  },
  "routes": [
    {
      "path": "*"
    }
  ],
  "children": null
}
```

More specifically:
Previous: "http://localhost:9191/v1/history" => routes to "history"
New route: "tofino://history/" => routes to "*".

## Expected Behavior
React router should be able to work with nonstandard schemes.

## Actual Behavior
React router always routes to `*` when on a nonstandard scheme.

**Comment by victorporof** [comment]
Hmm, looks like our location for `tofino://history` ends up being

```json
{
  "hash": "",
  "search": "",
  "pathname": "/",
  "port": "",
  "hostname": "history",
  "host": "history",
  "protocol": "tofino:",
  "origin": "tofino://history",
  "href": "tofino://history/",
  "ancestorOrigins": {}
```

Is there a way to match hostnames directly with react router? There's no way we can use `tofino://foo/bar/baz/history` so that "history" gets to be a part of the pathname (which is what react router is currently relying on afaik). Having a simple url like `tofino://history` is what we'd like.

**Comment by timdorr** [comment]
What does your route config look like? This might be something to solve inside of `history`.

**Comment by taion** [comment]
You need to use a custom history that supports this functionality – essentially a custom version of `createBrowserHistory`.

**Comment by timdorr** [comment]
More specifically, this is the core line that's causing the issue: https://github.com/ReactJSTraining/history/blob/v2.x/modules/PathUtils.js#L4

I'm actually not sure how you can get around that without remaking large chunks of `history`. The `createLocation` function is embedded pretty deeply in a core `createHistory` closure, so you can't just enhance history to get around it. 

But this is really a history issue and should be discussed [over there](https://github.com/ReactJSTraining/history).

**Comment by victorporof** [comment]
I'm a bit confused by @taion's and @timdorr's replies. Is the problem with react router's `browserHistory`, or is this a deeper problem with the `history` lib itself (thus creating a custom history manager won't help)?

**Comment by taion** [comment]
`browserHistory` is just intended to work for standard web pages. The behavior you're talking about is in the browser history. You can (probably with some duplication) make a different history that works on the hostname rather than just the path, and then use that instead.

**Comment by taion** [comment]
And in general it doesn't make sense to allow setting the hostname when using a standard HTML5 browser history, since that would be a security exception in the general case.

**Comment by victorporof** [comment]
@taion Are there any wikis or documentation on using custom histories with react-router?
