### ISSUE TITLE
Refreshing the state on press of F5

### ISSUE THREAD

**Issue by ashwinigps** [reactjs/react-router#3532]
Hi,

I have a requirement wherein I have to reload the same page with latest state on click of F5. 

Curently the default route '/' within my application is set to Login, on pressing F5 the user gets redirected to Login.

Can you please suggest how should I handle this requirement?

Regards,
Ashwini

## Version
2.0.0

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

**Comment by taion** [comment]
We don't do anything special on F5, including not changing the location. Preserving non-routing state is up to you.
