### ISSUE TITLE
Multiple react apps based on multiple routers, all working with current location

### ISSUE THREAD

**Issue by davidpelayo** [reactjs/react-router#3533]
I'm working in a concept where I need to build more than one React root components (or applications) co-working together differently, based on the current location. See image below:

<img width="902" alt="screen shot 2016-06-11 at 12 51 29 pm" src="https://cloud.githubusercontent.com/assets/84540/15985009/22e46736-2fdf-11e6-81c4-c089761390aa.png">

This mean each application will render children as they want, or just interact with some server or API based on their current state, pretty much directed by the current location.

However, when a certain UI action (say click) is triggered over one app's component or button (let's say), I want to update the location in a way all Router instances from react-router get notified so they can render their children (the applications themselves) correctly.

**Since I still don't know if this is an issue**, I will use the template provided on the repo.

What's the best way to get this running properly?

There are certain restrictions I need to accomplish like the usage of a custom router creation, like follows:
```javascript
/* from the example in jsbin */
const appHistory2 = useRouterHistory(createHistory)({
  basename: '/nevoke'
});
```
The reason is simply I need to define my own `stringifyQuery` and `parseQueryString` functions.

## Version
2.4.0

## Test Case
http://output.jsbin.com/nevoke

## Steps to reproduce
Go clicking in different "apps" links, so they will alert you with which router has got the update

## Expected Behavior
Ideally two alerts would popup

## Actual Behavior
Only the current parent's Router one gets notified

**Comment by taion** [comment]
You'd need to share the same history object for this to work.

**Comment by davidpelayo** [comment]
Fair enough. That works. Just for curiosity, could you elaborate how does it work internally to understand more?

Thanks!

**Comment by taion** [comment]
Can't say for sure without digging more. At a guess:

If you navigate with e.g. `history.push`, the updating is handled via listeners on the same history (rather than listeners on the document/window/&c.).

Therefore if you have two routers mounted with `history1` and `history2`, `history1.push` won't trigger `history2.listen`.

So you end up needing something built on top of the same history object.

**Comment by timdorr** [comment]
> history1.push won't trigger history2.listen.

Actually, it will, but based on the browser URL change. So, things like `state` won't get communicated along with it. It would essentially be like using a lossy IPC protocol. As @taion said, using the same history object would be best and semantically represents what you're trying to do anyways.

**Comment by taurose** [comment]
`history.push` doesn't trigger popstate. It's different for hash history though.

**Comment by grimunit** [comment]
@timdorr I just randomly came across this issue and it's almost a year later but figured I'd throw this out there for other people that may stumble across this. This library called [single-spa](https://github.com/CanopyTax/single-spa) is aimed at solving that problem of needing multiple SPA's to work together and basically solves the problem of routing between them.
