### ISSUE TITLE
withRouter error: Module 'react-router' has no exported member 'withRouter'

### ISSUE THREAD

**Issue by HenrikBechmann** [reactjs/react-router#3535]
installed v 2.4.1 of react-router

using Typesrcript 15

    import { withRouter } from 'react-router' 

generates above error

**Comment by taion** [comment]
That's an issue with your TS defs, not with this library.

**Comment by HenrikBechmann** [comment]
Yeah, sorry. I modified index.d.ts for version 2 (best I could find) and added

```
declare module "react-router/lib/withRouter" {
    const withRouter:Function
    export default withRouter
}

declare module "react-router" {

    import withRouter from "react-router/lib/withRouter"
   ...

export {
    withRouter,
    ...
```

all of which avoided errors, and allowed

    ... = withRouter(connect(mapStateToProps)(...

Progress.

**Comment by emzero** [comment]
@HenrikBechmann Would you consider pushing the update to DefinitelyTyped? At least it's better than the outdated 2.0.0 that's been sitting there for months now.
