### ISSUE TITLE
Active routes not changing when used with `react-redux`

### ISSUE THREAD

**Issue by mertkahyaoglu** [reactjs/react-router#3536]
Only initial route gets active class but when I change the route, it is still showing the first route as active.
This happens when the component containing `Link`s is wrapped with `connect` like this;

`export default connect(mapStateToProps, mapDispatchToProps)(Sidebar);`

But when I export it as a plain component like this;

`export default Sidebar;`

Active links are changing correctly. Is this a bug or am I missing something?

Versions;
react-router: 2.4.0,
react-router-redux: ^4.0.4

**Comment by taion** [comment]
See previous discussions around link and pure containers.

**Comment by timdorr** [comment]
Note that this is fixed in react-router@next and 3.0.

**Comment by jimbolla** [comment]
@timdorr Any chance you can point me to the changes that made it work? I'd like to see just for educational purposes.

**Comment by mertkahyaoglu** [comment]
@jimbolla [This one](https://github.com/reactjs/react-router/issues/3286) worked for me. Basically you pass `{pure:false}` to `connect` like this;

``` javascript
export default connect(mapStateToProps, mapDispatchToProps, null, {pure:false})(Sidebar);
```

**Comment by timdorr** [comment]
See the tail end of #470 and #3430

**Comment by paustria** [comment]
FYI. I can reproduce this again on
    "react-router": "2.6.0",
    "react-router-redux": "4.0.5"

**Comment by taion** [comment]
Please read earlier comments on the issue.

**Comment by paustria** [comment]
@taion I read it. So, this is expected behavior until you pass {pure:false}?

**Comment by taion** [comment]
That's how React context works. For reasons of avoiding breakage per semver, we cannot ship the workaround for this in the 2.x line.

**Comment by billyshena** [comment]
I'm currently also facing this issue and used {pure:false} as a workaround.
However, I can notice a little delay between active class being set.
Should we upgrade react-router to the 3.X version to avoid this performance issue?

Best,

**Comment by petermikitsh** [comment]
Thanks @mertkahyaoglu, that solution works for me with `react-router@2.8.1` and `react-redux@4.4.5`.

**Comment by mraliyev** [comment]
The same issue here:
`   "react": "^16.5.0",
    "react-dom": "^16.5.0",
    "react-redux": "^5.0.7",
    "react-router-dom": "^4.3.1",
    "redux": "^4.0.0",`

Adding `{ pure: false }` to connect helped.
