### ISSUE TITLE
Preserve Form values on clicking back button in browser

### ISSUE THREAD

**Issue by NileshSM** [reactjs/react-router#3538]
## Version
2.0.0

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

## Steps to reproduce

For example, in a form Input some value in a text field. On submit it goes to the next page. On clicking back button on the browser it goes to the previous page and the values are disappeared. We need this value to be retained in the text field.

## Expected Behavior
On clicking the back button on the browser, we need the form values to be retained. Please give us the suggestion to achieve this or send us the code snippet.

## Actual Behavior
On clicking the back button on the browser, the form values are getting disappeared.

Thank You

**Comment by timdorr** [comment]
You need to use a global state container, like Redux or Mobx.

**Comment by NileshSM** [comment]
Thank you Timdorr.
I need the queryKey (?_k=) to get the state. Please send me the code snippet which would retrieve the 
value of _k from the url.
