### ISSUE TITLE
onUpdate-like onEnter handler for whole Router

### ISSUE THREAD

**Issue by benwiley4000** [reactjs/react-router#3539]
I have components with `need` properties specifying actions required on mount. e.g.

```
class SomeComponent {
...
}

SomeComponent.need = [
  fetchDataForSomeComponent
];
```

Fetching required data `onUpdate` is nice because I can use `Promise.all` to fetch all required fetches simultaneously, across all components participating in routing. However this can be visually jarring, since the component loads before route swap, and data may change after the fetch.

The solution I am currently implementing is to move my data fetch to the `onEnter` hook of each of my routes. This is fine - but if I have multiple loaded routes requiring data, the data fetches must be completed one after another. I want to be able to `Promise.all` all my data at once.

`onUpdate` runs *after* component render. What if there were an `onEnter` hook that applies to the `Router` component rather than individual `Routes`? This way we could access `this.state.components` and get all fetch requirements simultaneously. Or perhaps `this.state.components` isn't accessible ... I'm really not sure how this would be implemented, but I'd love some ideas.

**Comment by taion** [comment]
You should handle this with a router middleware. Refer to how this is handled in e.g. react-router-relay.

**Comment by benwiley4000** [comment]
@taion OK. If this is going to be the "official" recommendation for React Router, there should be better documentation for it.

**Comment by benwiley4000** [comment]
I checked out the `render` prop of `Router`, and I think that's good enough. Confused by `applyRouterMiddleware`.. if that's a superior interface, perhaps it should be integrated with React Router?

**Comment by taion** [comment]
`applyRouterMiddleware` is part of this library.

**Comment by benwiley4000** [comment]
Aha - I found [this](https://github.com/ryanflorence/react-router-apply-middleware) and so I believed it to be separate.

There's no API documentation I can find referencing `applyRouterMiddleware`. The one piece of documentation [I did find](https://github.com/reactjs/react-router/blob/1c46e2c16128e93f3c406a388ccab4a582ce5ade/docs/Troubleshooting.md#inject-props-to-all-routes-via-middleware) does not explain how to do anything other than pass props down to routes (synchronously, it seems).

I took you to mean, in your initial reply, that I can use `applyRouterMiddleware` to delay rendering until a Promise has resolved? This is the value I find in `onEnter`. Since no callback is to provided to the `render` prop, I don't yet see how async behavior could be possible.

**Comment by benwiley4000** [comment]
I get a console warning when I try dispatching an action during `render` (as I should) ... it's inadvisable to change the app state while rendering. I guess what I want is to sometimes be able to cancel sending new route props to the `RouterContext` until after my Promises have resolved. That sounds like it might be more a job for Redux middleware, but I'm unsure how I should be accessing my component fetch requirements if the location change hasn't been processed by the `Router` yet.

**Comment by benwiley4000** [comment]
My current workaround is to use `Route`-level `onEnter`, as I was before, but instead of working on the current component I use `Promise.all` for `nextState.routes.map(route => route.component)` and get all component fetch requirements from there. Since multiple routes may have fetch requirements, I tell the Redux state that I am fetching so I'm able to only perform the fetch once. I change the state back once the Promise resolves or rejects.
