### ISSUE TITLE
some v2.0.0 docs links 404

### ISSUE THREAD

**Issue by aghreed** [reactjs/react-router#3542]
I'm still on v2.0.0, and have plans to update to latest eventually. However, I think that the documentation links for older versions should still be available. Currently they result in 404s. Any idea what's going on here?

https://github.com/reactjs/react-router/tree/v2.0.0/docs

All the links under "Basics" and "Advanced Usage" seem to be the problematic ones.

**Comment by taion** [comment]
Which links do you mean?

**Comment by aghreed** [comment]
@taion - sorry realized that it was not all the links after clicking around some more. I edited my original message above - please read.

**Comment by taion** [comment]
Those links are broken in the tagged commit. As it's generally considered bad practice to re-tag releases, we don't have a way to go back and fix those links. They work on master.
