### ISSUE TITLE
Expose url in this.props.route for easier route composing

### ISSUE THREAD

**Issue by blackChef** [reactjs/react-router#3543]
Consider huge apps example, each page defines its own route, then they are composed into one single route object. However, inside each individual page, it can only access path in route object, not the actual url that path is translated into. If page has `<Link />`s, it doesn't know where should they pointed to. 
It would be nice if actual url is passed in `this.props.route`.

    var Foo = () => <div>foo</div>;
    var Bar = () => <div>bar</div>;

    var SomePage = function({ children, route }) {

      // if route has url:
      // {
      //   path: 'somePage',
      //   url: 'nested/nested/somePage',
      //   childRoutes: [
      //     { path: 'foo', component: Foo, url: 'nested/nested/somePage/foo' }, 
      //     { path: 'bar', component: Bar, url: 'nested/nested/somePage/bar' }, 
      //   ]
      // }
      
      var links = route.childRoutes.map(item => {
        return <Link to={item.url}>{item.path}</Link>;
      });

      return (
      <div>
        <nav>
          {links}
        </nav>

        {children}
      </div>
      );
    };

    var somePageRoute = {
      path: 'somePage',
      childRoutes: [
        { path: 'foo', component: Foo },
        { path: 'bar', component: Bar },
      ],
    };

**Comment by taion** [comment]
We don't actually translate paths into full patterns – instead we match each path segment separately. You can access `location` from various props; more flexibly in the v3 alpha.
