### ISSUE TITLE
IndexRedirect vs this.context.router.push

### ISSUE THREAD

**Issue by tsvetann** [reactjs/react-router#3547]
## Version
2.4.1

## Test Case
http://jsbin.com/mugipih/edit?html,js,output

## Steps to reproduce
See Test Case

## Expected Behavior
When `this.props.authenticated` is false route1 will not render

## Actual Behavior
route1 renders always

Actual rendering order:
App
route1
login

**Comment by taion** [comment]
It's not clear what your route definition is trying to accomplish – you're attempting to redirect to a number of components that don't exist, you have an index redirect set up without a parent route, and you probably shouldn't be redirecting from cWM anyway.

**Comment by tsvetann** [comment]
Sorry I updated the jsbin with the correct code. 

The idea is that I would like my router to be auth aware. Login component should not be protected but Route1 should be protected

If user is authenticated IndexRedirect should be followed. If user is not authenticated I would like to redirect to /login. The earliest i can make a decision whether user should be redirected is in App component. Route1 component should be protected. What I am experiencing is that when user is not authenticated and I redirect to Login component, Route1 is rendered anyway. So looks like irrespective to whether I redirect IndexRedirect is always rendered. Is this expected?
