### ISSUE TITLE
[Feature] Dynamically matching routes

### ISSUE THREAD

**Issue by avanderhoorn** [reactjs/react-router#3548]
I have a path which looks something like the following `:selectedId(/:detailParam)`. What I would like to be able to do, it have a callback that I have registered on the above route, that asks which component it would like to render. As far as I can tell and questions that I have asked this isn't currently possible. The reason would like to do this is that I lots of different components that can be used, depending on the path and context.

In lieu of such a feature, I'm setup that that when `(/:detailParam)` pickups a match, the higher order component targeting the about route, will lookup what component it needs to render and render it as its child. This works relatively well until I hit scenarios where "modules" that I have matching different `detailParam` options, need to have sub routes in turn. As far as I can tell and questions I have asked, there is no way to say "and now use these child routes for the rest of the current march lookup".

Assuming that what I have stated in the above is true and that there isn't really a way to do this, I'm wondering if the project would be open to such a feature and if anyone has any ideas where I might get started?

**Comment by timdorr** [comment]
You're looking for [`getComponent`](https://github.com/reactjs/react-router/blob/master/docs/API.md#getcomponentnextstate-callback).

**Comment by avanderhoorn** [comment]
That doesn't complete the whole picture. That gets the component but doesn't allow me to register sub routes for that component.

**Comment by timdorr** [comment]
That is [`getChildRoutes`](https://github.com/reactjs/react-router/blob/master/docs/API.md#getchildrouteslocation-callback)

**Comment by avanderhoorn** [comment]
If I'm using `getChildRoutes` how do I get access to the `params`? Debugging through the source, the upstream methods that call my `getChildRoutes` but they aren't passed to it... depending on what the param match is, will dictate which child route I return and I shouldn't have to reparse the url to work it out.

**Comment by timdorr** [comment]
Unfortunately, because that's called while we're still traversing the route tree, the params aren't yet coalesced and aren't made available. You'll have to parse them out on your own, probably with a regex.

**Comment by avanderhoorn** [comment]
Damm... Why couldn't it give what it has so far?

**Comment by timdorr** [comment]
While erroneous, you could have duplicate parameter keys, which may change the behavior of your gCR depending on where you insert it.

Based on what I've seen of 3.0, this should be a *lot* clearer once we can get that out in the next couple weeks.
