### ISSUE TITLE
{query: false} no longer works for userRouterHistory?

### ISSUE THREAD

**Issue by nelsonlho** [reactjs/react-router#3551]
for the doc and used the following code:
`import { Router, useRouterHistory } from 'react-router'
import { createHashHistory } from 'history'
// useRouterHistory creates a composable higher-order function
const appHistory = useRouterHistory(createHashHistory)({ queryKey: false })
<Router history={appHistory} />`

when hitting refresh, a blank page appears (but starting the server will render the page)

following message appears in the console:

`Warning: Using { queryKey: false } no longer works. Instead, just don't use location state if you don't want a key in your URL query string`

any ideas?

## Version
2.0.0

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

**Comment by taion** [comment]
You're using history 3. The current compat version is 2.

**Comment by nelsonlho** [comment]
checked the version.  I am using history 2.0.1

**Comment by taion** [comment]
You are not. That error message is in history 3 only.

**Comment by nelsonlho** [comment]
sorry you are right.  it works now
