### ISSUE TITLE
How do I mock tests using calls to browserHistory?

### ISSUE THREAD

**Issue by purezen** [reactjs/react-router#3552]
Hey, I am using react-router in my project and started writing tests for the same.

The tests are working fine except a place in my api middleware where I am making a call to browserHistory.

I have setup a mock environment for my tests using jsdom as shown below:
```
global.document = require('jsdom').jsdom('<!doctype html><html><body></body></html>')
global.window = document.defaultView
global.navigator = global.window.navigator
global.localStorage = global.sessionStorage = {
    getItem: function (key) {
        return this[key];
    },
    setItem: function (key, value) {
        this[key] = value;
    }
};
```
The mock environment works fine for places where sessionStorage is used. I tried attaching the history object here too but that doesn't seem to be working.

Thanks!

**Comment by taion** [comment]
Use `createMemoryHistory` for tests
