### ISSUE TITLE
Is there any event/hook to detect route change?

### ISSUE THREAD

**Issue by twoeo** [reactjs/react-router#3554]
I have a ``<Router>`` with many ``<Route>``

I want count each page views like Google Analytics

So the problem is how to detect Router url changing ?

**Comment by amxfonseca** [comment]
Can't you use onChange property? Just add that you your top level route(s) and it will call a function and pass you the information about the previous and the next route.

```
 <Route path="/" onChange={yourHandler} component={AppContainer}>
   <IndexRoute component={StaticContainer}  />
   <Route path="/a" component={ContainerA}  />
   <Route path="/b" component={ContainerB}  />
 </Route>

function yourHandler(previousRoute, nextRoute) {
   //do your logic here
}
```

**Comment by EasonWang01** [comment]
`browserHistory.listen` won't work if you type url in address bar.

**Comment by mjackson** [comment]
@EasonWang01 It will after you hit Enter

**Comment by EasonWang01** [comment]
no not work

**Comment by ViniciusTavares** [comment]
I agree with @EasonWang01, I had tried using `browserHistory.listen` and it was't called after I typed url.

In a redux app, I've been using `syncHistoryWithStore` from react router redux. The example below works after typing url in address bar: 

const history = syncHistoryWithStore(browserHistory, store)

history.listen(location => analyticsService.track(location.pathname))

Source: https://github.com/reactjs/react-router-redux

**Comment by timdorr** [comment]
When you're loading up a page for the first time (i.e., when you type in a URL in the browser), under `history` 3.x, the first `listen` doesn't immediately fire back. You should get the location initially with `getCurrentLocation` instead.

**Comment by adrian-moisa** [comment]
I'm using react router dom.
After importing: `let Router = require('react-router-dom').BrowserRouter;` Should I import `import { browserHistory } from 'react-router';`?

**Comment by timdorr** [comment]
No, this library doesn't work with React Router or history 4.0. Please see the top of the README.

**Comment by yss14** [comment]
Is there still a way to get notified when the current route changes?
Upgraded to v4, so the `history` approach doesn't work anymore :(

**Comment by roblapp** [comment]
React router 4 is harder to work with in my opinion. Many teams at my organization are switching to other routing frameworks or are going back to 3.0. It's too bad.  What is an easy way in 4.0 to perform a check to see if the user is authenticated before the route transition?

**Comment by roblapp** [comment]
How do you listen for route changes with React Router 4.0?

**Comment by timdorr** [comment]
Get history off context or create it outside the Router and pass it in as a `history` prop.

**Comment by roblapp** [comment]
For React-Router 4 I solved this by wrapping one of my top level components using the HOC withRouter. This allows me to access this.props.history. The component is a parent element of every other component in the app. In code...

```
//index.js
ReactDOM.render(
    <Provider store={store}>
      <BrowserRouter>
            <AppContainer>
                   <Route exact path="/" Component={...} />
                   <Route exact path="/Home" Component={...} />
           </AppContainer>
        </BrowserRouter>
    </Provider>,
  document.getElementById('root')
);

//AppContainer.js
import App from '../components/App';
import { connect } from 'react-redux';
import { withRouter } from 'react-router'

function mapStateToProps(state) {
  return {};
}

function mapDispatchToProps() {
    return {};
}

export default withRouter(connect(mapStateToProps, mapDispatchToProps)(App));

//App.js
class App extends Component {
  constructor(props) {
    super(props);
    
   //Here ya go
    this.props.history.listen((location, action) => {
      console.log("on route change");
    });
  }

  render() {
     return (
         {this.props.children}
      );
  }
}
```

**Comment by igurenko** [comment]
Easy way: try to catch it in your root component: 

```
componentWillReceiveProps(nextProps) { 
   if(this.props.pathname !== nextPorps.pathname) {
          // your code
   } 
}
```

**Comment by lizhong8532** [comment]
@roblapp This way can be listen route change. But easy duplicate listens, how to listen only once?

**Comment by jazeee** [comment]
@lizhong8532 From testing, `history.listen()` returns an `unlisten` function. You'd use this to unregister from listening.
Example: 
```
this.unlisten = this.props.history.listen(...);
//Later...
this.unlisten();
```
Presumably, one could attach a listener in `componentDidMount` and unlisten in `componentWillUnmount` or similar...

**Comment by vnsrahul1304** [comment]
@amxfonseca I want to do something just before the route change in url. Currently onEnter and browserHistory.listen are fired just immediately after url change. I want something like onEnterBefore. Is there any way around?

**Comment by amxfonseca** [comment]
@vnsrahul1304 I'm not that familiar with the router. But I think there are some possible solutions:

You can use the `onLeave` hook from the router, but I think you can't run anything asynchronous there so it may not be suited for your specific use case.

And if I'm not mistaken you also have the `listenBefore` event on the history. This one provides you with a callback that you can call when you're ready to proceed. It may create a sluggish navigation experience though 
```js
history.listenBefore( (location, done) => doSomething(location).then(done) )
```

In last case scenario you can always wrap the `Link` component provided by React Router and add your own custom logic there.

**Comment by vnsrahul1304** [comment]
@amxfonseca Thanks a lot! history.listenBefore works great for me. And I am also able to get the current route(through window.location.pathname) as well as the next route through the location param of listenBefore. Also the navigation seems fine.

**Comment by dangnhi169** [comment]
@roblapp I tried your solution. But I get this error: 
```
browser.js:40 Uncaught Error: You must pass a component to the function returned by connect. Instead received undefined
    at invariant (browser.js:40)
    at wrapWithConnect (connectAdvanced.js:84)
    at Object../src/AppContainer.js (AppContainer.js:13)
    at __webpack_require__ (bootstrap 4be83206928d24f746a2:669)
    at fn (bootstrap 4be83206928d24f746a2:87)
    at Object../src/App.js (fetch.js:461)
    at __webpack_require__ (bootstrap 4be83206928d24f746a2:669)
    at fn (bootstrap 4be83206928d24f746a2:87)
    at Object../src/index.js (index.css?4b88:26)
    at __webpack_require__ (bootstrap 4be83206928d24f746a2:669)
    at fn (bootstrap 4be83206928d24f746a2:87)
    at Object.0 (registerServiceWorker.js:108)
    at __webpack_require__ (bootstrap 4be83206928d24f746a2:669)
    at bootstrap 4be83206928d24f746a2:715
    at bundle.js:719
```

Anybody know why? And I'm using react-router v4.2.0

**Comment by QuantumInformation** [comment]
@lizhongit @jazeee  Hi, can you explain your issue and solution more verose, thx?

**Comment by smishr4** [comment]
I have a suggestion to hook `yourFunction` between `route` updates, instead of hooking it to the route, you can use the componentDidUpdate() lifecycle hook of the component which updates with the route,
in my case, `App` component is the parent component which updates when a route changes, `index.js` is where I use `App` component and wrap it inside `BrowserRouter`

inside `App` component: 

`class App extends Component{
  componentDidUpdate() {
    /**
     * Check if window google analytics object is defined
     * And sends a PageView event when a location is changed.
     */
    if (window.ga) {
      window.ga("set", "page", location.pathname);
      window.ga("send", "pageview");
    }
  }

  /**
   * Toggles visibility of SideDrawer component
   * @function toggleSideDrawer
   * @memberof App
   * @static
   *
   */
  toggleSideDrawer = () => {
    this.setState(prev => ({ showSideDrawer: !prev.showSideDrawer }));
  };
  /**
   * Render of App component
   * @function render
   * @returns {string} returns jsx
   * @memberof App
   */
  render() {
    return (
      <Layout
        showSideDrawer={this.state.showSideDrawer}
        toggleSideDrawer={this.toggleSideDrawer}
      >
        <Switch>
          <Route path="/auth" component={Auth} />
          <Route path="/logout" component={Logout} />
          <Route path="/contact" component={Home} />
          <Route path="/terms_of_service" component={Extras} />
          <Route path="/privacy_policy" component={Extras} />
          <Route path="/risk_disclosure" component={Extras} />
          <Route exact path="/" component={Home} />
          <Redirect from="*" to="/" />
        </Switch>
      </Layout>
    );
  }
}`

`index.js`:

`ReactDOM.render(
  <Provider store={store}>
    <BrowserRouter>
        <App />
    </BrowserRouter>
  </Provider>,
  document.getElementById("root")
);`
