### ISSUE TITLE
Huge apps example and server side rendering

### ISSUE THREAD

**Issue by olalonde** [reactjs/react-router#3558]
I've been trying to implement code splitting similar to the `huge apps` example in my app but am getting the following React error when refreshing a route which is loaded through `require.ensure`:

```
warning.js:44 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <!-- react-empty: 1 -
 (server) <div class="root" dat
```

This error only occurs on routes which use `require.ensure`. I am guessing this is because react tries to do a first render on the client before `require.ensure` had time to load the route and therefore renders to an empty component. Is that correct? Would there be any way to tell React not to render anything if require.ensure still needs to load modules?

**Comment by taion** [comment]
See the server rendering guide.

**Comment by manovagyanik1** [comment]
@olalonde Did you figure out the issue? I am facing the same issue, not sure though.

**Comment by olalonde** [comment]
@manovagyanik1 I think I solved with this: https://github.com/ReactTraining/react-router/blob/master/docs/guides/ServerRendering.md#async-routes (async routes section)

**Comment by garmjs** [comment]
If you are using es6 modules you can use `System.import` instead of `require.ensure` and its easy to do tree shaking and code splitting.

**Comment by timdorr** [comment]
3.0 will let you return the Promise from System.import directly: #3719

**Comment by manovagyanik1** [comment]
Thanks guys. It worked :)

**Comment by paolavness** [comment]
Does anyone know where the link is to the above file? Searching all over but keeping getting a 404.
Thank you!

**Comment by pshrmn** [comment]
@paolavness https://github.com/ReactTraining/react-router/blob/v3/docs/guides/ServerRendering.md#async-routes

**Comment by paolavness** [comment]
@pshrmn thank you
