### ISSUE TITLE
Provide params or routeParams to getIndexRoute

### ISSUE THREAD

**Issue by ryancole** [reactjs/react-router#3564]
I'm using dynamic routing and have a scenario where I'd like to use a particular react component depending on a route param. So for example, if I've got a route like below ...

```
/:slug
```

I've like to be able to look at that slug and if it's `A` then use component A, or if it's `B` use component B.

Right now, `getIndexRoute` receives the `location` param, which does have the current path ... as a string, though. There exists the `params` and `routeParams` props that get passed into route components. Could `getIndexRoute` receive these too, so that we can make more precise logic around the route params?

**Comment by taion** [comment]
This was resolved by https://github.com/reactjs/react-router/pull/3561.
