### ISSUE TITLE
correct support route configuration components as a array

### ISSUE THREAD

**Issue by wenbing** [reactjs/react-router#3565]
## Version
2.4.1

## Test Case

http://jsbin.com/wepineyika/1/edit?html,js,output

## Steps to reproduce

visit http://output.jsbin.com/wepineyika/1#/test?_k=aq03lh

## Expected Behavior

when components is an array, this.props.children should be working

## Actual Behavior

this.props[0]
this.props[1] is working

**Comment by taion** [comment]
This syntax is not supported.

**Comment by taion** [comment]
Look into using named components if you want multiple children.
