### ISSUE TITLE
withRouter with TransitionGroup

### ISSUE THREAD

**Issue by yangbomb2** [reactjs/react-router#3568]
I have root component and router handles each component accordingly.

When I wrap children of root component with TransitionGroup, target child component won't fire the life cycle(componentWillEnter, componentWillLeave...)

for instance, 

export default withRouter(AbstractPage) won't fire. router is accessible via props.

export default AbstractPage does. but contextType has to set for router.

am I missing something?

**Comment by taion** [comment]
Please provide a repro.
