### ISSUE TITLE
isActive returns false for paths with optional params

### ISSUE THREAD

**Issue by misogl** [reactjs/react-router#3573]
## Version
2.4.1

## Test Case
http://jsbin.com/baqanihiha/edit?html,js,output

## Steps to reproduce
Click on first link -> path is active
Click on second link -> path is not active

## Expected Behavior
Path should be active in both cases.

## Actual Behavior
`isActive` returns true only when current location does not contain any optional parameters.

**Comment by taion** [comment]
Dupe https://github.com/reactjs/react-router/issues/3277 and others
