### ISSUE TITLE
[Feature Request] Load chunk on Link mouse hover

### ISSUE THREAD

**Issue by FezVrasta** [reactjs/react-router#3577]
I'm rewriting an application from Ember (1.6) to React (latest).

I have a page with a side menu on the left, and the content on the right. When you click one of the menu options, the route changes, the content on the right is replaced.
I'm using code splitting by route, so every route loads its own resources (based on the react-boilerplate implementation).

Everything is nice, but the code splitting of Webpack makes the transition time between the pages a bit too slow for my tastes compared to the old Ember implementation.
This because when you click the menu option, you have to wait for the HTTP request to load the needed chunk.
I mean, it's question of half a second difference or so, but it's still annoying and I see potential improvements if the page to load needs a bigger chunk.

I was wondering if it could be possible to ask React Router to pre-load the chunk needed by the route that will be loaded once the user clicks on a Link component.

In pratice, if I have:

```jsx
<Link to='/settings/foobar'>Click me</Link>
```

When I hover the URL, the chunk relative to the `/settings/foobar` route could be loaded, making the transition once the user clicks much faster.

Do you think it is something feasible?

**Comment by timdorr** [comment]
You can extend Link to support this. It's not something we'll do internally, since we don't want to be opinionated about code splitting.
