### ISSUE TITLE
Consider including a TypeScript d.ts definition file

### ISSUE THREAD

**Issue by emzero** [reactjs/react-router#3580]
TypeScript is gaining popularity and I believe all serious JS libraries should start including its own definition file so it's easier to update without having to also update the definition which are usually outdated.

[Latest definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react-router/react-router.d.ts) file from DefinitelyTyped for react-router is for version 2.0.0 which doesn't contain things like `withRouter`.

**Comment by taion** [comment]
Dupe https://github.com/reactjs/react-router/issues/3455.
