### ISSUE TITLE
IndexLink with optional URL portion

### ISSUE THREAD

**Issue by solugebefola** [reactjs/react-router#3581]
Hi all, 
I was trying to use the IndexLink to highlight a route with an optional portion, but it seems that exact matching REALLY means exact matching.  However this seems counterintuitive to me since the option is included in the path for the link itself.  I think it might be a good idea if IndexLinks allowed matching with optional parameters.  The current example I am working with involves a header with a series of links that I want to highlight when active.  However, one of the links has an optional component to display when an id is shown:
```
<Route path={"/projects/:project_id/inspect(/:device_id)"} component={SingleDevicePage} key="single-device"/>
```
I want to have an active link to the inspect route, but I also would like it to be active when there is a device id present.  I worked around it by making the optional portion into a child route: 
```
<Route path={"/projects/:project_id/inspect"} component={SingleDevicePage} key="single-device">
    <Route path={"(:device_id)"}  key="single-device-selected" />
</Route>
```
and then using a standard Link for the parent route, but that seems odd as there is no component attached.  If there is a better way to accomplish this, I would be glad to hear it.

Cheers,
Solar

**Comment by taion** [comment]
See discussion regarding `isActive` for optional path segments at https://github.com/reactjs/react-router/issues/3277.
