### ISSUE TITLE
Missing withRouter HoC and proper way to get Router while using TypeScript

### ISSUE THREAD

**Issue by galvesribeiro** [reactjs/react-router#3582]
Hello,

The tutorial suggest to use https://github.com/reactjs/react-router-tutorial/tree/master/lessons/12-navigating so we can have access to `this.context.router` however this note in upgrade section say that all that is deprecated https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md#changes-to-thiscontext 

Despite the confusion on those links, somewhere I've seen suggestions to use `withRouter` like here https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.4.0.md#withrouter-hoc-higher-order-component but, in that case, I can't see the exported module `import { withRouter } from 'react-router'`...

So again, what is the proper way to have inside a component access to `router` object so we can hook events, ask for navigation, etc?

I'm trying to ask it on Discord but it looks like a deadland...

Appreciate any help.

Thanks
Gutemberg

**Comment by taion** [comment]
`this.context.router` is not deprecated – the upgrade guide does not say that. We do recommend most users use `withRouter`, but both are fine. The tutorial should probably now use `withRouter`, though, and we'd appreciate a PR there to fix that.

We do in fact export `withRouter` in the main package: https://github.com/reactjs/react-router/blob/v2.5.1/modules/index.js#L5

We do not maintain the TypeScript definitions for React Router. If the ones you see are out-of-date, please submit a PR to the repo hosting those definitions.

**Comment by galvesribeiro** [comment]
Ok... I think I'm blind...

Anyway... Any major library today has its own TypeScript definitions inside their own packages and NPM itself recommends that...

**Comment by taion** [comment]
That's not true. For example, type definitions for both React and Lodash live in DefinitelyTyped and are not maintained by the package maintainers.

**Comment by galvesribeiro** [comment]
I guess there are other major packages like Angular, Angular2, and many other node.js packages... Just need to look around...

**Comment by mrgreen7** [comment]
@galvesribeiro Check out https://github.com/typed-typings/npm-react-router It supports withRouter()
