### ISSUE TITLE
Errors when trying to access URL with parameters

### ISSUE THREAD

**Issue by aaronmoore93** [reactjs/react-router#3584]
Hi,

I am currently trying access a URL with parameters by typing it directly into the address bar on my browser with the parameters I wan (localhost:8080/questions/1/195). However once I try and load or refresh the page I get a series of 404 errors

`http://localhost:8080/questions/1/bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)`

I am using Webpack.

Any help would be greatly appreciated!

**Comment by taion** [comment]
Please consult the section on histories in the docs, or else refer to the tutorial.
