### ISSUE TITLE
Hash history needs a DOM

### ISSUE THREAD

**Issue by gagayang** [reactjs/react-router#3585]
I tried to use Web Worker in the Web project with react then the error was found
"History needs a DOM Hash"
But I did not use react-router in hashHistory. is not in the use of react-router must be bound in an existing DOM?
Because the principle of Worker Web is to put the DOM fragments together and then hang in the tree dom.

**Comment by timdorr** [comment]
Unfortunately, [`history` has a hard check for `window.document`](https://github.com/ReactJSTraining/history/blob/v2.x/modules/ExecutionEnvironment.js). You can make it work with a memory history instead.
