### ISSUE TITLE
Parent path does not show as active

### ISSUE THREAD

**Issue by h8rry** [reactjs/react-router#3586]
```js
<Route path="/">
  <Route path="widgets" component={WidgetList} />
  <Route path="widgets/:widgetId" component={Widget} foo="bar"/>
</Route>
```

Currently, if I want to read foo="bar", I can't do `this.props.route.bar` because `path="/"` is active, instead of `path="widgets/:widgetId"`.

I would have to do `this.props.routes[1].bar`.

Any suggestions on identifying the actual active path / route? Thanks!

**Comment by timdorr** [comment]
I wouldn't use props on your Routes. Have a specialized route component for each of your Routes and put whatever data you need inside of those.

**Comment by h8rry** [comment]
What if my parent route is used as a navbar, and I want the navbar to
change based on the current active path?

**Comment by timdorr** [comment]
`this.context.router.isActive()` or `activeClassName` on `<Link>`.
