### ISSUE TITLE
Issue with non-English path names

### ISSUE THREAD

**Issue by mohsen1** [reactjs/react-router#3594]
#### Version
2.4.1

#### Test Case
My repo at this specific SHA: https://github.com/rah-foundation/website/blob/a248549f5100949bf493d30b0402be59eb79ed33/src/server.tsx#L44

#### Issue
I noticed that if you don't decode the URL before passing it to `match` function it will not match non-english routes. The [Server Side Rendering Guide](https://github.com/reactjs/react-router/blob/master/docs/guides/ServerRendering.md#server-rendering) should mention that.

Changing those line mentioned above to this, fixes the backend routing issue: 

```js
const location = decodeURIComponent(req.url);
match({routes, location}, (error, redirectLocation, renderProps) => { // ...
```

This is probably not limited to non-English languages and can be an issue for routes with special characters like space in it.

**Comment by mohsen1** [comment]
Actually, this will break the front-end side of it because in the front-end React-Router is expecting encoded URIs. 

What I try was to remove this change and instead, `encodeURIComponent` my paths when I pass them to `Route` component:

```
// t('faq') returns a non-English string
<Route path={encodeURIComponent(t('faq'))} component={FAQ} />
```

This fixed the issue in the back-end and front-end **but** I have to `encodeURI` my links everywhere:

```
<Link to={encodeURIComponent(t('faq'))}>{t('faq')}</Link>
```

Doesn't it make sense for `Route` and `Link` components to encode the URIs automatically?

**Comment by taion** [comment]
You have to handle encoding yourself. Consider a link to e.g. `/foo/bar` – the library has no way of knowing whether you mean `/foo/bar`, `%2Ffoo%2Fbar`, or something else.

You _should not_ decode the URI before matching against it – the matcher will decode params accordingly before passing them to components; otherwise your routes should be specified with encoded paths.

**Comment by khankuan** [comment]
@mohsen1 i had the same issue and it breaks with whitespace. Wondering if it is a useful solution to split path by `/` and then encode each part then join them back:
```
.split('/').map(encodeURIComponent).join('/')
```
