### ISSUE TITLE
withRouter make refs abnormal

### ISSUE THREAD

**Issue by saviroyu** [reactjs/react-router#3595]
When I use withRouter like this:  ComponentB = withRouter(ComponentA)

 I can't obtain the state and internal function from ComponentA  through refs.

**Comment by watert** [comment]
Maybe add a method to source code to get wrapped instance, like `react-redux` way: `getWrappedInstance()`

**Comment by watert** [comment]
added a PR https://github.com/reactjs/react-router/pull/3596

**Comment by taion** [comment]
That's just how HoCs work. See e.g. equivalent issue for Redux.

**Comment by saviroyu** [comment]
@taion 

would you show some detail?

**Comment by pvienneau** [comment]
@savioryu some resources for context: https://facebook.github.io/react/docs/higher-order-components.html#refs-arent-passed-through
