### ISSUE TITLE
support for react 0.15.2 -  https://fb.me/react-unknown-prop

### ISSUE THREAD

**Issue by FredericHeem** [reactjs/react-router#3599]
The new React version 0.15.2 has introduced a new warning regarding passing props to children: https://fb.me/react-unknown-prop

## Version
2.5.2

## Test Case
git clone https://github.com/FredericHeem/starhackit && cd starhackit/client && npm i && npm start

## Expected Behavior
No react warnings
## Actual Behavior
warning.js:44 Warning: Unknown props `history`, `location`, `params`, `route`, `routeParams`, `routes` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

**Comment by taion** [comment]
You're getting that error because _you're_ passing down the route props to the DOM nodes.

**Comment by FredericHeem** [comment]
Thanks a lot.

**Comment by FredericHeem** [comment]
This is a pattern taken from the example: https://github.com/reactjs/react-router/blob/master/examples/huge-apps/app.js#L23

**Comment by timdorr** [comment]
This is not inherent with the router. It's an issue with an example. This bug report is for the wrong thing. A PR for fixing the example is what's needed instead.

**Comment by taion** [comment]
https://github.com/reactjs/react-router/pull/3608

**Comment by CodeJjang** [comment]
It still happens by today.
