### ISSUE TITLE
Optimization in transition example

### ISSUE THREAD

**Issue by zabojad** [reactjs/react-router#3601]
I use the [transition pattern](https://github.com/reactjs/react-router/blob/master/examples/animations/app.js) in few of my projects and I realise that a page will be re-rendered when being left.

I try to implement a shouldComponentUpdate method like this:
```
	function shouldComponentUpdate(np,ns) {

		if (np.location.pathname == "/") {

			console.log("DO NOT UPDATE INDEX PAGE");
			return false;
		}
		return true;
	}
```

But the problem is that even when leaving, the page receives its previous props and np.location.pathname is still equal to "/". That seems to be because of [how React.cloneElement works](https://facebook.github.io/react/docs/top-level-api.html#react.cloneelement)...

I tried to check the pathname with context.router.isActive but the context too seems not to be up to date...

Any idea of how could I detect that the page is a leaving page from within the page component it self?

**Comment by taion** [comment]
See https://github.com/reactjs/react-router/blob/c41309b3cd5ef5bf7e4b6e5219f0aba110557c7a/examples/animations/app.js#L22-L62

**Comment by zabojad** [comment]
@taion Thank you. I tried to implement this `RouteCSSTransitionGroup ` and I get warnings like this one: `Warning: [react-router] `context.location` is deprecated, please use a route component's `props.location` instead.`.

Also, it doesn't solve my problem. The page gets re-rendered when being left...

Is this example up to date?

**Comment by zabojad** [comment]
Yes I confirm, we have exactly the same behavior as with the latest version of that same example. Can you reopen the issue please?

**Comment by taion** [comment]
It's not intended to be a copy-pastable drop-in thing; just an illustration of a pattern for controlling re-rendering during a transition.
