### ISSUE TITLE
Refreshing the page with parameters in the url doesn't work

### ISSUE THREAD

**Issue by Borisboky** [reactjs/react-router#3604]
I'm trying to create a multistep registration form but I have a problem when I try to refresh the page with the url with a parameter.

My routes.js file is as follows : 

```
const routes = (
  <Route path="/" component={App}>
    <IndexRoute component={HomePage}/>
    <Route path="registration/:id" component={hideIfLoggedIn(Registration)}/>
    <Route path="registration" component={hideIfLoggedIn(Registration)}/>
    <Route path="reset-password" component={PasswordReset} />
    <Route path="portal" component={requireAuth(UserPage)} />
  </Route>
);
```

When I'm on _http://localhost:8001/registration_ everything works perfect. If I refresh the page it works without problems.

But the problem is when I'm on _http://localhost:8001/registration/step-one_ . First time when it loads it works good, but when I try to refresh the site I get a blank page.

I do not get CANNOT GET / or something like this, I get only a blank page. In the console is the error 
**bundle.js:1 Uncaught SyntaxError: Unexpected token <**

But I do not get this error when I'm on _http://localhost:8001/registration_ and when I refresh the page. The code is the same.

Any advice?

**Comment by taion** [comment]
You probably aren't correctly specifying an absolute path to your bundle.
