### ISSUE TITLE
Pass prevState as argument to onLeave

### ISSUE THREAD

**Issue by albertogasparin** [reactjs/react-router#3612]
This is a little enhancement I'm asking for. Currently, both `onEnter` and `onChange` have router state passed as an argument. That allows us doing stuff with router location and parameters. However, it is not the case for `onLeave`. Is there any particular reason?

Use case example: I'd like to handle socket.io room joining/leaving on the router. 

```js
<Route path="/" component={App}>
  <Route 
    path="/chat/:id" 
    component={Chat} 
    onEnter={(nextState) => { 
      joinChat(nextState.params.id); 
    }}
    onChange={(prevState, nextState) => { 
      leaveChat(prevState.params.id); 
      joinChat(nextState.params.id); 
    }}
    onLeave={(prevState) => { 
      leaveChat(prevState.params.id); 
    }}
  />
</Route>
```

I know this could be handled by the component itself, but I'm questioning why not passing the previous state to the `onLeave` callback, as it might be helpful in some situations.

**Comment by timdorr** [comment]
> I know this could be handled by the component itself

That's the reason right there. Make use of lifecycle methods as much as possible.

In your example, you can move the onChange up to your top level route instead.

**Comment by taion** [comment]
Is it weird that the API is inconsistent here? I do think it would feel more consistent if `onLeave` received `prevState`? It'd be a pretty easy change.

**Comment by taion** [comment]
I'm inclined to add `prevState` there just for the sake of consistency. It's just really weird that `onLeave` doesn't have the signature you'd expect there.

One reason you may not want to just use lifecycle hooks there is (as with `onChange`) that you might be using named components.
