### ISSUE TITLE
Doc Improvement for "Decoupling the UI from the URL" section

### ISSUE THREAD

**Issue by dchambers** [reactjs/react-router#3614]
The [Decoupling the UI from the URL](https://github.com/reactjs/react-router/blob/master/docs/guides/RouteConfiguration.md#decoupling-the-ui-from-the-url) section of the [Route Configuration](https://github.com/reactjs/react-router/blob/master/docs/guides/RouteConfiguration.md) document talks about 'Absolute paths', but never actually demonstrates an absolute path. It instead shows you how to decouple the UI from the URL using relative paths.

I think it would make sense to first show how to do it with relative paths, but then provide an alternative example using absolute paths to show another way that may be more useful when it's a deeply nested route and you want to avoid lots of code duplication.

If people agree that this change makes sense then I'd be happy to submit a pull-request, though it's not currently clear to me whether the version of the config that uses relative URLs avoids the incompatability with _dynamic routing_?

**Comment by taion** [comment]
Oops. That pattern is no longer encouraged. I'm just going to drop that section entirely from the docs.

**Comment by taion** [comment]
https://github.com/reactjs/react-router/pull/3615
