### ISSUE TITLE
Replace flag for Link component

### ISSUE THREAD

**Issue by juliankrispel** [reactjs/react-router#3618]
Right now at Rainforest QA we use react router and it's Link component extensively. Every now and then we need to manually implement a redirect because we want to use `browserHistory.replace` instead of `.push`. It'd be nice if the Link component did that as well. One could implement this by having a `replaceState` flag on the Link component for example. I'd be happy to provide a PR if this'd be inline with the design of react-router.

Thanks for a great project!!!

**Comment by taion** [comment]
See earlier https://github.com/reactjs/react-router/pull/2914

It's not really a great fit for a "link", especially with `href`.

**Comment by holyxiaoxin** [comment]
See https://github.com/ReactTraining/react-router/issues/3776
