### ISSUE TITLE
animation has no effect 

### ISSUE THREAD

**Issue by ruanzy** [reactjs/react-router#3619]
```
class Index extends React.Component {
  render() {
    return <div>
			<Header/>
			<Sidebar/>
			<div className="content">
			<ReactCSSTransitionGroup
			  component="div"
			  transitionName="example"
			  transitionEnterTimeout={2500}
			  transitionLeaveTimeout={2500}
			>
				{this.props.children}
			</ReactCSSTransitionGroup>
			</div>
		</div>
  }
}
```

**Comment by timdorr** [comment]
Your component is probably getting unmounted between routes. It's hard to tell without the route config. 

Just follow the example for this: https://github.com/reactjs/react-router/blob/master/examples/animations/app.js

**Comment by ruanzy** [comment]
`render((
  <Router history={hashHistory}>
    <Route path="/" component={App}>
		<IndexRoute component={Index}/>
		<Route path="/index" component={Index}>
			<Route path="/a" component={A}/>
			<Route path="/b" component={B}/>
		</Route>
		<Route path="/login" component={Login}/>
	</Route>
  </Router>
), document.getElementById('app'));`
