### ISSUE TITLE
React server rendering example in es5 ? How to use with NodeJS ?

### ISSUE THREAD

**Issue by Nishchit14** [reactjs/react-router#3625]
## Version
2.4.1

## Steps to reproduce
This is server code
```
const ReactRouter = require('react-router')
const routes = require('../../lib/web/routes')

renderWeb(req, res, next) {

  let location = req.url    //   '/pricing'
  ReactRouter.match({
      routes: routes,
      location: location
    }, (error, redirectLocation, renderProps) => {

      console.log(error, redirectLocation, renderProps)
  })
}
```

This is routes file
```
export default (
    <Route path="/" component={App}>
      <IndexRoute component={Home}></IndexRoute>
      <Route path="/pricing" component={Pricing}></Route>
      <Route path="/integration" component={integration}></Route>
    </Route>
)
```
## Expected Behavior
It should find the route.

## Actual Behavior

Currently console output are undefined
`undefined` `undefined` `undefined`

**Comment by timdorr** [comment]
First, don't use nested absolute routes. Remove the leading slash from those paths. 

Did you check what is in req.url? Something must be missing, because that code would not work otherwise. Try deleting your node_modules directory and reinstalling.
