### ISSUE TITLE
Improve the API to navigate programatically

### ISSUE THREAD

**Issue by mrgreen7** [reactjs/react-router#3626]
The two options for navigation from https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md seem non-optimal to me. 

https://facebook.github.io/react/docs/context.html states that the context API will be subject to future changes and that it's usage causes code to become harder to understand. 

> Regardless of whether you're building an application or a library, try to isolate your use of context to a small area and avoid using the context API directly when possible so that it's easier to upgrade when the API changes.

Since there was an API before which did not rely on the context feature I'm guessing it would be possible to avoid using it?

The second option of importing browserHistory/hashHistory/... is weird IMHO since you hard code your choice of history at multiple locations. Wouldn't it be much better to refactor this so that you have something like `import {history} from 'react-router'` and have the history object propagate to what the user has chosen as history when configuring `<Router history={myHistoryType}></Router>`?

Please let me know if something needs clarification.

**Comment by timdorr** [comment]
Use `withRouter` instead. We added it specifically for your concerns. https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.4.0.md
