### ISSUE TITLE
NFR: routes mount/unmount callbacks

### ISSUE THREAD

**Issue by iotch** [reactjs/react-router#3628]
Hello.
Will be great to have routes mount/unmount callbacks to act on app screens changes. For example, to dispatch an action on old route leave and new route **enter and resolved** (ready to render). This is useful for async loaded routes - it's impossible to use existing `onEnter` callback because it fires right after location changed, not after component resolved.

Something like:
````jsx
<Router routeWillMount={cb} routeWillUnmount={cb}  {...props} />
````
or
````jsx
<Route beforeMount={cb} onLeave={cb}  {...props} />
````
Thanks!

**Comment by timdorr** [comment]
You can do this with the built-in React lifecycle methods on your route components.

**Comment by iotch** [comment]
Oh, didn't knew about that! It's a great idea to copy-paste same code into each `componentWillMount()` instead of configure router once! Thanks!
