### ISSUE TITLE
Feature request: additional route hooks

### ISSUE THREAD

**Issue by perrin4869** [reactjs/react-router#3629]
This is related to my question in https://github.com/reactjs/react-router/issues/3404.
The specific use case I have in mind is, dispatching a redux action when entering a specific route, but only if we are entering the route after coming from another route (i.e., if it's not the first time the router is rendering).

I'm thinking something like `onEntering` or `onLeaving`, which would be a counterpart to `onEnter` and `onLeave`, kind of analogous to `componentWillReceiveProps` and `componentDidReceive` props.

```js
function fooEnter(prevState, nextState, ...) {
  if (prevState.location && fooForm.sent) { // if this is not the first route rendered
    store.dispatch(resetFooForm()); // for example
  }
}

<Route path="foo" component={Foo} onEntering={fooEnter} />
```

For your cosideration!

**Comment by taion** [comment]
While in principle other leave hooks are possible, our current view is that the best way to handle this sort of thing is with a router middleware – though in your case you'd be just as well served with a component lifecycle hook.

**Comment by perrin4869** [comment]
Actually yeah, I'll try to do this with a middleware later, that might work indeed!
And now that I think about it, rather than more lifecycle hooks, I guess what I'd be missing is a `prevState` parameter in `onEnter`. Is there a reason why that is not available?
Lifecycle hooks on the component would not really work because they don't have access to previous router state, afaik.

**Comment by perrin4869** [comment]
Also, I'd rather keep my components as dumb as possible

**Comment by perrin4869** [comment]
Hm... the reason the middleware won't work is that the middleware has no access to the `router` instance, and therefore it can't know the current state of the router. Maybe `renderRouterContext` and `renderRouteComponent` should have `this` bound to `router`? That would make sense, I can try sending a pull request for that

**Comment by taion** [comment]
It can't bind to the router at that point.

The router context middleware receives all the render props as props, so just use cWRP or equivalent.

**Comment by perrin4869** [comment]
hm... well, this is what I've been able to come up with:

```js
// Say you have a route:
// <Route path="contact-us" component={ContactUs} reset={resetContactUsParam} />
let prevLocation = null;
const resetContactUsParam = {
  predicate: state => state.contactUs.sent,
  action: resetContactUs(),
};

const resetFormMiddleware = () => ({
  renderRouteComponent(child, routeProps) {
    const { reset } = routeProps.route;
    if (prevLocation !== null && reset && reset.predicate(store.getState())) {
      store.dispatch(reset.action);
    }

    prevLocation = routeProps.location;
    return child;
  },
});
```

I don't think there is a more organic way to compare previous locations than this, although I'd be very happy if you have a better solution to the problem!

**Comment by taion** [comment]
Render a component and use cWRP in that component

**Comment by perrin4869** [comment]
So something like:

```js
const resetFormMiddleware = () => ({
  renderRouterContext(child) {
    return <ResetComponent>{child}</ResetComponent>;
  },
});
```

Where `ResetComponent` uses `cWRP`?

**Comment by taion** [comment]
Right

**Comment by perrin4869** [comment]
Got it, thanks!

**Comment by perrin4869** [comment]
tried that approach, but it was actually futile, because `ResetComponent` above has no easy way of getting information about the route (I guess it could be calculated from the props the same as `RouterContext` does though). What does work, however, is to use `renderRouteComponent` instead:

```js
const resetFormMiddleware = () => ({
  renderRouteComponent(child) {
    return <ResetComponent>{child}</ResetComponent>;
  },
});
```

I'm afraid this might break though if you start nesting more routes...
