### ISSUE TITLE
onEnter signature are not matching to your doc in Route Configuration

### ISSUE THREAD

**Issue by hasangilak** [reactjs/react-router#3630]
<Route onEnter={(nextState, replace) => console.log( replace(nextState, 'archived')) }
       path="featured" component={FeaturedStuff}></Route>

replace function accepts pathname as a second argument not first. but in your doc https://github.com/reactjs/react-router/blob/master/docs/guides/RouteConfiguration.md you passed pathname as first argument which breaks my code ;)

**Comment by taion** [comment]
You are using a very old version. The signature is up to date for the current version.
