### ISSUE TITLE
Router.initialize is not a function

### ISSUE THREAD

**Issue by Cottin** [reactjs/react-router#3632]
We're using `"react-router": "^2.0.1"` with react `"react-hot-loader": "^1.1.6"` and sometimes when you write some code that breaks you don't get to see the line that actually broke in Chrome's console. The only output is `Router.initialize is not a function` like so:

![image](https://cloud.githubusercontent.com/assets/4736419/16809607/3aaae3ee-4921-11e6-99b1-9a75bd42204e.png)

i.e. a very general error message that is not related to the code that broke anything which means it's almost impossible to track down the bad code.

Usually, if you have only written a couple of lines, it's easy to just revert it manually and see what line that broke things. However, if you have been changing lots of code it's almost impossible to manually test what lines broke things in this way.

I'm just curious if this problem happens to more people or if anybody have an idea if something is wrong in our setup?

**Comment by timdorr** [comment]
Look at the stack trace. You're trying to call this nonexistent function in your main.js file.

**Comment by Cottin** [comment]
Seems like this issue is easily solved by activating "Pause on exceptions" in Chrome dev tools.

![image](https://cloud.githubusercontent.com/assets/4736419/16810014/aa933aca-4922-11e6-90ea-8c2d9f24899a.png)

When doing so, Chrome first stops at the line in the source code that provokes the error. (When you continue (F8), you get the indecipherable error message above).
