### ISSUE TITLE
Examples not working with Webpack 2.1

### ISSUE THREAD

**Issue by Kitanotori** [reactjs/react-router#3633]
Problem
=====
The routes are unaccessible. When trying to access a route, following errors are thrown in the browser console:
```
GET 
http://localhost:8080/__build__/shared.js [HTTP/1.1 404 Not Found 9ms]
```
`ReferenceError: webpackJsonp is not defined`

If I comment out CommonsChunkPlugin from webpack.config.js, the routes are accessible but 404 error for shared.js is still being thrown.

How to reproduce
===========
Set Webpack version in package.json to "^2.1.0-" so that the lates version is being used, and access any example route, e.g. http://localhost:8080/active-links/

Confirmed with react-router 2.5.2, and recent master and next branches.

**Comment by Aweary** [comment]
Webpack 2 isn't supported. That's why webpack is set to `"^1.13.1"` in the package.json file.

**Comment by taion** [comment]
As noted. The Router itself works fine with webpack 2, but we're targeting our examples at the stable release.

**Comment by Kitanotori** [comment]
Any plans to support it?

**Comment by taion** [comment]
There's no "support" or "not support" here. The examples are intended as examples of the React Router API, not as examples of how to configure webpack – and in fact the webpack configuration there is very specific to the way these examples are set up, and are neither intended for nor appropriate for a website that does not have that specific structure.
