### ISSUE TITLE
Links in docs to history package appear to be broken

### ISSUE THREAD

**Issue by rimunroe** [reactjs/react-router#3634]
I've been trying to determine the upgrade path from 0.13 to 1.0, and ran into a problem when it came time to look at the way histories are handled now. The docs reference a package called `history` in the reactjs GitHub, but when I try to go there it it redirects me to a non-existent or private repository of the ReactTraining GitHub.

Where is the package located now?

## Version
N/A, seems like docs fell out of date with the outside world.

## Test Case
https://github.com/reactjs/react-router/blob/master/upgrade-guides/v1.0.0.md#locations

## Steps to reproduce
Click on link to the [`history` package](https://github.com/reactjs/history)

## Expected Behavior
Being taken to a page showing the package and further information on it.

## Actual Behavior
There appears to be a repository redirect to https://github.com/ReactTraining/history, which either doesn't exist or is private.

**Comment by taion** [comment]
Started working again just now. We'll update the links again when we get a chance.
