### ISSUE TITLE
react-router translated uri fragments??

### ISSUE THREAD

**Issue by jamiehill** [reactjs/react-router#3640]
We're building a multi-lingual site, using react-router, which I'm tasked with also having to translate the individual uri fragments for the current route, so that the address url appears translated as well.

I'm afraid I've exhausted other lines of research, and realise this probably isn't deemed a bug, but think this is probably the best forum for opening a discussion on how best this should/could be implemented.

Having studied the `react-router` code, it seems there's a one-to-one mapping being browser location and route name declared on the router.  Is this correct?  An obvious solution could be to explicitly declare all routes, with all i18n versions, but seems a little verbose and rigid.

I was wondering how best to implement, some kind of intermediary i18n lookup, between browser and router, where routes could be correlated to their translated counter parts?

Obviously this would need to be bi-directional, so that user initiated routes and direct address bar routes would be handled in this fashion.

There don't currently seem to be any hooks, for implementing something one might deem as middleware.  Am I wrong?

**Comment by taion** [comment]
You can handle this in `getChildRoutes` – generate child routes dynamically based on whatever you want. You'll need to be careful with referential equality if you're using route transition hooks, though.

**Comment by taion** [comment]
Note that the declared paths will need to be URI encoded.

We'd be really happy to get a PR with improved documentation for i18n handling.

**Comment by jamiehill** [comment]
Ok, will look into that.  Which version of RR should I go with?  4, or stable versions?
