### ISSUE TITLE
Bundle output is not optimised despite importing from `lib`

### ISSUE THREAD

**Issue by ctrlplusb** [reactjs/react-router#3642]
## Version
2.5.2

## Test Case
https://github.com/ctrlplusb/react-router-bundlesize

## Steps to reproduce

_Note: I was using node v6_

Run the following commands
```console
git clone https://github.com/ctrlplusb/react-router-bundlesize
cd react-router-bundlesize
npm install
npm run analyse
```

Then... 
- Browse to http://webpack.github.io/analyse/
- Select the `build/stats.json` file.
- Go to the "modules" section and look for `react-router` imports.  You will see imports for code that is not being used. e.g. createHashHistory.

## Expected Behavior

Don't include unnecessary modules from `react-router` and `history` in bundle output when following the guidelines from the [Minimizing Bundle Size](https://github.com/reactjs/react-router/blob/master/docs/guides/MinimizingBundleSize.md) docs.

## Actual Behavior

There are imports that I am not using/importing.  The below screenshot isn't the exhaustive list, but you can see references to `createHashHistory` for example whilst in my source I explicitly import `react-router/lib/browserHistory`.  A few others too.

<img width="640" alt="screenshot 2016-07-18 09 39 45" src="https://cloud.githubusercontent.com/assets/12164768/16909733/5d7ad786-4ccc-11e6-9133-67cc05e05c76.png">

**Comment by timdorr** [comment]
Your project doesn't specify which version of webpack you're using, but I'm going to assume 1.x. Those items are downstream of the files you've included. They are required for things like Route and Router to function. This is normal and expected behavior.

**Comment by taion** [comment]
Hash history is getting pulled in because of the backward compat behavior for creating the default history in the router.

There wasn't really a way to get around that while still maintaining that behavior. We've gotten rid of this on the v3 pre-releases, so I'd recommend taking a look there if it's an option.

**Comment by ctrlplusb** [comment]
Oki great thanks for the info @taion - I look forward to the v3 release. :)

@timdorr my bad! I didn't save down the dependency.  I was in fact using the latest webpack 2, which of course includes tree-shaking features.  It doesn't seem to be having a major impact on react-router thus far.  I'll retry with v3 though.

**Comment by ctrlplusb** [comment]
🎉 I installed the v3 prerelease and bundle size is much smaller!

Sweet I am busy making a "skinny" version of my [`react-universally`](https://github.com/ctrlplusb/react-universally) boilerplate.  

The original version comes out at a gzipped bundle size of __57kb__.

Dropping in `preact`, `preact-compat` and `react-router@3.0.0-alpha.1` has dropped the bundle size way down to __21.4kb__!!  Frikken stoked with that. :)
