### ISSUE TITLE
route with optional parameter is not active if parameter is present

### ISSUE THREAD

**Issue by kromit** [reactjs/react-router#3648]
## Version
2.6.0

## Test Case
http://jsbin.com/geyisilaxi/8/edit?html,js,output

## Steps to reproduce
click  "home"
click  "items"
click  "edit"
click  "edit 123"

## Expected Behavior
link to "edit" is not active

## Actual Behavior
link to "edit" should be active

**Comment by taion** [comment]
This has been discussed at length repeatedly. Please see existing issues.

**Comment by kromit** [comment]
Close by duplicate after 1 minute, without providing an actual open or fixed duplicate? Well I'll do it then: 

#3581 
#3573
#3527
#3277 
#3233
#3230
#3052
#2570
#2437

**Every single issue about this is closed without actually fixing the bug**.  And yes, it is a bug because there are even more closed issues (in the last 6 months) about it and I am willing to bet there will be more until it is fixed on at least you will be willing to stop pretending there is no bug because and this is working as intended. Maybe it should not be **intended** behavior when this is clearly not working as **expected**. 

/rant

Please leave at least one issue about this OPEN for people to find the workaround.
Please do not close not fixed issues.

**Comment by kromit** [comment]
workaround for dynamic paths:

```
module.exports = {
    path: 'edit'
    ,onEnter(nextState, replaceState) {
        if (!nextState.params.itemId) {
            replaceState(nextState, "/home/items/edit/0"); 
        }
    },
    childRoutes: [
        {
            path:':itemId'
            ,getComponent(location, callback) {
                require.ensure([], (requireCallback) => {
                    callback(null, require('./Edit'))
                })
            }
        }
    ]
};
```

**Comment by taion** [comment]
I've cleaned up an inappropriate comment and an incorrect workaround for this issue thread.

I'd like to recommend contributors to check and read through existing issues before opening new ones, and to follow the reasons given there.

**Comment by kromit** [comment]
Deleting criticisms does not fix the issue. People will create new issues for this bug until it is fixed or at least open confirmed or documented elsewhere. Referencing to old issues closed months ago makes no sense since it is not clear if the old issue still relevant now. Especially a day after a minor release.

**Comment by taion** [comment]
It's not a bug, and it is documented. The previous issues cover at length why we set things up to behave in this manner, and how to set up your routes so that their semantic hierarchy gives you the behavior you're looking for.
