### ISSUE TITLE
location.pathname not same between client-side render and server-side render.

### ISSUE THREAD

**Issue by MagiCarbon** [reactjs/react-router#3651]
## Version
2.3.0

## Test Case
server-side render. sry, no Test Case.

## Steps to reproduce

**App component:**
```jsx
class App extends React.Component {
    componentDidMount() {
        console.info(this.props.location.pathname);
    }
    componentDidUpdate() {
        console.info(this.props.location.pathname);
    }
    ....
}
```

**Route:**
```jsx
  <Route path="/" component={App} >
    <IndexRoute component={Home} />
    <Route path="about" component={About} />
  </Route>
```
**steps**
- 1. let's say server is listening on `8000` and it's server-side render.
- 2. now access `http://localhost:8000/about`
- 3. keep eyes on output of `console.info()`;

**output**
- 1. `componentDidMount()` get server-sider rendered location.pathname which is `/about`;
- 2.  now click on About `<Link />`, `componentDidUpdate` get the location.pathname which is `about`.

## Expected Behavior

*output 1* sould exactly equal to *output 2* nomater client-side render or server-side render.

## Actual Behavior

it's not equal. *output 1* get a prefix-'/'.

**Comment by taion** [comment]
Links need to be absolute. The correct path _is_ `"/about"`.

**Comment by MagiCarbon** [comment]
@taion thanks for reply. but in `output 2`, `location.pathname` is "`about`". it should be "`/about`" as u said.
