### ISSUE TITLE
Enhancement: Add custom data to routes for access in event handlers

### ISSUE THREAD

**Issue by joaoreynolds** [reactjs/react-router#3653]
Coming from the Angular world, ui-router allows us to pass in data which is accessible by the event handlers. For example:
```
.state('admins', {
  url: '/admins', template: '<admin-list></admin-list>',
  data: {
    authorizedPermissions: ['admins_view']
  }
})
```

We could then access that data in the `onRouteChange` event handlers. This would be an awesome feature in react-router where some custom data object is passed through the Route params and made accessible by our global (or wrapper route) onEnter/onChange event handler functions.

My solution for now is:
`<Route path="new" component={NewUser} onEnter={checkRoutePermissions('users_save')}/>`

but I'm limited to one onEnter function per route, which could be restricting (unless I wrap multiple event handlers in a single wrapper function - but that gets messy).

It would be great to have something like this:

```
<Route component={MainTemplate} onChange={onRouteChange} >
  <Route path="new" component={NewUser} data={permissionNeeded: 'users_save'}/>
</Route>

//Then onRouteChange can use that data
function onRouteChange(prevState, nextState, replaceState, callback, data){
  const routePermission = data.permissionNeeded
  //do some auth stuff here with routePermission
}
```

**Comment by taion** [comment]
In the route callbacks, `this` is the route on which you set up the callback, and `nextState`/`prevState` both include a `routes` entry that has an array of all the route objects matched.

**Comment by joaoreynolds** [comment]
Oh this is awesome. I had no idea I was able to pull extra properties out of there! Sorry to create an annoying Issue out of what could have been a SO question. I thought it was a feature missing.
