### ISSUE TITLE
Navigation to hash URL not firing onChange hook in IE11

### ISSUE THREAD

**Issue by jrajav** [reactjs/react-router#3655]
## Version
2.6.0

## Test Case
https://github.com/jrajav/react-router-ie-hash-issue

## Steps to reproduce
Clone Test Case repo and do `npm i && npm start`. Visit `http://localhost:3000` in IE11, then click the link (which is an `<a href="#hash">`).

## Expected Behavior
The onChange hook is fired and a `hash changed: #hash` message logged to the console. This happens in every other browser.

## Actual Behavior
The hook is never fired and no message is logged.

**Comment by taion** [comment]
This would be a bug in `history` regarding when browser events get fired. Not clear to me why you want `onChange` to fire when not changing the route and using browser history, though. Probably you should be using `<Link>` anyway.

**Comment by jrajav** [comment]
We want to intercept a hash change, we are using hashes to change tabs inside of a page. <Link> is less useful for us because we want to simply add the hash to the current url, not change the whole `location` - unless that is possible with <Link>, too?

**Comment by taion** [comment]
`router.push({ ...location, hash: newHash })`

**Comment by jrajav** [comment]
Yes - then, I gather it's not possible with a simple `<Link>`?

**Comment by taion** [comment]
`<Link to={{ ...location, hash: newHash }}>`
