### ISSUE TITLE
Allow `<Link to>` to be a function

### ISSUE THREAD

**Issue by taion** [reactjs/react-router#3657]
Maybe a little QoL, thing... it'd let people do e.g.

```js
<Link to={location => ({ ...location, query: newQuery })>
```

without having to worry about having `location` on context or wrapping the `<Link>`'s parent with `withRouter`.

**Comment by umidbekkarimov** [comment]
This is really good feature! What about 'push' and 'replace'?

**Comment by smashercosmo** [comment]
This is awesome

**Comment by smashercosmo** [comment]
I would like to propose also a possibility to provide a function to set isActive flag. Something like
```
<Link to="/hello" isActive={location => location.pathname === '/hello'} activeClassName="active">
```

**Comment by jodo4x** [comment]
@smashercosmo  what do you think of this way?
```js
const ACTIVE_NAME = { "true": "active": "false": "" }

<Link to="/foo" className={ACTIVE_NAME[pathname === "/foo"]}>foo</Link>
<Link to="/bar" className={ACTIVE_NAME[pathname === "/bar"]}>bar</Link>
<Link to="/baz" className={ACTIVE_NAME[pathname === "/baz"]}>baz</Link>
<Link to="/baz/quux" className={ACTIVE_NAME[/\/baz/i.test(pathname)]}>baz&#47;quux</Link>
```

**Comment by smashercosmo** [comment]
@jodo4x Where do you get pathname from?

**Comment by jodo4x** [comment]
@smashercosmo from the prop `props` , if you are using react-redux, then `location` will  be passed on automatically by `connect`.

**Comment by smashercosmo** [comment]
@jodo4x yes, but if your component is deeply nested you need to pass location through the components tree.

Well this issue is not suited for this discussion. I'll open a separate one.

**Comment by timdorr** [comment]
Added in #3669

**Comment by taion** [comment]
Hmm, I wonder if these functions should take e.g. `{ location, params }` instead of just `location` as the arg.

**Comment by eldh** [comment]
I think `{ location, params }` would be great.

**Comment by taion** [comment]
@eldh Thanks for your feedback! How would you use `params`? Would it be to essentially build a relative link?

**Comment by taion** [comment]
The reason I ask is because I can think of a few places where I could use `params`, but in all those it's only to work around the lack of relative links. I don't want to complicate the API here just to work around a missing feature elsewhere – would rather add that missing feature.

**Comment by eldh** [comment]
Yeah, that would be a common case. We have some places where we do filtering in such a way that it would be a nice addition. Not sure, maybe relative links could solve that too.

**Comment by taion** [comment]
@eldh Can you clarify regarding the filtering use case a bit? Just trying to understand use cases here.

I'm really torn here because `(location: Location) => LocationDescriptor` just feels like a cleaner and more symmetric API, and lets the user be a bit terser when writing things like

```jsx
({ query, ...location }) => ({ ...location, query: { ...query, new: 'query' } })
```

but I don't want to rule out real use cases.

**Comment by eldh** [comment]
We have some cases where params are part of a (known) set, and to calculate filter options we'd need access to the params. 

However, I'm not even sure that this api would be the cleanest way to solve that case though. And I suspect we aren't using react-router idiomatically anyway, so feel free to disregard my comments :)

**Comment by taion** [comment]
Okay, I think I'll go with `(location: Location) => LocationDescriptor` API for now and reserve the option to change it before cutting a final release. Thanks for your feedback!
