### ISSUE TITLE
Request to fire `getChildRoutes` after `onEnter`, and request for a re-evaluation of `getChildRoutes`

### ISSUE THREAD

**Issue by EvNaverniouk** [reactjs/react-router#3663]
## Version
2.5.2

## Test Case

Too complex to be put into a JSFiddle. See description below.

## Steps to Reproduce and Expected Behavior

In my application, the available routes cannot be determined at initialization because they are based on two important factors:

- **Issue 1)** What routes a user has access to depends on their auth permission levels. The user must first go through the auth flow and only when that succeeds, will I know which routes he has access to. (eg. An admin user can access www.mysite.com/admin, but a regular user cannot)
- **Issue 2)** Because the available routes are dependent on permission access, the user might have their permissions elevated/lessened while they are interacting with the app. I have a WebSocket which will notify the client of this. At this time, I need to update the available routes and (if necessary) ensure the user is kicked out of any route they are currently browsing.

## Actual Behavior

At the moment this is incredibly difficult to do with react-router for the following reasons:

- **Request 1)** The recommended auth flow control is done via the `onEnter` callback on a Route and the recommended controller for route access is done via `getChildRoutes`. However, `getChildRoutes` always fires before the `onEnter` callback is resolved. I would like to require that all `onEnter` callbacks are evaluated (in order of route hiearchy) before `getChildRoutes` is called.
- **Request 2)** There doesn't appear to be any way to trigger a re-evaluation of the routes after initialization. I would like some global method, ie (`require('react-router').reEvaluate()`) which would tell the router to re-evaluate itself again. So that `getChildRoutes` is re-run for all routes, and if your current route disappeared, you would be redirected to a 404 page. This would essentially be a new `render()` call to the top-level `<Router />` component

## Example of Request 1 behavior

Imagine the following route structure:

```
const topMostGetChildRoutes = () => {
	return (
		<Route component={Home} path="home" />
			<Route component={Restricted} path="/restricted" onEnter={requireAuth} getChildRoutes={innerGetChildRoutes} />
		</Route>
	);
};

<Router>
	<Route getChildRoutes={topMostGetChildRoutes} />
</Router>
```

My expectation is the following execution order when I visit `/restricted/something`:
- `topMostGetChildRoutes` gets called first
- `home` route component is rendered
- `requireAuth` gets called from `onEnter` of the `restricted` route
- `innerGetChildRoutes` gets called from the `restricted` route
- If `innerGetChildRoutes` returned a `something` route -- it will take me there

## Other Notes

- _"Why can't you just wrap your authenticated routes with a HOC to redirect away users who don't have permissions?"_ I could, but my application is huge. And I would rather use code splitting to prevent the loading of those components if a user doesn't have access to them. Using React Router to control this code splitting would be ideal. If that route isn't even listed, then webpack wouldn't even load it. If I wrap with a HOC then webpack will still load them for the users only to immediately redirect unauthenticated users away from it. Seems very wasteful.
- _"What is the expected behavior when a user's access to their current route is revoked?"_ It should behave just as if that route no longer exists. So they would get redirected to the nearest `"*"` path route.

**Comment by taion** [comment]
1. It doesn't make sense to run `onEnter` before `getChildRoutes`, because we don't know what the child routes are yet, and we don't want to unnecessarily waterfall these sorts of requests. If you need to do stuff in `getChildRoutes`, do it in `getChildRoutes`.
2. If you want to re-run the match, call `router.replace` with the current location. Or re-mount the router.

**Comment by EvNaverniouk** [comment]
Running stuff directly in `getChildRoutes` doesn't work in this case though. Imagine, the following scenario:

The route structure is this:

```
<Router>
	<Route component={Root} path="/">
		<Route component={Public} path="public" />
		<Route component={AuthOnly} path="authonly" onEnter={requireAuth} getChildRoutes={getChildRoutes} />
	</Route>
</Router>
```

And now, there are two possible scenarios:
- 1) I visit `/authonly`. It doesn't call `getChildRoutes` at all (since I'm not visiting a child). It calls my authentication code in `onEnter`, logs me in, and shows me the `AuthOnly` component. Everything works great! But now,
- 2) I visit `/authonly/inner`. It calls `getChildRoutes` which requires authentication to happen... But authentication happens only in `requireAuth` in the `onEnter` prop. Therefore, `getChildRoutes` requires an empty array of routes, and the react-router kicks me out to a 404 before authentication can even happen.

Are you suggesting I call run authentication requests both in `onEnter` and in `getChildRoutes` for any inner child route? If I have a complex structure with many nested routes, I'm going to need to have every single `getChildRoutes` request ensure the user is authenticated. That feels incredibly inefficient.

**Comment by taion** [comment]
It should be no big deal if you cache the results. But otherwise that _is_ what the auth flow example is getting at – not letting the user access specific routes when not authenticated.

**Comment by EvNaverniouk** [comment]
I have another problem with the proposed solution.

If I call blocking auth code in the `getChildRoutes` it also blocks initial rendering. So I can't even display a loading spinner while routes are being fetched. `getChildRoutes` gets called at the deepest route, so none of the wrapper component routes can render while this is happening.

**Comment by EvNaverniouk** [comment]
Another problem with calling having `getChildRoutes` get executed before `onEnter` is that you can't properly redirect unauthenticated calls.

Because `getChildRoutes` is called first, a route might be missing as a result of bad authentication -- however, this simply takes the uses to a 404 page instead of redirection to the login page. If `getChildRoutes` doesn't return a valid route for the current URL, it doesn't call `onEnter` on that parent route, and since the `replace()` call is inside `onEnter`, the user isn't properly redirected.
