### ISSUE TITLE
Passing props from parent route to child routes on initial render

### ISSUE THREAD

**Issue by renarsvilnis** [reactjs/react-router#3664]
Noticed an issue when for the the initial render, when first opening page, props from a parent route aren't passed in to child routes.

## Version
react-router - `2.6.0`
react - `15.1.0`

## Test Case
**1)** https://jsbin.com/jijuso/21/edit?html,js,console,output *(using stateless function)*
**2)** https://jsbin.com/jijuso/22/edit?html,js,console,output *(using react class component)*

> Two test cases, because testing locally against my app didn't noticed an issue with standard react class component, But after some more testing, the issue was there. 

## Steps to reproduce
Create an `react-router` app that has a base route `Base` and  a child `MyView` which is defined as a stateless react component.
Make `Base` component pass-in additional props to the `children` views.

```javascript
const {Router, Route, IndexRoute, browserHistory} = ReactRouter;

/**
 * Base container for react-router routes
 */
class Base extends React.Component {
  render () {
    const {children} = this.props;
    
    const child = React.cloneElement(children, {msg: 'Hello world'});
    
    return (
      <div>
        {child}
      </div>
    );
  }
}

/**
 * Stateless function react-router component
 */
class MyView extends React.Component {
  render () {
    const {msg} = this.props;
    
    return (<h1>{msg}</h1>);    
  }

}

MyView.propTypes = {
  msg: React.PropTypes.string.isRequired
};


const App = (
  <Router history={browserHistory}>
    <Route path="/:lang" component={Base}>
      <IndexRoute component={MyView} />
    </Route>
  </Router>
);

ReactDOM.render(App, document.querySelector('.app'));
```

## Expected Behavior
Expect child route `MyView` to receive `msg` prop on its initial render.

## Actual Behavior
Child route `MyView` hasn't received an `msg` from parent.

```
"Warning: Failed propType: Required prop `msg` was not specified in `MyView`.
Check the render method of `RouterContext`."
```

# Sidenote 🤔
Also noticed that if the parent route, in this case `/:lang` has an parameter, then I also need to specify route path `/:lang` to all of its children.

Should create another issue for that?

```javascript
const App = (
  <Router history={history}>
    <Route path="/:lang" component={Censorship}>
      <IndexRoute component={Intro} />
      <Route path="/:lang/rules" component={Rules}/>
      <Route path="/:lang/choose" component={Choose} />
    </Route>
  </Router>
);
```

**Comment by taion** [comment]
https://github.com/reactjs/react-router/blob/master/docs/Troubleshooting.md#required-prop-was-not-specified-on-route-components

**Comment by taion** [comment]
And don't prefix your path with `/` if you want the path to be relative to the parent route

**Comment by renarsvilnis** [comment]
Thanks!
