### ISSUE TITLE
Reloading the page with `setRouteLeaveHook` changes the location hash on going back in history

### ISSUE THREAD

**Issue by Gopikrishna19** [reactjs/react-router#3667]
## Version
2.4.1
2.5.2
2.6.0

## Test Case
When using `context.router.setRouteLeaveHook`, and returning a simple false in hook to prevent the user form navigating away, the hash value in the url is changed to next location. It works as expected if the user comes to the page from an another page, but it doesn't work once the page is reloaded.

Recreated here: https://gopikrishna19.github.io/react-router-issue
Source here: https://github.com/Gopikrishna19/react-router-issue

## Steps to reproduce
1. Go to [https://gopikrishna19.github.io/react-router-issue](https://gopikrishna19.github.io/react-router-issue).
2. Click `sub page` link.
3. Click back button -> prevents the navigation, does not change/resets the hash.
4. Reload the page
3. Click back button -> prevents the navigation, but sets the hash to next location

Clicking the `app` link works as expected -- doesn't change the hash nor lets the user navigate.

## Expected Behavior
Should retain the hash value

## Actual Behavior
Hash value is changed to that of previous state

**Comment by Gopikrishna19** [comment]
jic, if anyone is wondering, it has the same effect even when I use a string to show up the confirm dialog and I click cancel, the view remains the same but the hash value changes in the url bar.

**Comment by taion** [comment]
Dupe https://github.com/ReactTraining/history/issues/157

**Comment by Gopikrishna19** [comment]
@taion I did not look at the `history`'s issues. Thanks
