### ISSUE TITLE
Nested history

### ISSUE THREAD

**Issue by thehappycoder** [reactjs/react-router#3676]
I would like to be able to do something like this:
```
<Router history={ appHistory }>
    <Route path='/sessions/:sessionId' component={ App } history={createMemoryHistory}>
      <IndexRoute component={ Home }/>
      <Route path='video' component={ Video }/>
    </Route>
  </Router>
```

This should allow opening /sessions/1 via URL
But it should not be possible to open /sessions/1/video via URL
Link to /sessions/1/video should open Video component but URL in the address bar should remain as before -- /sessions/1

**Comment by taion** [comment]
You'd want to just mount another router at that route component.

**Comment by thehappycoder** [comment]
Hm, never thought it was possible. Can you show me an example?

```
<Router history={ appHistory }>
    <Route path='/sessions/:sessionId' component={ App }>
      <Router history={ createMemoryHistory() }>
        <IndexRoute component={ Home }/>
        <Route path='video' component={ Video }/>
      </Router>
    </Route>
  </Router>
```

It doesn't seem to be working. I am able to open /sessions/1/video. Expected result is that Home component should open.

**Comment by taion** [comment]
Render the `<Router>` in the route component – not as part of your route tree.

**Comment by thehappycoder** [comment]
I implemented App component's render method like this:
```
render() {
    return (
      <Router history={ createMemoryHistory() }>
      ...
    )
}
```

But I get this warning:
browser.js:49Warning: [react-router] Location "/" did not match any routes

I guess I have to supply proper location to createMemoryHistory? But what is it?

Router:
```
<Router history={ appHistory }>
    <Route path='/sessions/:sessionId' component={ App }>
      <IndexRoute component={ Home }/>
      <Route path='video' component={ Video }/>
    </Route>
  </Router>
```
