### ISSUE TITLE
Isomorphic `onEnter` usage

### ISSUE THREAD

**Issue by ufocoder** [reactjs/react-router#3682]
I have a question about `react-route` hooks usage.

I'm writing an isomorphic react+redux application and I use `onEnter` hook to `dispatch` action that will fetch data from API like this: 

```
<Router onEnter='fetchData(store)'>
```

And there's my hook function:

```
import {loadData} from 'path/to/data/actions';

export function fetchData(store) {
  return (nextState, replace, callback) => {
      store.dispatch(loadData())
        .then(() => callback())
        .catch(() => callback());
  };
}
```

When server side render my application it fetch data and then data fetched on client side. 
How to avoid twice data fetching?

**Comment by taion** [comment]
Presumably you'd need to rehydrate the store and check for the data on the client before rendering the router.
