### ISSUE TITLE
How to programmaticaly go to a specific route?

### ISSUE THREAD

**Issue by monkeymonk** [reactjs/react-router#3683]
When trying this :

```
onSubmit(values, dispatch) {
    actions.update(values)
        .then((response) => {
            // ...doing stuf
            this.props.history.push(`step/2`);
        });
}
```

I get a warning telling me that is deprecated and that I should use `this.context.router.push` but I did not have any `this.context.router` and cannot find any documentation about that.

Is someone can point me to the answer?

Thank you very much!

**Comment by timdorr** [comment]
Use `withRouter`: https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.4.0.md
