### ISSUE TITLE
DefaultRoute instead of IndexRoute

### ISSUE THREAD

**Issue by userpixel** [reactjs/react-router#3688]
I'm new to `react-router` and had a few head scratches till I figured `<IndexRoute>` indicates the default route. Even the documentation says:

> We can use an <IndexRoute> to specify a "default" page.

I think DefaultRoute would be a more expressive name. But I might be too late since there is a lot of code and documentation for IndexRoute. Anyhow I thought I'll give a shout. Feel free to close the issue if it's too much work/unnecessary. :hammer:

**Comment by taion** [comment]
It's "index route" by analogy with an `index.html`. It used to be `<DefaultRoute>` but I believe the name change was explicit – otherwise it'd potentially be confusable with the concept of a "not found" route.
