### ISSUE TITLE
Handler vs Component

### ISSUE THREAD

**Issue by uragecz** [reactjs/react-router#3690]
Can anybody explain what is different between handler and component in router?? Which one i should to use ?
```
<Route path='/' component={App}>
    <IndexRoute component={App} />
  </Route>
```
and then 
`ReactDOM.render(<Router history={browserHistory} routes={routes} />, document.querySelector('#app'));`
or 
```
<Route name="ourApp" path="/" handler={require('./components/ourApp.js')}>
           <DefaultRoute handler={Home} />
    </Route>
```
and then 
```
Router.run(routes, function(Handler) {  
    React.render(<Handler />, document.getElementById('app');
});
```
???
for example first solution - http://davidmeents.com/journey-into-react-part-3-navigating-between-webpages-with-react-router/
second solution - https://www.themarketingtechnologist.co/react-router-an-introduction/

**Comment by taion** [comment]
It looks like you're just getting started with React Router. Take a look at our tutorial and the guides on the site. The issue tracker is intended to track bugs and feature requests – it's not an ideal resource for learning how to use React Router.

**Comment by Rixot** [comment]
Understandable, except the `handler` attribute doesn't seem to be documented anywhere. But judging by the articles, it looks like it's just an alias for `component` anyway. Can someone confirm this?
