### ISSUE TITLE
Changing the location without triggering routing

### ISSUE THREAD

**Issue by salzhrani** [reactjs/react-router#3691]
Is it possibleto do something similar to what medium does when publishing a post for the first time the URL changes to the public/sharable URL without UI changes. I was able to do such using `history.pushState` but I wasn't sure of any the ramifications.

**Comment by taion** [comment]
The point of the router is to declaratively map location to rendered state. If you need to prevent various re-renders, use the standard tools React gives you. Otherwise see https://github.com/reactjs/react-router/issues/266.
