### ISSUE TITLE
Warning: Link: context type `router` is invalid; it must be a function, usually from React.PropTypes.

### ISSUE THREAD

**Issue by MervynFang** [reactjs/react-router#3694]
##version
react 15.3.0 
react-router 2.6.1
use rollup to pack

I found a strange problem. When I use <Link to="">, some msg appears in the consol as follow.
```
Warning: Link: context type `router` is invalid; it must be a function, usually from React.PropTypes.
```
And I try to see the call stack. When <Link>'s craeatClass has property 'contextTypes', the stack trace is 
```
mixSpecIntoComponent => RESERVED_SPEC_KEYS[contextTypes] => validateTypeDef => 
warning.
```
 So it log in the console. 
When I remove the contextType property in `node_modules/react-router/lib/Link.js`, the warning disappered. I don't know why add the contextType will cause the warning, and why the contextType.router is undefined here.
Any suggestion to solve?

PS: I have a same project use webpack. It doesn't have any warning.

the code is in this repo [react-rollup-starter](https://github.com/MervynFang/react-rollup-starter)

**Comment by taion** [comment]
If you're only seeing this in Rollup and not webpack, I'd follow up with the Rollup folks. We're just doing the normal transpiled ES modules thing.
