### ISSUE TITLE
Params outside component

### ISSUE THREAD

**Issue by DarrylD** [reactjs/react-router#3697]
In reference to this [guide](https://github.com/reactjs/react-router/blob/master/docs/guides/NavigatingOutsideOfComponents.md) and #822

Any way to access params (or queries) while outside of the component?

This may be a feature request as it would be pretty useful.

**Comment by taion** [comment]
See https://github.com/reactjs/react-router-redux/search?q=params&type=Issues&utf8=%E2%9C%93.

**Comment by liesislukas** [comment]
i had same issue and solved it like this:

I use redux-saga for side effects, it has `select` function, so just used that to get app's current state and all the routing info is in the state. 

```
import{select, put, call} from 'redux-saga/effects';
function fitlersSelector(state) {
  return state.routing.locationBeforeTransitions.query;
}

export function* someActionHandler(action) {
  try {
    let filters = yield select(fitlersSelector);
    
}

```

State is updated by npm package `react-router-redux`

```
import {combineReducers} from 'redux';
import {routerReducer as routing} from 'react-router-redux';

export default combineReducers({
  routing,
  // .... other reducers
});
```

**Comment by im1dermike** [comment]
@liesislukas `locationBeforeTransitions` is always `null` for me...
