### ISSUE TITLE
inconsistent scroll behaviour when using Link or history.push()

### ISSUE THREAD

**Issue by PierBover** [reactjs/react-router#3699]
When using `<Link to="/something">click</Link>` the router resets the scroll position even if the route has already been shown to the user.

When using `browserHistory.push('/something')` the scroll position is kept as the last time the route was shown to the user.

I'm aware the preferred way now of changing the route is by using `withRouter(component)` but this is an inconsistent behaviour nonetheless.

**Comment by taion** [comment]
`<Link>` has no attached scroll behavior. Most likely your history is some custom history with a scroll behavior enhancement, rather than the bundled `browserHistory`.

**Comment by PierBover** [comment]
I'm using `browserHistory` with no scroll enhancement.

```
import { browserHistory} from 'react-router'
```

And then:

```
browserHistory.push('/something')
```
