### ISSUE TITLE
react router browser history doesn't work

### ISSUE THREAD

**Issue by aditcoding** [reactjs/react-router#3702]
Hi,

When I change this line `<Router history={hashHistory}>` to `<Router history={browserHistory}>`,  in 
`   
<Router history={hashHistory}>
          <Route path="/" component={M}/>
          <Route path="/a" component={A}/>
          <Route path="/b" component={B}/>
          <Route path="/c" component={C}/>
          <Route path="/d" component={D}/>
        </Router>,`

my paged stop loading. I get this error `Warning: [react-router] Location "/dist/index.html#/b?_k=xm0tin" did not match any routes`.
Please help me to fix this problem.

**Comment by taion** [comment]
It's literally what the error message says.

**Comment by aditcoding** [comment]
Thanks for the reply. What changes should I make to my route config if I am switching from hashHistory to browserHistory?

**Comment by aditcoding** [comment]
Some more info: when I use hashHistory and visit http://localhost:3000/dist/index.html the url changes to http://localhost:3000/dist/index.html#/?_k=6w1qlo and the page is loaded and all is well. But when I use browserHistory and visit http://localhost:3000/dist/index.html, I get the error "did not match any routes"
