### ISSUE TITLE
Match active router with hash symbol

### ISSUE THREAD

**Issue by rafaelcapucho** [reactjs/react-router#3704]
I have one route like **/app/servers/monitoring** described by the following code:

```
  <Router history={browserHistory}>
    <Route name="Dashboard" path="/app/" component={App}>
      <IndexRoute component={Home}/>
      <Route name="Servers" path="servers" component={ServerRoot}>
        <Route name="Monitoring" path="monitoring" component={ServerSet}/>
      </Route>
    </Route>
  </Router>
```

My interface is desgined with a Dropdown Menu, **Servers** => **Monitoring**:

![screen](https://cloud.githubusercontent.com/assets/163367/17430209/53d3a41e-5ac9-11e6-9060-e237d2a00229.png)

I'm able to set the **active class** on monitoring link using the `Link` tag but when monitoring is active is interesting that servers is also active (to leave the Dropdown menu opened when someone open it directly from URL).

It would be a lot easy if I add `to="/app/servers"` to `Link` of Servers but without the `#` my dropdown stop working, because the browser follow te link do /app/servers, of course.

```
<li className="nav-item nav-dropdown">
  <Link to="#" className="nav-link" activeClassName="active">Servers</Link>
  <ul className="nav-sub" data-index="0" style={{display: 'none'}}>
     <li><Link to="/app/servers/monitoring" activeClassName="active">Monitoring</Link></li>
  </ul>
</li>
```
There is a React-Router way to solve that? thank you.

**Comment by taion** [comment]
Use an IndexLink

**Comment by rafaelcapucho** [comment]
Hi @taion,

Thank you for your answer but I'm not sure that you understood the point.

I tested what you said, It don't solve the problem, I tested as:

```
<li className="nav-item nav-dropdown">
  <IndexLink to="#" className="nav-link" activeClassName="active">Servers</IndexLink>
  <ul className="nav-sub" data-index="0" style={{display: 'none'}}>
    <li><Link to="/app/servers/monitoring" activeClassName="active">Monitoring</Link></li>
  </ul>
</li>
```
The main point is that the Link at line 2 should be marked with class `active` when the route pointed on line 4 is also active. The problem is related to the fact that I'm pointing `to="#"` because without it the Menu dropdown won't work.

**Comment by taion** [comment]
Oh, just make `onClick` call `e.preventDefault()` then to prevent navigation.

**Comment by rafaelcapucho** [comment]
@taion 

I was aware about the `preventDefault`, I was just checking if there's a react-router way to do that.
Thank you for clarifying.
