### ISSUE TITLE
back button bug

### ISSUE THREAD

**Issue by jaewon1219** [reactjs/react-router#3709]
## Version
2.6.1

## browser
Internet Exproler 11

## Test Case
I can't reproduce with bin.

## Steps to reproduce
1. There are a lot of list with scroll-y bar.
2. scroll down(x: 0, y: 150)
3. click one of the list which will move detail page.
4. click back button
 
## Expected Behavior
when click back button, move the list page and scroll (x:0, y: 150) 
## Actual Behavior
when click back button, scroll (x:0, y: 150) and move the list page.

Have a feature request?
=======================
Remove the template from below and provide thoughtful commentary *and code samples* on what this feature means for your product. What will it allow you to do that you can't do today? How will it make current work-arounds straightforward? What potential bugs and edge cases does it help to avoid? etc. Please keep it product-centric.
-->

## Version
2.6.1

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

**Comment by taion** [comment]
React Router does not currently manage scroll position. Try an add-on package like react-router-scroll.

**Comment by jaewon1219** [comment]
I did't mean I want to move scroll position.
In IE 11, when I click <Link />, browser move scroll to top(new route).

**Comment by taion** [comment]
That's something the browser does. The router isn't doing any scrolling for you. Look up `scrollRestoration` and appropriate polyfills. There's no logic here handling scroll position at all.
