### ISSUE TITLE
createRoutes wont work on server if an array was supplied.

### ISSUE THREAD

**Issue by yanivkalfa** [reactjs/react-router#3710]
So for some reason createRoutes will not work when supplying an array on server
So take a look at this little configuration :
https://gist.github.com/yanivkalfa/30935da2d1c77bb823f80dce69326637

i think the fact that the router has a routes property and not children property is the reason it wont work as its the only thing different then the other approach

**Comment by taion** [comment]
Your code snippet is non-functional because your `routes` is not a function.

**Comment by yanivkalfa** [comment]
my routes are a function, taion i've corrected my gist 

https://gist.github.com/yanivkalfa/30935da2d1c77bb823f80dce69326637
