### ISSUE TITLE
Error when trying to execute react-router-lessons

### ISSUE THREAD

**Issue by simonkofler** [reactjs/react-router#3712]
Hi, I'm trying to execute the current  react-router-lessons, but when I execute `npm start` I get the following error log:

https://gist.github.com/simonkofler/6f51b882afebf0a5469a91554f3074da

I've installed the current node/npm versions:
- node: v6.3.1
- npm: 3.10.5

**Comment by taion** [comment]
I don't know what "react-router-lessons" is.
