### ISSUE TITLE
array in query breaks active state

### ISSUE THREAD

**Issue by aocenas** [reactjs/react-router#3713]
## Version
2.6.1

## Test Case
Sorry not yet.

## Steps to reproduce
I have a link with array of item, something like this:
```
<Link
   className="nav-item compare"
   activeClassName="is-active"
   to={{
      pathname: '/compare',
      query: {compared: compared},
   }}
>
```
which creates link for example: `compare?compared=async&compared=glob&compared=readable-stream&compared=source-map` but then somewhere in here https://github.com/reactjs/react-router/blob/master/modules/isActive.js#L146, the currentLocation.query has sometimes different order of items than query and so they do not match. Basically it seems that serialization and deserialization of arrays in query is not stable in regards to the ordering.
 
## Expected Behavior
Link would be active.

## Actual Behavior
Link is not active.

**Comment by taion** [comment]
Arrays stringify and parse out in the same order they're given. You need to make sure you consistently set up your queries in the same order.

**Comment by aocenas** [comment]
@taion not sure what do you mean, I see that after navigating to url with the array in query, the url in the browser and the href on the visited link are the same, with the same order. I will try to reproduce it but I do not really see what mistake I could have made, that would change the order of items in between transitions but then rendered them correctly afterwards.

**Comment by aocenas** [comment]
@taion The problem seems to be here:
![screen shot 2016-08-09 at 12 47 14 am](https://cloud.githubusercontent.com/assets/1014802/17499008/02f6c26a-5dcb-11e6-890c-edeee1070bf9.png)
Hope this is understandable, it seems that createHref creates url with different ordering but then when comparing it is using the original location with ordering that I supplied.

**Comment by aocenas** [comment]
Ok it seems this is a dependency issue, and the problem is with older version of https://www.npmjs.com/package/query-string in your history dependency, and with new version of query-string it is fixed, but react-router has dependency `"history": "^2.1.2"` that means I have history version 2.1.2 which is ok for react-router but that one is also ok with old query-string with mentioned bug.

@taion I see that those dependencies are updated in new alpha versions, so I am not sure whether this should be opened until then or not.

**Comment by taion** [comment]
We can't upgrade to 3.x there – it changes some semantics of the returned objects in a breaking way. You can just build a custom history and use custom stringify/parse methods, though. Frankly if you're making meaningful use of arrays there, you'd be better off using `qs` anyway.

**Comment by taion** [comment]
Upgrade to 4.x I mean.

**Comment by aocenas** [comment]
Yeah I could probably upgrade to some newer version, but I just tested that creating the `to=` myself like this:
```
<Link
  className="nav-item compare"
  activeClassName="is-active"
  to={`/compare${comparedQuerystring}`}
>
```
instead of using object with query, solves this issue.
