### ISSUE TITLE
restore documentation for v1.0/0.13 mixins?

### ISSUE THREAD

**Issue by Pomax** [reactjs/react-router#3718]
Some people are forced to work on old codebases, where the option to upgrade to an actually modern version of react-router is not as straightforward as "just upgrading it", which means having the documentation for deprecated approaches still available is super valuable.

Can https://github.com/reactjs/react-router/blob/master/docs/API.md#mixins-deprecated be restored to the actual documentation on how to load which mixin from which namespace and how to use them, even if it's on its own page that is linked from the current section? 

e.g. "**Deprecated**. Please see the [upgrade guide](), or click the following links for the deprecated [v1.0] or [v0.13] documentation"

**Comment by timdorr** [comment]
It's always there, just on a different branch or tag:

* https://github.com/reactjs/react-router/blob/1.0.x/docs/API.md
* https://github.com/reactjs/react-router/tree/v0.13.6/doc

**Comment by Pomax** [comment]
Ah. Can those links please be made explicit in the main docs then? It's not really intuitive (even if it makes perfect sense once explained) to have to switch to a different branch.

**Comment by timdorr** [comment]
It's in the Readme near the top: https://github.com/reactjs/react-router/blob/master/README.md#docs--help

**Comment by Pomax** [comment]
ah, yeah the problem there is that if you google for the docs, that is not the page you'll find, you'll find the specific page that matches what you searched for, so it's super easy not to see that until you file an issue on github and get pointed to it =)
