### ISSUE TITLE
Can't pass function in state, in location descriptor

### ISSUE THREAD

**Issue by wildeyes** [reactjs/react-router#3720]
Not mentioned in the docs that this is not possible, is it on purpose?

I'm doing something like;
```
    this.props.router.push({pathname:'/path/add/item', state: {
      onSave: state => ...
```

## Version
2.0.0

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

**Comment by taion** [comment]
That's correct. Location state is actually serialized and thus must be serializable.

**Comment by wildeyes** [comment]
Just asking, but why is it serialised?

**Comment by taion** [comment]
So it persists across things like page refreshes

**Comment by wildeyes** [comment]
I was thinking, isn't it possible to serialize functions? 

Functions could be useful for passing around callbacks, is there a reason not to support that? 

I might even pull request ':)
