### ISSUE TITLE
Replacing history state in iframe

### ISSUE THREAD

**Issue by fredddy123** [reactjs/react-router#3721]
hi guys, sorry for my bad english. I have the problem with history routing. I have the website. Website has page "A".  page "A" has iframe "i". iframe "i" has pages "i1" and "i2". When page "A" loading first time - iframe shows 

"i1" page and browser show this url: "website.com/A/i1". "i1" page has link to "i2" page. When I click that link - iframe make history.pushState(... page: "i2" ...) and iframe sends message to parent page "A", iframe says: "change your url to 'website.com/A/i2' " and browser changes url to "website.com/A/i2". 

When I click browser back button, iframe react on this thanks to react-router, changes inner history state to previous and says to page "A": "Make your url like your previous url ". And all good. Browser url changed to previous( "website.com/A/i1") and iframe rendered page "i1" and props.location.pathname shows "/A/i1".

But when I make 1 or more history.replace in iframe page "i2", and click browser back button, I got almost same result besides that the in page "website.com/A/i1", props.location.pathname shows "/A/i2". But it must show "/A/i1". How to fix that?

**Comment by taion** [comment]
If you're routing inside an iframe, you probably want to use `createMemoryHistory` – the contents of the iframe shouldn't change the page-level location.
