### ISSUE TITLE
onEnter does not have access to full Route instance (ie props, etc)

### ISSUE THREAD

**Issue by johnnyfreeman** [reactjs/react-router#3722]
## Version
2.6.1

## Test Case

In the docs, it states:

> ##### `onEnter(nextState, replace, callback?)`
Called when a route is about to be entered. It provides the next router state and a function to redirect to another path. `this` will be the route instance that triggered the hook.

So, if my `onEnter` hook has access to the route instance, I should have access the route's `props`.

Here's a brief snippet

```js
import { Route } from 'react-router';
import { connect } from 'react-redux';

/**
 * Container Component for injecting store into route instance
 */
const AuthAwareRoute = connect(
    (state) => {
        // isLoggedIn will be passed to Route as a props
        // just as if I were to do
        // <Route isLoggedIn={state.isLoggedIn} />
        return { isLoggedIn: state.isLoggedIn };
    }
)(Route);

/**
 * Route Hook
 */
function requireAuth(nextState, replace) {
    if (!this.props.isLoggedIn) {
        replace({ pathname: '/login' });
    }
};

/**
 * Route Definition
 */
<AuthAwareRoute path="/" component={App} onEnter={requireAuth} />
```

Is this a bug? Or just a lack of understanding on my part?

## Expected Behavior

Based on having access to the route's instance, I am expecting to have access to it's `props` as well.

## Actual Behavior

> TypeError: Cannot read property 'isLoggedIn' of undefined

**Comment by taion** [comment]
It's a lack of understanding on your part. This is still in the matching, before we render anything – no props exist at this point, it's just the router params and location and matched routes.

**Comment by johnnyfreeman** [comment]
Ok thanks, I get it.

But then, the docs do say you have access to the `Route` "instance". And you're saying "This is still in the matching, before we render anything" - before we _instantiate_ anything (my translation). Maybe the docs could be updated with something that clarifies that a bit? Access to Route's "instance" isn't quite right, it seems.

**Comment by taion** [comment]
It's the instance of the plain route object, not the route component.
