### ISSUE TITLE
Unexpected onEnter w/ callback parameter behaviour

### ISSUE THREAD

**Issue by davidfurlong** [reactjs/react-router#3723]
## Version
2.0.0

## Test Case
http://jsbin.com/guvicohipo/edit?html,js,output

## Steps to reproduce
Using onEnter with the async callback argument, but using it synchronously. Use case: if you don't know whether you are going to return sync or async
## Expected Behavior
Router replace to "Login Page"
## Actual Behavior
Doesn't replace route, no errors

**Comment by timdorr** [comment]
If you accept the callback argument, you have to call it for the hook to finish running. [We check the hook function argument length](https://github.com/reactjs/react-router/blob/master/modules/TransitionUtils.js#L8). If you're not doing anything async, just leave off the callback argument.

**Comment by davidfurlong** [comment]
Thanks for the rapid response @timdorr .
What if I might be doing something async or might not in the same hook? 
It seems strange to me that I can't call callback() synchronously

**Comment by timdorr** [comment]
You can. Just call callback right after you call replace.
