### ISSUE TITLE
Proposal: support `to` as an optional prop

### ISSUE THREAD

**Issue by macgyver** [reactjs/react-router#3725]
The `href` attribute of `<a>` tags in HTML5 is optional (https://www.w3.org/TR/html-markup/a.html#a.attrs.href), a link with no `href` is considered a placeholder link. In practice, I've sometimes felt the need to create placeholder links, for example to represent a model that has not been synced to the server yet and does not have a URL, or when the link is a path to the exact URL that I'm already at.

I'd like to use code like this:
```jsx
<Link to={props.model.url}/>{props.model.name}</Link>
```

if the model's url is empty, an `<a>` tag with no `href` attribute will be rendered. If the model has a url, there will be an `href`. All good so far, **but** clicking on the link with no `href` will raise `Error: <Link>s rendered outside of a router context cannot navigate.(…)`

To prevent this error, I would have to make an `onClick` handler function to `preventDefault` for clicks on links with no href, or do some other conditional rendering to display a span or something else while the link has no valid href. I'd prefer to avoid that boilerplate for every link that is potentially a placeholder link.

What do you all think about having React Router treat `<Link>` with empty `to` the same way that browsers treat `<a>` with no `href`?

**Comment by taion** [comment]
We discussed this previously in https://github.com/reactjs/react-router/issues/2319.

Your empty href is not why you're hitting that invariant – it's only triggered by https://github.com/reactjs/react-router/blob/v2.6.1/modules/Link.js#L83-L86.
