### ISSUE TITLE
Arabic url seems not working on "Refresh"

### ISSUE THREAD

**Issue by sidati** [reactjs/react-router#3726]
Hi @timdorr  ,
I've been working on An **Arabic** Web-App, clicking on link such as `http://localhost/product/هاتف` works just fine but if i click `refresh` button or hit `F5`key, the link in the address bar became `http://localhost/هاتف`and so it render another component :cry: 

Is there a fix for this issue ??
Thanks

**Comment by taion** [comment]
I'm not aware of anything in this library that would cause that. Please provide a repro.

**Comment by timdorr** [comment]
Related to #3317. 

You need to encode the URL before sending it through the router. [This comment should help](https://github.com/reactjs/react-router/issues/3317#issuecomment-210178759).
