### ISSUE TITLE
[feature] path/url helpers on router object

### ISSUE THREAD

**Issue by pke** [reactjs/react-router#3727]
Rails routing has a nice path/url helper that is automagically generated for the defined routes.

Take these routes as an example:

```jsx
<Router history={hashHistory}>
      <Route path="/" component={App}>
        { TestContainer && <Route path="/test/*" component={TestContainer}/> }
        <Route path="/retailers" component={HomeContainer} scope="retailers">
          <Route path=":id" component={HomeContainer} scope="retailers" back/>
        </Route>
        <Route path="about">
          <IndexRoute to="info"/>
          <Route path="info"/>
       </Route>
```

The router exposed with `withRouter` would provide the following, dynamically created functions:

| helper name | route path |
| -------------- | ------------ |
|`home_path` | `/` |
|`test_path` | `/test/* |
|`retailers_path(id)` | `/retailers` or `/retailers/id`|
|`about_path` |  `/about` |
|`about_info_path` | `/about/info` |

The `_url` variants would prefix the returned value from `_path` variants with the documents absolute domain.

`home_url` === `http://localhost:3000/`

It would have to be decided how the function signature looks for routes that accept arguments. I think Rails does it the way that if there is only one argument, then the function just accepts this one argument by value. If there are more than one argument in the route you have to use named call arguments:

`<Route path="/retailers/:id"/>` => `retailers_path(1)`
`<Route path="/cities/:cityId/retailers/:retailerId"/>` => `cities_retailers_path({ cityId: 1, retailerId: 2 })`
`<Route path="/test/*" component={TestContainer}/>` => `test_path("components/Button.jsx")`

This could also help in refactoring routes, as you don' have to search for `"/retailers/" || "retailers" || "/retailers"` but instead for `retailers_path` in your code.

**Comment by taion** [comment]
This seems too specific to add to core. Look at the using the middleware API to add this functionality yourself, if you want it.

**Comment by pke** [comment]
Where is the middleware API documented?

**Comment by taion** [comment]
Really just the tests right now, but it's pretty straightforward.

**Comment by pke** [comment]
Looking at `applyMiddleware` I fail to see how my proposed change could be implemented with `renderRouterContext` or `renderRouteComponent`.
I think it might be easier to just monkey-patch the `Router` component to generate my helper functions when its mounted.
