### ISSUE TITLE
Warning when making a named import on PropTypes

### ISSUE THREAD

**Issue by chcarter** [reactjs/react-router#3728]
## Version
2.6.1

## Steps to reproduce
- Add to a file: import {PropTypes} from 'react-router'

## Expected Behavior
- Should successfully do the named import without warnings, I think.

## Actual Behavior
Gives these warning messages: 
1. Warning: [react-router] The default export from `react-router/lib/PropTypes` is deprecated. Please use the named exports instead.

2. Warning: [react-router] This prop type is not intended for external use, and was previously exported by mistake. These internal prop types are deprecated for external use, and will be removed in a later version.

##Description
I am trying to add the history object to a component using the context as described in: 
https://github.com/reactjs/react-router/blob/fe9358adc864c556afff6fd472476ab84ce2d7d9/docs/api/History.md#but-im-using-classes

However, when I import PropTypes without the brackets as shown in the link above and access PropTypes.history, the object comes back as undefined. I don't understand why the warning says use the named import instead because by putting  curly braces around PropTypes this specifies a named import.

**Comment by taion** [comment]
The only non-deprecated prop type export is `routerShape`. All other imports are intentionally deprecated. You're also linking to very old docs for a version that is no longer the current version.

**Comment by chcarter** [comment]
So what is the best way to add the history object to an ES6 class?

**Comment by taion** [comment]
Please consult the docs for the version you're using. The `history` object on context has been deprecated since 2.0.0.
