### ISSUE TITLE
How to perform relative routing

### ISSUE THREAD

**Issue by demoritik** [reactjs/react-router#3733]
Hello. 
In my case i have clickable image thumbs. After clicking i have to navigate to `/picture/:id` to show full-size picture in popup. But image thumb could be clicked from different places like `www.myapp.com/people-list/` or `www.myapp.com/single-person/` . So i have to use relative routing to modify current route through pushing `/picture/:id` into it. How can i perfome it ?

**Comment by taion** [comment]
Dupe https://github.com/reactjs/react-router/issues/2172
