### ISSUE TITLE
When should normal routing be replaced with dynamic routing

### ISSUE THREAD

**Issue by mehrdaad** [reactjs/react-router#3736]
I see you provide dynamic routing [here](https://github.com/reactjs/react-router/tree/master/examples/huge-apps). 
My question is that what is an estimated rule of thumb on when to load routes dynamically vs loading all of them at once.
Do you go to dynamic routes if file size exceeds a size?
Or do you go that way if route numbers exceeds a number?
I didn't asked it on SO because I would get down-vote. sorry.

**Comment by timdorr** [comment]
It's entirely up to you. There is no rule of thumb on these sorts of things. You need to weigh things like loading times, bandwidth usage, and the capabilities of your typical audience. It obviously can vary a lot.
