### ISSUE TITLE
return false from beforeListener sometimes still pops the location

### ISSUE THREAD

**Issue by pke** [reactjs/react-router#3738]
## Version
2.4.1

## Steps to reproduce
It seems there is a race condition in history listener handling.

In my react app I use this (simplified) beforeListener to prevent back navigation in certain situations.

```es6
import { hashHistory as history } from "react-router"

history.beforeListener(location => {
  //debugger
  if (condition && location.action === "POP") {
    return false
  }
})
```

## Expected Behavior

The location is not popped when returning false.

## Actual Behavior

Without the debugger statement one can see a quick URL refresh in the Browsers URL input field.
When using the debugger the URL actually changes to the URL that was in `location.pathname` when the listener returned `false`. So navigating `back` eventually clears the history with POPs until its empty and you return to the browsers startpage.

Browser: Chrome 52.0.2743.116 m

**Comment by taion** [comment]
Dupe https://github.com/mjackson/history/issues/157

**Comment by pke** [comment]
@taion how are those issues related? I'm not refreshing the page. I'm only stepping back in history.

**Comment by pke** [comment]
@taion I think https://github.com/mjackson/history/pull/28 is closer to what I am experiencing when cancelling `listenBefore`
