### ISSUE TITLE
Link to new tab not working

### ISSUE THREAD

**Issue by SubhuMS** [reactjs/react-router#3739]
## Version
2.0.0

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

**Comment by SubhuMS** [comment]
Hi, I tried to use Link to open a component in new tab using target='_blank', but it display the white label error page, and the component is not been rendered in new tab.

**Comment by taion** [comment]
Please provide sufficient detail to reconstruct the issue if you're attempting to report a bug.

`<Link>` currently supports `target` by just opening the link as it would normally; if the component isn't rendered in the new tab, ensure that your server is serving up the URL properly.
