### ISSUE TITLE
Dispatching a redux action in componentWillMount leads to wrong location.pathname

### ISSUE THREAD

**Issue by pke** [reactjs/react-router#3741]
## Version
2.6.1

## Steps to reproduce

I am not sure if that is react-router problem or react, but since it happens during routing I'll file it here.

I have this Pages component that does page transitions using `ReactStyleTransitionGroup` which uses `ReactTransitionGroup` internally.

```es6
const Pages = ({ location, children, page }) => {
  const { pathname, state } = location
  const transition = state && state.transition
  const transitionStyles = TRANSITIONS[transition] || TRANSITIONS.fromLeft
  return <ReactStyleTransitionGroup
    component="div"
    style={{ WebkitFlex: 1, flex: 1, overflow: "hidden" }}>
    <Div
      key={"page" + pathname}
      style={{ position: "absolute", top: 0, left: 0, right: 0, bottom: 0 }}
      transitionStyles={transitionStyles}>
      { page || children }
    </Div>
  </ReactStyleTransitionGroup>
}
Pages.propTypes = {
  location: React.PropTypes.object,
  children: React.PropTypes.node,
  page: React.PropTypes.element,
}


<Route component={Pages}>
          <Route path="/account" component={AccountRoute} title="Your account" back>
            <IndexRoute component={AccountOverviewRoute} back/>
            <Route path="/activity" component={AccountActivityRoute} back/>
          </Route>
        </Route>
      </Route>
```

My AccountRoute looks like this:

```es6
class AccountContainer extends React.Component {
  componentWillMount() {
    this.props.setTitle("Your account")
  }
  ...
}
```

## Actual Behavior

When I navigate from `/account` to `/activity` I am getting an error in `ReactTransitionGroup.js:_handleDoneLeaving:166` (React 0.14.8) saying that component is `null`. And its clear why.
Because when I look at `this.refs` I see one key in there named: `.$page/activity` but the functions parameter `key` has the value of `.$page/account`. So no `component` with the key `.$page/account` can be read from it.
The key is composed in my `<Pages/>` from the routers location.

Now the interesting thing is, when I move the action dispatch code from `AccountContainer:componentWillMount` to `AccountContainer:componentDidMount` everything works as expected. That page transitions happen without any errors. All the code does is dispatching an action to the redux store. Which, I know, triggers (maybe) a re-rendering. According to the (redux, react) docs its fine to call dispatch/setState from within `componentDidMount`.

I'd like to understand whats going on here. If you think this is more related to `redux` or `react` close this an I will carry it over there.

**Comment by taion** [comment]
This doesn't seem to directly relate to React Router. Please follow up elsewhere.
