### ISSUE TITLE
"Unspecified error" from modal dialog in IE11

### ISSUE THREAD

**Issue by CASandmann** [reactjs/react-router#3742]
## Version
2.0.0
(Affects IE only as far as I know, found in IE11).

## Steps to reproduce
Make a page that calls `showModelessDialog()` with the first argument being a page that uses React Router.

## Expected Behavior
The page should load as normal.

## Actual Behavior
You will get an "Unspecified error" in the `getCurrentLocation(historyState)` function on the line that says `if (isSupported) window.history.replaceState...`.  This is likely because `window.history` has some funky issues in modal dialogs.  This does not seem to be work-aroundable because no part of the page loads if react-router errors before anything is done loading.

**Comment by taion** [comment]
If you're running in an environment that doesn't support the standard history APIs, supply a different `history` – like the memory history or a hash history.

**Comment by CASandmann** [comment]
I *am* supplying a different history.  Even when I use a hash history, this function is still throwing an error.  It seems to be required by `_historyLibCreateBrowserHistory`.  I don't really fully understand how webpack require works, all I know is that I'm not using a browserHistory anywhere in my app and this function is still being called.

**Comment by taion** [comment]
Ah. You need to import for submodules directly then, e.g. do `import Route from 'react-router/lib/Route'`.
