### ISSUE TITLE
IndexRoute component does not update

### ISSUE THREAD

**Issue by ericsoco** [reactjs/react-router#3743]
## Version
2.0.0+ (tested with v2 and v2.6.1)

## Test Case
http://jsbin.com/cimisu/7/edit?html,js,console,output
(note that jsbin doesn't seem to handle the load events of the loaded libraries properly; you have to wait a moment for the libs to load and then manually run the bin (ctrl+enter).

## Steps to reproduce
Set up an `IndexRoute` on the root path, let it render, and trigger an update of the root component.

## Expected Behavior
Both the root component and the `IndexRoute` component rerender.

## Actual Behavior
Only the root component rerenders.

The code from the jsbin above:

```
let cbs = [];
const register = cb => cbs.push(cb);
const emit = () => cbs.forEach(cb => cb());

const {
  Router,
  Route,
  IndexRoute,
  Redirect,
  Link,
  IndexLink
} = ReactRouter

const App = React.createClass({
  componentWillMount () {
    register(this.onIndexEvent);
  },
  
  onIndexEvent () {
    this.forceUpdate();
  },
  
  render() {
    return (
      <div>
        <h1>React Router Playground</h1>
        <h3>Updated: { new Date().toString() }</h3>
        {this.props.children}
      </div>
    )
  }
});

const Home = React.createClass({
  onClick() {
    emit();
  },
  
  render() {
    return (
      <div onClick={ this.onClick }>
        <p>Index Route rendered at { new Date().toString() }</p>
        <p>Click here to update.</p>
      </div>
    )
  }
});

ReactDOM.render((
  <Router>
    <Route path="/" component={App}>
      <IndexRoute component={Home}/>
    </Route>
  </Router>
), document.getElementById('app'))
```

Am I misunderstanding `IndexRoute`? The `IndexRoute` component does appear in `this.props.children` on the rerender, but it is not updated nor rendered.

**Comment by ericsoco** [comment]
I've noticed that manually re-running the route correctly renders the `IndexRoute` component. It's as if it's rendered only when the route is run, but not when its parent route's component updates.

**Comment by taion** [comment]
This isn't a React Router thing per se. This is just a consequence of your render method being impure while still rendering the same (referentially identical) ReactElement as a child. Same as with:

```js
let cbs = [];
const register = cb => cbs.push(cb);
const emit = () => cbs.forEach(cb => cb());

const {
  Router,
  Route,
  IndexRoute,
  Redirect,
  Link,
  IndexLink
} = ReactRouter

const Home = React.createClass({
  onClick() {
    emit();
  },
  
  render() {
    return (
      <div onClick={ this.onClick }>
        <p>Index Route rendered at { new Date().toString() }</p>
        <p>Click here to update.</p>
      </div>
    )
  }
});

const home = <Home />;

const App = React.createClass({
  componentWillMount () {
    register(this.onIndexEvent);
  },
  
  onIndexEvent () {
    this.forceUpdate();
  },
  
  render() {
    return (
      <div>
        <h1>React Router Playground</h1>
        <h3>Updated: { new Date().toString() }</h3>
        {home}
      </div>
    )
  }
});

ReactDOM.render((
  <Router>
    <Route path="/" component={App} />
  </Router>
), document.getElementById('app'))
```

Use React state for this sort of thing.

**Comment by ericsoco** [comment]
Thanks for the response, @taion. So is what you're saying that `IndexRoute` instantiates `Home` only once (when routing), and passes that instance as a React child, and that `App.render()` is impure because it's relying on that child to determine its output instead of any props/state passed in?

Sorry, I'm not quite understanding. How would I use state to get around this problem?

**Comment by ericsoco** [comment]
Ok, never mind, I got it. I'm maintaining application state in a Redux store and not really using React component state, nor props (in this particular case). I understand now -- React sees the exact same child component, with the same state & props, so it doesn't render it again.

Perhaps not the ideal solution, but for now I'm cloning the child in the parent `render()` with `React.cloneElement`. I'll find a more optimized solution somewhere that isn't a `react-router` issue ;)
