### ISSUE TITLE
Query string's ordering

### ISSUE THREAD

**Issue by gaulucky92** [reactjs/react-router#3744]
Hi,
I am building a search form, which will call `this.props.router.push()` on enter, and I get a problem: the ordering of the query object's properties are automatically sorted by alphabet. My SEO consultant said that the query params ordering should be put manually, not to be sorted, e.g.:

```javascript
this.props.router.push({
  pathname: '/search',
    query: {
      q: this.state.query,
      a: data.get('slug')
    }
});
```
I expect it would transit me to `/search?q=...&a=...`, but instead it shows `/search?a=...&q=...`.

This happens with the Link module, too. I tried this: 

```javascript
this.props.router.push({
  pathname: `/search?q=${this.state.query}&a=${data.get('slug')}`
});
```

but it doesn't work, instead it misunderstands to another route, not my search route, therefore crashes the app.

Is there an option to keep those query params' ordering?

**Comment by taion** [comment]
Same issue and resolution as https://github.com/reactjs/react-router/issues/3713

**Comment by gaulucky92** [comment]
I can create my own url to pass to Link's `to=` to get it work, but how about the `router.push()`? I tried the same method and it misunderstood to another route.
