### ISSUE TITLE
[react-router] `Router` no longer defaults the history prop to hash history

### ISSUE THREAD

**Issue by m-menon** [reactjs/react-router#3745]
Totally new to react and stuff and had to get a node application which uses react. Ironed out most errors except for the 2 shown in the picture. Any pointers will be great as I am a total newbie to both node n react. Thanks

```
Error 1. [react-router] `Router` no longer defaults the history prop to hash history
Error 2. bundle.js:79269 Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.
```

![react_error](https://cloud.githubusercontent.com/assets/10776430/17830836/0d04ea5e-670b-11e6-8bf3-ad4499fc1509.jpg)

**Comment by timdorr** [comment]
Provide a history to your Router, like it says.

**Comment by m-menon** [comment]
I could understand the english part where it said that it doesn't go by default anymore. Dealing with react for the first time today, out of no choice cos I need to test a nodejs react gps tracking server. A little clueless as to where to 'inject' the history into the router.

![react_router_shit](https://cloud.githubusercontent.com/assets/10776430/17832928/566fa4c2-6742-11e6-80e1-e6abe6f42427.jpg)

**Comment by taion** [comment]
This is covered in the documentation.

**Comment by timdorr** [comment]
Specifically, look at the example in the Readme. You need to add a history prop. If you don't know what a prop is, that's covered in the getting started guides for React.
