### ISSUE TITLE
Feature request: add an option to not respond to indexRoute

### ISSUE THREAD

**Issue by mehrdaad** [reactjs/react-router#3748]
In one of my route files which is a child route of another file I have a configuration as follows:

    module.exports = {
		path: 'auth',
    }

I want to design a route which responds to ``auth/login`` and ``auth/register`` but not to ``auth``. 
base path is just provided for removing common route segment. (path which is ``auth`` here).
trying to add ``indexRoute:{component:null}`` didn't return 404 on ``auth`` is there any way to ignore indexRoute?

**Comment by taion** [comment]
ATM we don't support 404ing from deep inside a route config. The best you can do is something like

```js
<IndexRoute component={NotFound} />
```
