### ISSUE TITLE
Strange error while testing

### ISSUE THREAD

**Issue by demoritik** [reactjs/react-router#3749]
Hi. I have such error : 
```
D:\front-end\node_modules\react-router\node_modules\history\lib\DOMStateStorage.js:46
    throw error;
    ^

TypeError: Cannot read property 'removeItem' of undefined
```

This error appear only in tests (i use node.js environment for testing and mocha as test runner and enzyme mount for wrapping my components). 
This error do not appear when i remove next code: 
```
browserHistory.push(`/find/${string}`);
```

**Comment by taion** [comment]
Browser history requires the actual browser API. If you're testing, consider using the memory history.

**Comment by umairwanclouds** [comment]
@taion I am facing the exact issue. Can you be more specific on how to resolve this?

**Comment by taion** [comment]
Use Karma. Or Jest.

**Comment by taion** [comment]
Or use `createMemoryHistory` instead.
