### ISSUE TITLE
[material-ui] How to use with different libraries, with buttons, not Link?

### ISSUE THREAD

**Issue by wzup** [reactjs/react-router#3751]
How do I use [material-ui](http://www.material-ui.com/) buttons as links? You force to use your `Link` component to be able to navigate routes. Your `Link` isn't a one-size-fits-all solution definitely. 

Here is `material-ui`'s `<RaisedButton>` component that can serve as a link, it has `href` attribute. How does `react-router` go with it?

```
<RaisedButton
    href="/foo"
    onClick={e => { ... }}
    label='Follow /foo'
    secondary={true}
    style={{width:'100%', height:'initial'}}
    labelStyle={{fontSize:'1.3em', lineHeight:'2.3em'}}
/>
```

**Comment by taion** [comment]
See e.g. react-router-bootstrap. The `<Link>` component here intentionally only renders a standard anchor to prevent poor a11y.
