### ISSUE TITLE
this.props.route points to the wrong Route

### ISSUE THREAD

**Issue by delijah** [reactjs/react-router#3753]
## Version
2.7.0

## Test Case
http://jsbin.com/secenap/edit?html,js,console,output
(sometimes you have to make a change to the js-code to make it run, i don't know why)

## Steps to reproduce
- Click "User Management"
- this.props.route is correct
- Go back
- Click one of the other links
- this.props.route points to the wrong route

## Expected Behavior
this.props.route on route components should point to the actual route, which means this.props.route must be equivalent to the last entry of this.props.routes[].

## Actual Behavior
this.props.route on route components does not point to the actual route in the above scenario. To get the current route i have to access this.props.routes[this.props.routes.length - 1].

**Comment by taion** [comment]
On a route component, `props.route` is the route rendering that specific component.

**Comment by delijah** [comment]
Ok. Is there a specific reason for it @taion ? That behaviour does not make sense to me at all. If i am navigating to a specific route, i want to know on which route i am, not which route renders something. Why should I?

**Comment by taion** [comment]
So just do `routes[routes.length - 1]`. They're different concepts and this does come up if a component wants to e.g. read props from the route it belongs to.

**Comment by delijah** [comment]
Ok.. for me not really understandable, but i guess i am just not enough into it :) Are there docs that describing this behaviour more clearly? Thanks anyway for your quick response 👍
