### ISSUE TITLE
Confirm navigation for custom history changes URL, even after cancel

### ISSUE THREAD

**Issue by gmacciocca** [reactjs/react-router#3755]
## React-router version
2.7.0
I have this problem in my app and was able to reproduce it in the confirm-navigation example.

## Description.
When I hit the browser back button, the URL changes to the previous history URL, then a confirmation dialog comes up.

#### Actual behavior
When I cancel out of the confirmation, my route remains the same, but the URL in the browser does not change back to where it was before I hit the back button.

#### Expected Behavior
When I cancel out of the confirmation, I expect the route and the URL to remain as they were before I hit the back button

## My changes to the example

```js
// Add useRouterHistory to import.
import { browserHistory, Router, Route, Link, withRouter, useRouterHistory } from 'react-router'

// Create my customHistory
import { createHashHistory } from 'history'
const customHistory = useRouterHistory(createHashHistory)({ queryKey: false })
```

Then I use my custom history
```js
  <Router history={customHistory}>
   ...
```

#### Before I hit the back button
![image](https://cloud.githubusercontent.com/assets/2065633/17862543/bce164da-6863-11e6-97a2-8461d4a57bae.png)

#### After I hit the back button, and the URL changes, and confirmation message appears
![image](https://cloud.githubusercontent.com/assets/2065633/17862613/009f371a-6864-11e6-89d5-b5cecb088baf.png)

#### After I cancel out of the confirmation message, the route does not change but URL remains changed
![image](https://cloud.githubusercontent.com/assets/2065633/17862648/201106fa-6864-11e6-84c7-fee9c4e825d4.png)

**Comment by taion** [comment]
This is the expected behavior. Since you've already hit "back", the browser updates the window URL; we can't prevent that from happening. The most we can do is to try to restore the old URL if the user cancels the navigation action.

**Comment by gmacciocca** [comment]
@taion thank you for your message. 
I apologize for forgetting to mention that when using the regular `browserHistory` (like in the example out of the box) the behavior is the same as the one I mentioned above, with the only difference that the react-router does change the URL back to the original one, when I click on cancel.
So I'm guessing there's already a mechanism in the code that can change the URL to what it was before "back"  was pressed, but it does not get executed with custom (hash) history.
I hope I'm giving you enough information this time.
