### ISSUE TITLE
[Feature Request] Up navigation

### ISSUE THREAD

**Issue by romulof** [reactjs/react-router#3757]
Android has a navigation pattern called up navigation  that is very useful and I'm missing a lot in `react-router`. [[Link](https://developer.android.com/training/implementing-navigation/ancestral.html)]

Let's say we have an email app with 4 views: `list`, `detail`, `reply` and `compose`.
The navigation tree looks like this:
```
list
┣━ compose
┗━ detail
    ┗━ reply
```

Each view has an parent view defined:
`list` -> _null_ (it is the root view)
`compose` -> `list`
`detail` -> `list`
`reply` -> `list` (this is the tricky one)

If we follow this navigation path `list->detail->reply` and call `history.goBack()` we go back to `detail` view, but calling instead `history.goUp()` would take us to the parent view: `list`.

The code for up navigation search the history looking for the closest instance of the parent view, if it's not found, it replaces current location with parent's.

Code would look like this:
```es6
function goUp() {
  const backStack = [...]; // Get this from history provider
  const parentPath = '/list'; // Get this from current view

  const pathEscaped = parentPath.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, "\\$&");
  const pathRegexp = regexp`^${pathEscaped}[\?|$]`; // Provide better matching.

  for (const index = backStack.length - 1; index >= 0; index--) {
    const location = backStack[index].location;
    if (pathRegexp.match(location)) {
      // Found in back stack
      return history.go(index - backStack.length);
    }
  }

  // Not found
  return history.replace(parentPath);
}
```

**Comment by taion** [comment]
While that navigation pattern is idiomatic on mobile, it's not especially idiomatic on web. Feel free to implement this in user space, though.

**Comment by peteruithoven** [comment]
I feel this could be very useful for closing popups and nested hamburger menu's for example, especially when the user started on that page (deep linked).
