### ISSUE TITLE
<Link> requiring two clicks to navigate

### ISSUE THREAD

**Issue by Ajaay** [reactjs/react-router#3758]
For some reason it's taking two clicks for Link to navigate to the page. On the first click it updates the URL but renders a blank page. On the second click the page content is loaded.

I'm using it along with Material UI like so:

```js
<MenuItem
          primaryText="Manage Users"
          containerElement={<Link to="/manageusers" />}
/>
```

Seems very similar to what was described in issue #1506 but there was no reported resolution to that one.

Any ideas?

Thanks

**Comment by taion** [comment]
Please provide a repro.

**Comment by Ajaay** [comment]
Through further testing this appears to be a problem with Material UI rather than react router. 

On a side note, just a general comment to say that closing the issue a day after requesting a repro is a little hasty. I'm sure plenty of people using rr are full time on other projects and therefore may not have the time to put something together in such short a time.
