### ISSUE TITLE
<Link>

### ISSUE THREAD

**Issue by zp1112** [reactjs/react-router#3760]
I want to use <Link> to make SPA,but once two or more of my components have timer，when to clearTimeout when I change the path?Because when I use <Link> to change the path,the timers still run,that is not what I want.
How and when should i clearTimeout? use componentWillUnMount?Tried but it dosen't work

**Comment by taion** [comment]
`componentWillUnmount` is the right hook to use in React to clean things up when components unmount.

**Comment by zp1112** [comment]
thanks!
