### ISSUE TITLE
setRouteLeaveHook doesn't work as expected with dynamic routes

### ISSUE THREAD

**Issue by ilyabo** [reactjs/react-router#3761]
## Version
2.7.0

## Test Case

setRouteLeaveHook doesn't seem to play well with getChildRoutes. After some debugging I could see that it is related to how getRouteID works internally.

Here is a test case:
http://jsbin.com/jizese/edit?js,output

## Steps to reproduce
Click on "Page 1", then "Page 2", then "Home"

## Expected Behavior
"Leaving page 1" should be shown in an alert window when leaving Page 1
"Leaving page 2" should be shown in an alert window when leaving Page 2

## Actual Behavior
"Leaving page 1" is show when _opening_ Page 1
Nothing is shown when leaving Page 2

**Comment by taion** [comment]
This is unavoidable – if you change the route objects such that there's no more referential equality, how are we supposed to identify them?

If you're using dynamic routes and route leave hooks, make sure you memoize the route objects.

**Comment by ilyabo** [comment]
I understand. Could you elaborate on how to memoize the route objects for this to work? Thanks in advance!

**Comment by ilyabo** [comment]
BTW, each route has a path and is placed somewhere in the tree of nested routes. If you join paths of the routes from the root to a leaf, you should get a unique identifier for this leaf route. Couldn't this be used in getRouteID instead of the generated numbers?
