### ISSUE TITLE
Escaping of query values is too aggressive

### ISSUE THREAD

**Issue by mologie** [reactjs/react-router#3764]
Hello,

this is a cosmetic issue: The values of the object passed as query parameters (either though the Link component or through the router API) are escaped very aggressively. The resulting URLs are quite ugly and hard to read for humans.

I would like to propose a change to this behavior: React Router should only escape characters in the query's value which would otherwise break the query.

According to https://tools.ietf.org/html/rfc3986#section-3.4, the only character which breaks a query is (technically) the `#` character. However, since we're using the query as key value store, `?`, `&` and `=` should also be escaped for readability (through it's technically irrelevant). `&` and ` ` may require special encoding depending on the implementation, but this library already appears to handle these cases correctly (I did not test further).

## Version
2.7.0

## Test Case
http://jsbin.com/laleruquyu/edit?html,js,output

## Steps to reproduce
Open the test case, click the link.

## Expected Behavior
I expected output similar to:  
`URL: http://null.jsbin.com/runner#/b?books=1,2,3`

## Actual Behavior
`URL: http://null.jsbin.com/runner#/b?books=1%2C2%2C3`

**Comment by timdorr** [comment]
We use [`history`'s query parsing](https://github.com/reactjs/react-router/blob/master/modules/useRouterHistory.js#L1) by default. If you want to change the behavior of how things are parsed and serialized, you're more than welcome to: https://github.com/mjackson/history/blob/v2.x/docs/QuerySupport.md

**Comment by mologie** [comment]
Thank you for your response and for pointing me into the right direction. In practice it would be possible to replace the query stringification implementation like you suggested. This indeed worked like a charm with all modern web browsers during my tests, but goes against the RFC.

Thus, for future readers: My approach itself was wrong because is misinterpreted the RFC: https://tools.ietf.org/html/rfc3986#section-2.2 specifies that `,` is reserved as delimiter character and must therefore be escaped if it appears as value in the query string (even if it would not break the query string). If the values delimited by the delimiter are longer than the query key, it might also work to simply duplicate the key per value. This is valid per RFC, but may not be supported by all parsers.
