### ISSUE TITLE
Route properties

### ISSUE THREAD

**Issue by Agrosis** [reactjs/react-router#3766]
Note: This is not about passing props to a route.

In my app I have a couple of routes, some of which are authenticated only routes and some of which are non-authenticated only routes. At some point, I need to verify that the user is authenticated or a guest, to allow or revoke access to that route.

I didn't exactly want to handle that logic in every component, so I put it in a component higher on the route hierarchy. Up there, I have two arrays of strings, one that contains the paths for authenticated routes, and one for non-authenticated routes. That component receives `location` as a prop from the router, and whenever the path changes, I would check if they're allowed to go there based on their authentication status and whether the route is authenticated-only or not, etc.

But, that might be unfeasible as the project grows, routes are added, removed, and changed. I'd have to constantly keep track of  It would be nice if a `properties` (could be a misleading name) could be defined on the `Route`, which would then be passed along inside the `location` prop.

Usage would be something like this:

```
<Route path="/" component={App}>
  <Route path="/account/create" component={CreateAccount} properties={{auth: false}} />
  <Route path="/account/login" component={LogInAccount} properties={{auth: false}} />

  <Route path="/account/settings" component={AccountSettings} properties={{auth: true}} />
</Route>
```

Now, we can specify exactly which routes are authenticated or not, right in the route configuration. `App` would receive the `location` object and `location.properties.auth` would let us know if they're at an authenticated route or non-authenticated only route.

I think my scenario could definitely be achieved with a HOC, but I'm putting it out here in case anyone else could come up with more compelling use cases.

What do you guys think?

**Comment by timdorr** [comment]
Just wrap all of your authenticated Routes in one that handles the checks for you:
```jsx
<Route path="/">
  <Route component={AuthorizedOnly}>
    <Route path="/user" component={User} />
    <Route path="/settings" component={Settings} />
  </Route>
</Route>
```

**Comment by taion** [comment]
The other thing you can do is check `props.routes`, e.g. you could do

```js
props.routes.some(route => route.properties && route.properties.authenticated)
```
