### ISSUE TITLE
React app freeze when clicking Link

### ISSUE THREAD

**Issue by Attrash-Islam** [reactjs/react-router#3767]
Hi,
I've built this app on http://138.68.78.96/
I'm attaching a GIF image that indicate that the url is changed when clicking on top menu but the app is not rendering until I move the mouse in or out!! I'm clicking just one click, and you can try it live (In the GIF I'm navigating from the / {Home component} to /about {About component})

![anim](https://cloud.githubusercontent.com/assets/7091543/18049212/78590bb0-6def-11e6-8d5c-5b339fbd135d.gif)

![router](https://cloud.githubusercontent.com/assets/7091543/18049263/d5b2c8f0-6def-11e6-9737-882073c15bbc.png)

![app](https://cloud.githubusercontent.com/assets/7091543/18049268/da6e1dae-6def-11e6-84a7-941b44d06d11.png)

![about](https://cloud.githubusercontent.com/assets/7091543/18049269/de647ad4-6def-11e6-90af-a14c6c7f3ce9.png)

Thanks

**Comment by timdorr** [comment]
Works just fine for me. Perhaps you have some sort of browser extension interfering? Try it in an Incognito window instead.

**Comment by Attrash-Islam** [comment]
Well. Thanks :)
