### ISSUE TITLE
ReactEventListener.js event are not bound to Link component on Safari

### ISSUE THREAD

**Issue by DWboutin** [reactjs/react-router#3768]
Hi! I just saw that my application's router doesn't work on Safari (v8.0.8). 

When i use the `Link` component, all is ok in Chrome but in Safari, it doesn't trigger any history changes or other react-router related event. 

See: http://imgur.com/a/GA7bI

Sorry, it's in french for the Safari screenshot, but you can see the event from `ReactEventListener.js` is missing. I just created a SO question (http://stackoverflow.com/questions/39214033/react-routers-links-doesnt-work-on-safari-v8-0-8), but it's probably a bug. 

Sorry if it's not and thank you for your help!

**Comment by taion** [comment]
We cover Safari 8: https://github.com/reactjs/react-router/blob/ab4552d2ea0ec5c0cf3c534bca654a1af3ea0dec/karma.conf.js#L31-L37

In general we're not doing anything novel with event handling. If something's weird, it's probably a bug upstream.
