### ISSUE TITLE
Returning false in setRouteLeaveHook changes URL

### ISSUE THREAD

**Issue by kig-rob** [reactjs/react-router#3772]
Trying to setup a custom alert when the user leaves the page before saving their changes. When returning false in the callback for setRouteLeaveHook, the URL updates when pressing the back button. This does not happen when returning a string and clicking cancel on the browser prompt.

## Version
2.7.0

## Steps to reproduce
```js
  componentDidMount() {
    this.props.router.setRouteLeaveHook(this.props.route, this._leaveHandler);
  }

  _leaveHandler() {
    return false;
  }
```

## Expected Behavior
When hitting the back button, component should not unmount and the route should not change, including the URL.

## Actual Behavior
When hitting the back button, the component does not unmount, but the URL changes.

**Comment by taion** [comment]
Please provide a repro.

**Comment by taion** [comment]
In neither case can we do prevent the URL from changing when the user hits the back button. It's just what the browser does. For both, there are some cases where the subsequent restore of the URL fails. That's https://github.com/mjackson/history/issues/157.
