### ISSUE TITLE
Default param with active link handling

### ISSUE THREAD

**Issue by aight8** [reactjs/react-router#3774]
I have route like ```/some(/:page)```. I have a link which point to ```/some``` because the page param is not known in the menu. I don't want to redirect the user to ```/some/my-page-1``` every time he visit ```/some```. I only want to set the current active ```page``` right in the component.
I cannot use ```IndexRoute``` because ```page``` is variable and the component which is used is dynamic.
How can I make this?

**Comment by taion** [comment]
If you want to handle this in the component, then do just that – handle it in your route component with something like `params.page || 'my-page-1'`.

**Comment by sebfek** [comment]
Exactly that I make. But then the link is not active for /some/my-page-1
