### ISSUE TITLE
Error throws when use browserHistory.push/replace at redux reducers.

### ISSUE THREAD

**Issue by shinxi** [reactjs/react-router#3775]
Hi all,

First of all, react-router is amazing when working with react + redux. 
But we just met some issue when working with redux reducers. 
Here is our scenario.
When user click logout button, send a logout event to backend, if response is success, just redirect to the home page. 

![react_issue_logout_reducers](https://cloud.githubusercontent.com/assets/1262296/18113232/9303e2b0-6f60-11e6-999c-12114590af09.png)

It works well until we register some redux actions at componentWillUnmount event in order to clean component state, 
![react_issue_unmout](https://cloud.githubusercontent.com/assets/1262296/18113245/a433a49e-6f60-11e6-905a-d9d5ec94a182.png)

then the logout gets failed, console throws an errors and the page won't redirect to the home page.
![react_issue_error](https://cloud.githubusercontent.com/assets/1262296/18113249/ae20b82a-6f60-11e6-9254-5dedca9487b5.png)
That is because the state at the redux reducer must return first before any further redux actions.

Currently we just wrap browserHistory.push with a timeout function to let it work(so that the state can get returned first), any better advice? 
Maybe we can just implement react-router's browserHistory.push in an asynchronous way, not sure if it is a bad idea...

Any reply is appreciated. Thanks in advance.

**Comment by taion** [comment]
This is out of scope. Please check with react-router-redux.
