### ISSUE TITLE
browser.js:49Warning: [react-router] `Router` no longer defaults the history prop to hash history. Please use the `hashHistory` singleton instead. http://tiny.cc/router-defaulthistory

### ISSUE THREAD

**Issue by ITtong** [reactjs/react-router#3778]
browser.js:49Warning: [react-router] `Router` no longer defaults the history prop to hash history. Please use the `hashHistory` singleton instead. http://tiny.cc/router-defaulthistory
在控制台报这个错误，但是我没有找到原因，我的代码如下：
![d2843af3-b65a-1085-68f8-bb81e24c36dc](https://cloud.githubusercontent.com/assets/19646825/18153834/98fe5240-7032-11e6-97ce-bfae8ebf35ba.png)
这是router文件夹中的index.js的路由配置项。
![0394c02c-02a5-8fcb-24ad-53aa9b73aa3d](https://cloud.githubusercontent.com/assets/19646825/18153865/bc053a38-7032-11e6-96c0-6fb777f4f505.png)
求大神告知这是什么问题！

**Comment by taion** [comment]
应该是

```js
const Routes = ({ history }) => (
  <Router history={history}>
```

**Comment by ITtong** [comment]
@taion thanks！
