### ISSUE TITLE
Docs for history api

### ISSUE THREAD

**Issue by tehandyb** [reactjs/react-router#3783]
I was looking for documentation on how to use the API for browserHistory. I see that it uses HTML5 History api, but wasn't clear on if it had all the functions of the HTML5 history api, because it looks like it has some convienience functions added. 

In particular it would be nice if the most used functions were documented like browserHistory.push and browserHistory.replace.

**Comment by timdorr** [comment]
It's documented in the `history` library: https://github.com/mjackson/history/tree/master/docs

**Comment by tehandyb** [comment]
Ah thanks, I wasn't clear on that for some reason.
