### ISSUE TITLE
[bug] onEnter asynchronous function causes discarding server-side rendering

### ISSUE THREAD

**Issue by michalg42** [reactjs/react-router#3791]
## Version
2.7.0

## Steps to reproduce
clone repo "git clone https://github.com/michalg42/react-router-ssr"
npm i
npm run build
npm run start
Open "localhost:3000"

## Expected Behavior
Using ssr, all content should be rendered in server, client should check that output is same and the end.

## Actual Behavior
ssr rendered page, but it wasn't same as in client side and ssr was discarded.

It,s caused by onEnter in routes.js that has setTimeout (in this example, in my real app there is request to server in order to check if user is logged in), each asynchronous code is failing, as far as I understand because react checksum is fired before onEnter function is finished, therefore no page is rendered.
Not sure if it's bug in react router, react itself or I'm doing something wrong, so correct me, if I'm the reason of this bug. ;)

**Comment by taion** [comment]
This is covered in the server-side rendering guide.
