### ISSUE TITLE
Ability to unsubscribe from hashHistory.listen()

### ISSUE THREAD

**Issue by Edgesyntax-Kwame** [reactjs/react-router#3792]
While trying to find the best solution for creating my own breadcrumb, I found it difficult to get route information into a sibling component in my case a navigation bar.

As of right now i'm using the `hashHistory.listen()` method and splitting the response using `event.pathname.split("/")`. This method works but since i'm using an event listener i receive an error if i navigate to a new route that doesn't contain my component. This the the expected behavior which leads me to think that there should be an `unlisten()` method to hashHistory.

Another plus would be to have both parent and child routes listed in the `hashHistory.listen()` response. This would help tremendously in know the exact components used to render parameters.

**Comment by taion** [comment]
If you're looking for location, the router passes that down to you.

**Comment by taion** [comment]
Or use the injected `routes` prop.

**Comment by Edgesyntax-Kwame** [comment]
that would work if my sibling component was defined as a route.

**Comment by Edgesyntax-Kwame** [comment]
@taion can you reopen this issues because the propose solution doesn't apply to my use case.

**Comment by timdorr** [comment]
First, the return from `history.listen()` is an "unlisten" function you can call. 

But you're provided the location on your route component. Pass that down via props to your breadcrumb component if you need it deeper in the tree.

**Comment by Edgesyntax-Kwame** [comment]
I just tried using the returned unlisten method but i'm still getting the same error.
```
componentWillMount(){
    this.hashHistoryListener = hashHistory.listen((event) => {
      var breadcrumb = event.pathname.split("/");
      var activeComponent = breadcrumb.pop();
      this.setState({breadcrumb, activeComponent})
    });
  }
  componentWillUnmount(){
    this.hashHistoryListener();
  }
```

*router.jsx*
```
<Route path="location/:locationId" component={Layout}>
  <IndexRoute component={Dashboard} />
  <Route path="dashboard" component={Dashboard}></Route>
  <Route path="items" component={Items}></Route>
  <Route path="reports" component={Reports}></Route>
  <Route path="*" component={NotFound}></Route>
</Route>
...
```
Having my breadcrumb as a child component will solve the problem but my breadcrumb is couple together with my navigation component. I choose this pattern because i have multiple parent views each with multiple child views. Im trying to prevent my entire navigation/breadcrumb component from re-rendering as i navigate through my child views. I could decouple my navigation and breadcrumb but i'm also displaying the active component on my navigation bar.

**Comment by Edgesyntax-Kwame** [comment]
After further research i finally understand what you were both trying to convey.
I couldn't wrap my mind around how a parent component would know a child component's route without re-rendering. but for anybody looking to accomplish the same task you can get all active routes in a child component by passing `routes={this.props.routes}` to the component and access the current route object using `routes[routes.length -1]`

Thank you both.
React router is awesome.
