### ISSUE TITLE
setRouteLeaveHook does not work with child routes

### ISSUE THREAD

**Issue by todesignandconquer** [reactjs/react-router#3793]
## Version
2.7.0

## Test Case
```
<Route path='/rootPath'>
  <Route path='childPath/:id'>
    <IndexRoute component={ChildIndexComponent} />
    <Route path='childPathA' component={ChildComponentA} />
    <Route path='childPathB' component={ChildComponentB} />
  </Route>
</Route>

class ChildComponentA extends Component {
  componentWillMount () {
    const {
      router, route
    } = this.props

    router.setRouteLeaveHook(route, this.routerWillLeave)
  }

  routerWillLeave = (nextLocation) => {
    return 'Are You Sure?'
  }
}

export default withRouter(ChildComponentA)

// Some header component
<Link to={ `/rootPath/childPath/${ id }/childPathA` }>Child Path A</Link>
<Link to={ `/rootPath/childPath/${ id }/childPathB` }>Child Path B</Link>
```

## Steps to reproduce
Clicking on Child Path B

## Expected Behavior
Clicking on Child Path B should trigger the alert dialog to prompt to continue

## Actual Behavior
Clicking on Child Path B does not trigger the alert dialog to prompt to continue

This used to work before in React 14 and React-Router 2.6.0, but something has changed with the upgrade where child path changes do not trigger the `setRouteLeaveHook`.

**Comment by timdorr** [comment]
I can confirm this works just fine as you have it configured in React 15 and 2.7.0. Something else must be busted elsewhere. Maybe try blowing away your node_modules directory?

**Comment by todesignandconquer** [comment]
Except this is broken in production as well. I can try blowing away the node_modules directory but the code that handles this hasn't changed since first implemented and it seemingly only stopped working recently without any code surrounding the logic being modified.
