### ISSUE TITLE
Deprecate call to PropTypes

### ISSUE THREAD

**Issue by hpaul** [reactjs/react-router#3796]
## Version
2.7.0

## Test Case
Anywhere `InternalPropTypes.js` is used.

## Fix
React throws an error when code call PropType functions, as in this [file](https://github.com/reactjs/react-router/blob/master/modules/InternalPropTypes.js#L10).

As specs [recommend](https://facebook.github.io/react/warnings/dont-call-proptypes.html), in future React this would be deprecated.

**Comment by janv** [comment]
This is addressed in 92824f606071cd1ee383a3509e26f36016a35bb2
