### ISSUE TITLE
Better ConfirmingNavigation documentation?

### ISSUE THREAD

**Issue by suprMax** [reactjs/react-router#3797]
I'm trying to implement "ConfirmingNavigation" functionality and having trouble following current documentation. Speaking of these 2 pages in particular:

https://github.com/reactjs/react-router/blob/master/docs/guides/Histories.md
https://github.com/reactjs/react-router/blob/master/docs/guides/ConfirmingNavigation.md

It looks there are 2 ways of achieving essentially the same thing: using `setRouteLeaveHook` or using  `listenBefore` method of History. It looks to me (correct me if I'm wrong) that neither work out of the box. Consider a case where you have a deeply nested form that doesn't have current route in props, but needs to prevent navigation. For simplicity router is accessed via context, essentially having this:

```
...
componentDidMount: function() {
  var test = function() { console.log('hello'); };
  this.context.router.listenBefore(test); // or setRouteLeaveHook
}
...
```

1. `setRouteLeaveHook`: because the component is deeply nested, it's hard to get a hold of current route, and you need to pass a route object, not just a pathname. This makes using this method a bit complicated. In my case this method didn't invoke the callback, which might be related to https://github.com/reactjs/react-router/issues/3793
2. `listenBefore`: this is not being called at all with default setup. I'm using `browserHistory` that is shipped with react-router (importing like `require('react-router/lib/browserHistory')`)
3. `listenBeforeUnload`: when trying to use History directly, you need to use specific version (2.x). Maybe this needs to be mentioned in the documentation. I tried to go through API Docs of History and make it work with new version only to see an error after I set everything up correctly. With History 2.x I managed to get `listenBeforeUnload` working after using `useBeforeUnload` wrapper. `listenBefore` still didn't work at all. Perhaps History instance needs to be wrapped in some of those "enhancer" middlewares, it's not clearly documented at this point.

Can you please point me at the documentation or an example where this functionality is implemented with current react-router and some version of History? SO has no issues regarding this, and following examples gets me nowhere with callbacks not being called.

**Comment by taion** [comment]
See the "confirming navigation" example. Use `setRouteLeaveHook`.

**Comment by suprMax** [comment]
Brilliant answer, that totally resolved my problem and the problems of future users. Thanks!

**Comment by suprMax** [comment]
Example only works because it's not a deeply nested Form component and receives `route` prop directly from the router. If you have deeper complexity you'd have to somehow pass `route` down or use redux, both cases are a pain.

But hey thanks for ignoring this and giving a generic answer.

**Comment by taion** [comment]
And, yes, as currently set up, you're supposed to pass down the `route` object. It's probably not a great API but there's not really any chance to fix that here now.

**Comment by suprMax** [comment]
None of the methods in the docs/examples work for me. I think I have some complicated router setup. I will try to break your example to isolate.

**Comment by suprMax** [comment]
@taion I managed to isolate the issue. It is due to a strange behavior in History. Apparently if you have `listenBefore` hook set before router starts, and this hook confirms that navigation is allowed, `setRouteLeaveHook` is never being called. I would assume from the documentation that every hook is called and only if every hook passes, the navigation occurs. I guess cc @mjackson.

Essentially:
function test() { return true; }
browserHistory.listenBefore(test)

**Comment by suprMax** [comment]
P.S. for anyone having the same issue, this quick monkey-patch seems to work.

```
var _handler = browserHistory.listenBefore;
var _stack = [];

browserHistory.listenBefore = function (callback) {
  _stack.push(callback);

  return function() {
    _stack = _stack.filter(function(item) { return item !== callback });
  };
};

_handler(function(){
  var canNavigate;

  for (var i = 0, l = _stack.length; i < l; i++) {
    canNavigate = _stack[i].apply(this, arguments);
    if (typeof canNavigate === 'string' || !canNavigate) {
      return canNavigate;
    }
  }

  return true;
});
```

**Comment by Rahulputhukkot** [comment]
@suprMax It happened to me also but the fix you suggested had a minor issue with mine.The listenBefore ensures the confirmation but only after changing the route.When i press back button the route get changed only then it shows a confirmation dialog.

**Comment by suprMax** [comment]
@Rahulputhukkot you need to use their additional navigating away plugin thing. this is only for internal router navigation

**Comment by livemixlove** [comment]
Having the same issue here.  Top level routes seem to work as expected using the setup from the example.  When navigating away child routes, setRouteLeaveHook isn't being called. 

For example:

- TopLevel A (setRouteLeaveHook is set in componentDidMount())
   - ChildA1
- TopLevel B
   - ChildB1


TopLevel A -> TopLevel B  (all good, setRouteLeaveHook function is called)
ChildA1 -> TopLevel B (setRouteLeaveHook is not called )
ChildA1-> ChildB1 (setRouteLeaveHook is not called )

If feels like something is missing from the documentation/example? Or am I misunderstanding something?  I also tried setting setRouteLeaveHook on the Child route with a passed-down route object, to no avail.

**Comment by livemixlove** [comment]
If it's relevant:
To create my browser history I'm doing the following:
```
const history = useRouterHistory(createBrowserHistory)(
				{
					basename: baseUrl,
				}
			)
```

**Comment by livemixlove** [comment]
Oh, now I see, I didn't fully understand what passing down the route object meant.  Not sure if this is the recommended way, but I found that that route object on child routes needs to be used like:

`router.setRouteLeaveHook(route.childRoutes[0], this.routerWillLeave.bind(this))`

Seems a bit messy, but it's now working.

**Comment by ii5tl** [comment]
When change in route wont trigger component unamount, for this case setRouteLeaveHook is better set in componentWillReceiveProps()) instead of componentDidMount.

**Comment by hyq2015** [comment]
@livemixlove ,yes u are right!!
