### ISSUE TITLE
How to use react-router to build a RESTful API?

### ISSUE THREAD

**Issue by WikiOops** [reactjs/react-router#3800]
Does it support it?
I want to use react-router to replace iron-router in
https://themeteorchef.com/recipes/writing-an-api/

Sorry, pls close it if it's not an issue. Thanks in advance.

## Version
2.0.0

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

**Comment by SBRK** [comment]
React-router is made to work with react, which is a framework for building client-side, front-end interfaces, not REST APIs.

**Comment by JWDobken** [comment]
@WikiOops dit you find a solution?
I have the exact same issue and would like to build a restfull api on my meteor application.

**Comment by leite08** [comment]
I'm using [simple:json-routes](https://atmospherejs.com/simple/json-routes), which also has [alternatives for different scenarios](https://github.com/stubailo/meteor-rest/).
