### ISSUE TITLE
window is null when going back in the browser after a refresh

### ISSUE THREAD

**Issue by SBRK** [reactjs/react-router#3802]
Say I have two routes `route1` and `route2`, I am on `route1` then go to `route2`. After `route2` is loaded, I refresh the page. `route2` is correctly loaded. I then go back to `route1` by pressing the back button of the browser. `route1` starts to load but then I get an exception in some of the core code of React where it tries to do a `removeEventListener` on `window`. `window` is `null` and I don't know why (how can it ever be null ?) :/
I'm using the `browserHistory` (with a redirection to index.html on the server) and react-router 1.0.3

**Comment by timdorr** [comment]
It sounds like you're trying to use a browserHistory on the server? You should be using a memory history, or just `match`.

**Comment by SBRK** [comment]
It's not on the server, all is client side.
The only thing the server does is apache redirecting all routes to the same page where the app using ReactRouter is

**Comment by icl7126** [comment]
I have a same problem (although without React). If I go back to my site, javascript is executed but the `window` object is `null`. Also it happens only if I go back from specific site to my site. Seems like bug in Chrome.
