### ISSUE TITLE
README.md contains broken links

### ISSUE THREAD

**Issue by BurningEnlightenment** [reactjs/react-router#3805]
Hi,

in your readme under `### Docs & Help` you provide the following links:
```
- [Guides and API docs](/docs)
- [Changelog](/CHANGES.md)
```
unfortunately they point to `https://github.com/docs` and `https://github.com/CHANGES.md` after being rendered by github :wink:

**Comment by BurningEnlightenment** [comment]
:hushed: just saw that there is already a pr fixing the first broken link: #3804

**Comment by taion** [comment]
This is a bug or other change with GitHub's markdown rendering: https://github.com/github/markup/issues/926

Let's hold off on making any changes until that upstream issue is resolved. We use this link pattern elsewhere.

**Comment by timdorr** [comment]
It's been fixed!
