### ISSUE TITLE
New version breaks router `replace`

### ISSUE THREAD

**Issue by blainesch** [reactjs/react-router#3807]
## Version
2.8.0

## Test Case
http://jsbin.com/ciqurodeda/1/edit?html,js,output

## Steps to reproduce
* Replace query with string: `replace({ pathname: '/', query: { name: 'meow' } })`

## Expected Behavior
* Assert `name` is in url once
* Assert `value` comes back as string `meow`

## Actual Behavior
* Assert `name` is in url twice
* Assert `value` comes back as array `['meow', 'meow']`

## Additional Information

This behavior does not happen in `2.7.0` and is likely related to [this line](https://github.com/reactjs/react-router/compare/v2.7.0...v2.8.0#diff-6f45a74cf5bd28187670b1f6a2add4daL271).

**Comment by taion** [comment]
Fixed in 2.8.1

**Comment by blainesch** [comment]
Thanks!
